### ISSUE TITLE
network_mode: "host" probably not working as expected

### ISSUE THREAD

**Issue by ealves-pt** [docker/for-mac#1031]
I'm trying to run from a `docker-compose.yml` the a service with `network_mode: "host"` but it doesn't seem to be working as expected in OS X.

Having the `docker-compose.yml`:
```yaml
version: '2'
services:
  db:
    image: postgres:9.6.1-alpine
    environment:
      POSTGRES_USER: arexdb_dev
      POSTGRES_PASSWORD: arexdb_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/docker-data/postgresql:/var/lib/postgresql/data/pgdata
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    network_mode: "host"
```

### Expected behavior

Running `nmap -sT 127.0.0.1` should output:
```
PORT     STATE SERVICE
5432/tcp open  postgresql
```

### Actual behavior

Running `nmap -sT 127.0.0.1` doesn't show the expected port.
