### ISSUE TITLE
Container takes 3 minutes to start; http requests 30+ seconds once up.

### ISSUE THREAD

**Issue by guice** [docker/for-mac#1149]
### Expected behavior

docker container start up immediately, things process through in reasonable time.

### Actual behavior

docker container takes 3 minutes to start up and show itself in the logs. It seems to be related to only this mac book -- my image works fine on Digital Ocean account and other laptop.

Once up, HTTP requests take 30+ seconds to process.

### Information
```
Docker for Mac: version: 1.12.6 (a3b0f1129)
OS X: version 10.12.2 (build: 16C68)
logs: /tmp/201A6A3E-8984-4DD3-B6AB-8E7EA72E474B/20170116-152658.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```
[20170116-152658.tar.gz](https://github.com/docker/for-mac/files/709641/20170116-152658.tar.gz)

### Steps to reproduce the behavior

I don't know how to reproduce this. [Here's a video demonstrating the problem](https://vimeo.com/199746000). It took 3 minutes for my nginx/fpm container to finally start -- from the time hitting docker-compose up, to the time logs finally disabled. 

It uses my custom `gpcentre/php7-fpm-nginx` image. This image runs fine on my DigitalOcean account and my other laptop. I ran into similar issues with `richarvey/nginx-php-fpm` thinking it was the image, I converted to my custom one.

### Docker-compose file
```
version: '2'
services:
  myfamli:
    image: gpcentre/php71-fpm-nginx
    env_file: .env
    ports:
      - "8080:80"
      - 443
    links:
      - db
    volumes:
      - ./myfamli:/var/www/html
      - ./etc/zzz-docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
  db:
    image: mariadb
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
```
