### ISSUE TITLE
It is possible to run docker-compose into docker?

### ISSUE THREAD

**Issue by benbor** [docker/for-mac#1155]
Hello! I need use docker-compose from docker container (jenkins). I can get access to docker via mounting `/var/run/docker.sock` and `/usr/bin/docker`. But i  can't mount `/usr/bin/docker-compose`.  Is it possible to run docker-compose into docker for mac?

My docker-compose.yml :
```
---
version: '2'
services:
  jenkins:
    image: jenkins
    container_name: jenkins_container
  
    ports:
  ...
    volumes:
     ...
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
#this row doesn't work 
      - /usr/bin/docker-compose:/usr/bin/docker-compose

```
### Information
Docker for Mac: version: 1.12.6 (a3b0f1129)
OS X: version 10.12.2 (build: 16C67)
logs: /tmp/1DE4FA7D-682B-4118-A500-6721B61BDF76/20170118-152919.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)
