### ISSUE TITLE
PHPUnit is significantly slow on my container

### ISSUE THREAD

**Issue by mrsteveheyes** [docker/for-mac#1281]
### Expected behavior

I have a web container (based on Herokus PHP container) and a Mysql Database container. When they are booted up and running i run `docker-compose run web bash` and inside there I run `phpunit` within the correct directory. It should take ~20 seconds.

### Actual behavior

The PHPUnit tests take 4 minutes to run my test. On two of my colleges machine it takes <20seconds. 

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu

```
Docker for Mac: version: 1.13.0 (0c6d765c5)
macOS: version 10.11.6 (build: 15G1217)
logs: /tmp/2D99FC38-75B5-48B1-B102-373ACAD25096/20170210-094010.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

  - A reproducible case if this is a bug, Dockerfiles FTW
Dockerfile
```
FROM heroku/cedar:14
ENV PORT 3000
ENV PHP_VERSION 5.6.15
ENV HTTPD_VERSION 2.4.17
ENV NGINX_VERSION 1.8.0

RUN mkdir -p /app/.heroku/php /app/.profile.d
WORKDIR /app/user

ENV PATH /app/.heroku/php/bin:/app/.heroku/php/sbin:$PATH

RUN curl --silent --location https://lang-php.s3.amazonaws.com/dist-cedar-14-master/apache-$HTTPD_VERSION.tar.gz | tar xz -C /app/.heroku/php
RUN curl --silent --location https://raw.githubusercontent.com/heroku/heroku-buildpack-php/5a770b914549cf2a897cbbaf379eb5adf410d464/conf/apache2/httpd.conf.default > /app/.heroku/php/etc/apache2/httpd.conf
RUN echo "\n\
Group root\n\
" >> /app/.heroku/php/etc/apache2/httpd.conf

RUN curl --silent --location https://lang-php.s3.amazonaws.com/dist-cedar-14-master/nginx-$NGINX_VERSION.tar.gz | tar xz -C /app/.heroku/php
RUN curl --silent --location https://raw.githubusercontent.com/heroku/heroku-buildpack-php/5a770b914549cf2a897cbbaf379eb5adf410d464/conf/nginx/nginx.conf.default > /app/.heroku/php/etc/nginx/nginx.conf
RUN echo "\n\
user nobody root;\n\
" >> /app/.heroku/php/etc/nginx/nginx.conf

RUN curl --silent --location https://lang-php.s3.amazonaws.com/dist-cedar-14-develop/php-7.0.12.tar.gz | tar xz -C /app/.heroku/php
RUN mkdir -p /app/.heroku/php/etc/php/conf.d
RUN curl --silent --location https://raw.githubusercontent.com/heroku/heroku-buildpack-php/5a770b914549cf2a897cbbaf379eb5adf410d464/conf/php/php.ini > /app/.heroku/php/etc/php/php.ini
RUN echo "\n\
user_ini.cache_ttl = 30 \n\
opcache.enable_cli = 1 \n\
opcache.validate_timestamps = 1 \n\
opcache.revalidate_freq = 0 \n\
opcache.fast_shutdown = 0 \n\
extension=bcmath.so \n\
extension=calendar.so \n\
extension=exif.so \n\
extension=ftp.so \n\
extension=gd.so \n\
extension=gettext.so \n\
extension=intl.so \n\
extension=mbstring.so \n\
extension=pcntl.so \n\
extension=shmop.so \n\
extension=soap.so \n\
extension=sqlite3.so \n\
extension=pdo_sqlite.so \n\
extension=xmlrpc.so \n\
extension=xsl.so\n\
" >> /app/.heroku/php/etc/php/php.ini

RUN wget https://phar.phpunit.de/phpunit.phar
RUN chmod +x phpunit.phar
RUN mv phpunit.phar /usr/local/bin/phpunit

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

RUN curl --silent --location "https://lang-php.s3.amazonaws.com/dist-cedar-14-master/composer-1.0.0alpha11.tar.gz" | tar xz -C /app/.heroku/php

COPY composer.lock /app/user/
COPY composer.json /app/user/
# run install but without scripts as we don't have the app source yet
RUN composer update --no-scripts --ignore-platform-reqs
# require the buildpack for execution
RUN composer show --installed heroku/heroku-buildpack-php || { echo 'Your composer.json must have "heroku/heroku-buildpack-php" as a "require-dev" dependency.'; exit 1; }
# run install hooks
RUN cat composer.json | python -c 'import sys,json; sys.exit("post-install-cmd" not in json.load(sys.stdin).get("scripts", {}));' && composer run-script post-install-cmd || true
RUN rm -rf /usr/local/etc/php/conf.d/opcache-recommended.ini
```

docker-compose.yml
```
version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 'wordpress'
    ports:
     - '3333:3306'

  test-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: 'test'
      MYSQL_USER: test
      MYSQL_PASSWORD: 'test'
    ports:
     - '3334:3306'

  web:
    depends_on:
      - db
    build: .
    links:
      - db
    restart: always
    env_file: .env
    volumes:
      - .:/app/user
    command: 'bash -c ''vendor/bin/heroku-php-nginx -C nginx_app.conf.dev'''
    working_dir: /app/user
    ports:
      - '3000:3000'

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
```

---

I'm not sure how to debug this or figure out what is wrong. Sorry if this is the wrong place to post this! If it needs to be taken somewhere else then happy to do so. 

Thanks for your help. Let me know if you need any more info.

**Comment by barat** [comment]
There is one simple reason ... volume mount ;)
https://github.com/docker/for-mac/issues/77

**Comment by mrsteveheyes** [comment]
Hi @barat 

Thanks for the pointer! I thought it would be something simple I'd missed. I updated my `test-db` block in my `docker-compose.yml` file to:
```
test-db:
    image: mysql:5.7
    volumes:
      - "./.data/test-db:/stopvar/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: 'test'
      MYSQL_USER: test
      MYSQL_PASSWORD: 'test'
    ports:
     - '3334:3306'
```

And now the test run in ~7 seconds!

Thanks a bunch! 😀
