### ISSUE TITLE
Docker compose slow / unusable

### ISSUE THREAD

**Issue by alexellis** [docker/for-mac#133]
### Expected behavior

docker-compose up to be timely as per Linux machine/VM
### Actual behavior

docker-compose is taking so long I'm giving up ( > 8 minutes)

```
$ time docker-compose up
Creating network "tele_default" with the default driver
Creating tele_influxdb_1
Creating tele_telegraf_1
Creating tele_grafana_1
Attaching to tele_influxdb_1, tele_telegraf_1, tele_grafana_1
...
...
real    8m8.470s
user    0m2.410s
sys 0m0.678s
```

On a second Macbook it appears to be OK.
### Information
- Diagnostic ID from "Diagnose & Feedback" in the menu.
- a reproducible case if this is a bug, Dockerfiles FTW
- page URL if this is a docs issue or the name of a man page
- host distribution and version (OSX 10.10.x, OSX 10.11.x)

4ED262E6-CCCA-4650-A271-25A3CA238825
### Steps to reproduce the behavior

```
version: "2.0"
services:
  influxdb:
    image: influxdb
    ports:
     - "8087:8086"
     - 8083/TCP
    environment:
     - INFLUXDB_USER=root
     - INFLUXDB_PASS=root
     - INFLUXDB_NAME=pistock
    volumes:
     - "./influxdb_data:/var/lib/influxdb"
  telegraf:
    image: telegraf
    depends_on:
     - influxdb

  grafana:
    image: grafana/grafana
    environment:    
     - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    links:
     - influxdb
    ports:
     - "3001:3000"
    volumes:
      - "./grafana_lib:/var/lib/grafana"
```

```
$ docker-compose up
```
