### ISSUE TITLE
Healthcheck configurations now missing for Docker for Mac v1.13.1 on version 2.1 docker-compose.yml

### ISSUE THREAD

**Issue by henrymei** [docker/for-mac#1341]
### Expected behavior
Image healthcheck configurations that worked in the last Docker for Mac version should be leveraged appropriately in 1.13.1.

### Actual behavior
`ERROR: for <service>  Service "<dependency_service>" is missing a healthcheck configuration` 

### Information
  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
``` 
Docker for Mac: version: 1.13.1 (94675c5a7)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/BF0D78AE-478B-4E27-A4F2-143759BF55A8/20170225-145353.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior
It looks like any version 2.1 `docker-compose.yml` that uses `depends_on` with `condition: service_healthy` produces this error.

**Comment by fhisamoto** [comment]
Same problem here.

**Comment by djs55** [comment]
@henrymei @fhisamoto could you share a simple `docker-compose.yml` that demonstrates the problem?

**Comment by henrymei** [comment]
Now that we're on `Docker CE 17.03.0-ce-mac2`, it has ceased to be a problem. A small example of the initial issue might be this (I slimmed down the problematic `docker-compose.yml`--happy to provide the original if it doesn't reproduce): 
```
version: '2.1'

services:
  db:
    extends:
      image: postgres:9.6
    ports:
      - "5434:5432"

  web:
    build: . 
    volumes:
      - .:/stuff
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8000"
```
