### ISSUE TITLE
"readlink /var/lib/docker/overlay2/l: invalid argument" occurs after some time 

### ISSUE THREAD

**Issue by tomgco** [docker/for-mac#1392]
### Expected behavior

`docker -D run 5d35104e2b93` actually runs my built container

### Actual behavior

```
docker -D run 5d35104e2b93
docker: Error response from daemon: ContainerInspect failed.
ERRO[0000] error getting events from daemon: net/http: request canceled
DEBU[0000] [hijack] End of stdout
```

### Information
ID: 04047E22-3B4B-4EF2-A2F8-458DE6099421

Docker for Mac: version: 17.03.0-ce-mac1 (e5a07a1a6)
macOS: version 10.12.3 (build: 16D32)
logs: /tmp/04047E22-3B4B-4EF2-A2F8-458DE6099421/20170306-155325.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

Docker logs:
```
Mar  6 16:01:30 moby root: time="2017-03-06T16:01:30.937928419Z" level=debug msg="Calling GET /containers/84cb59b8c91669702216ef5f7a61f004359b97f97da12072d2496d3dddf07851/json"
Mar  6 16:01:30 moby root: time="2017-03-06T16:01:30.938103726Z" level=error msg="Handler for GET /containers/84cb59b8c91669702216ef5f7a61f004359b97f97da12072d2496d3dddf07851/json returned error: readlink /var/lib/docker/overlay2/l: invalid argument"
```

### Steps to reproduce the behavior

```
version: "3"

services:
  test:
    tty: true
    privileged: true
    build:
      context: .
      args:
        - NPM_TOKEN
    depends_on:
      - db
      - dbseed
    volumes:
      - reports-volume:/home/node/app/reports:rw

  dbseed:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - NPM_TOKEN
    depends_on:
      - db

  db:
    image: mysql:5.6.23
    volumes:
      - data-volume:/var/lib/db

  reports:
    image: sebp/lighttpd
    ports:
      - 8080:80
    volumes:
      - reports-volume:/var/www/localhost/htdocs:ro

volumes:
  data-volume:
  reports-volume:
```

`docker-compose up --build test`

To actually fix this I have to reset the whole of docker-for-mac and re-download all my images.

Thanks
