### ISSUE TITLE
docker stack deploy no longer supports volume-labels

### ISSUE THREAD

**Issue by briantd** [docker/for-mac#1519]
### Expected behavior
The following docker command should be able to launch a stack with volumes that have volume labels
> docker stack deploy -c docker-compose.yml my_app
e.g.
```
services:
  # Docker Swarm visualizer
  # See https://docs.docker.com/engine/tutorials/dockervolumes/#volume-labels for info on the ":z"
  viz:
    image: manomarks/visualizer
    ports:
      - 8081:8080
    networks:
      - jenkins-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
    deploy:
      placement:
        constraints: [node.role==manager]
```
### Actual behavior
 1 error(s) decoding:

* invalid spec: /var/run/docker.sock:/var/run/docker.sock:z: unknown option: z
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.12.4 (build: 16E195)
logs: /tmp/3BC62945-262D-4DE5-83D6-6929A6993B92/20170406-170711.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. Put the example above into a docker-compose.yml
  2. Run docker stack deploy -c docker-compose.yml my_app
