### ISSUE TITLE
docker-compose.override.yml ignored on Version 17.05.0-ce-rc1-mac8 (16582)

### ISSUE THREAD

**Issue by ladrua** [docker/for-mac#1596]
### Expected behavior
docker-compose.override.yml settings override settings in docker-compose.yml
### Actual behavior
docker-compose.override.yml settings not overriding when using `docker-compose up -d`
### Information
Happened after upgrading to Version 17.05.0-ce-rc1-mac8 (16582) (to get the awesome new mount cached feature!)

**Comment by djs55** [comment]
Thanks for your report -- could you include a simple example to demonstrate the problem?

**Comment by ladrua** [comment]
Sure,
**docker-compose.yml** file:
```
version: '2'
services:
  example.dev:
    build: images/webserver/.
    container_name: example.dev
    volumes:
      - /srv/docker/sites:/sites
      - /srv/docker/database:/var/lib/mysql
```

**docker-compose.override.yml** file:
```
version: '2'
services:
  example.dev:
    volumes:
      - ./data/example.dev/sites:/sites:cached
      - ./data/example.dev/database:/var/lib/mysql:cached
```

`docker-compose up -d` gives error that it cant find the paths for the volumes in the docker-compose.yml file on host.
