### ISSUE TITLE
dial unix /Users/MYUSER/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused

### ISSUE THREAD

**Issue by fabriziocucci** [docker/for-mac#1713]
### Expected behavior

My web application should start with `docker-compose up`.

### Actual behavior

My web application does not start and the following gets printed:

```shell
...

Unexpected API error for compose_app_1 (HTTP code 500)
Response body:
dial unix /Users/MYUSER/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused

Unexpected API error for compose_db_1 (HTTP code 500)
Response body:
dial unix /Users/MYUSER/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused
```

### Information

* Full output of the diagnostics from "Diagnose & Feedback" in the menu:
```shell
Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.11.6 (build: 15G31)
logs: /tmp/98B30D24-3F0E-41D5-BFAF-AA96DD07505C/20170609-153747.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

* I currently don't have a reproducible project to share but I can describe my current environment by providing a simplistic version of my docker files:

  * docker-compose.yaml
```yaml
version: '3'

services:
  
  app:
    build: ./app
    ports:
    - "9080:9080"
    - "9443:9443"
    volumes:
    - /.../app/target/app-1.0.0-SNAPSHOT.war:/config/dropins/app.war
    links:
    - db
    
  db:
    build: ./db
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: db2inst1-pwd
    command: db2start    
```

  * Dockerfile for app
```docker
FROM websphere-liberty:kernel
COPY wlp-config/server.xml /config/
RUN installUtility install --acceptLicense defaultServer
COPY wlp-config/db2-10.5-fp8-jdbc-driver-4.19.66.jar /db2-jdbc-driver/db2jcc4.jar
COPY wlp-config/bootstrap.properties /config/
COPY wlp-config/jvm.options /config/
```

  * Dockerfile for db
```docker
FROM ibmcom/db2express-c
RUN su - db2inst1 -c "db2start && db2 create db DB"
```

### Steps to reproduce the behavior

  1. `docker-compose up`

### Notes

* after a random combination of `docker-compose up` and Docker restart _sometimes_ it works;
* the same issue was mentioned [here](https://github.com/docker/for-mac/issues/1176) and in many already closed issues.
