### ISSUE TITLE
Solution stack Multi-container Docker 1.12.6 (Generic) does not appear to be valid

### ISSUE THREAD

**Issue by matneves** [docker/for-mac#1768]
I'm not sure if this is Docker or Elastick Beanstalk issue related, but my problem is that I'm running the command `eb local run` to start the local enviroment alongside with docker.

### Expected behavior
The command runs seamlessly
### Actual behavior

> ERROR: Solution stack Multi-container Docker 1.12.6 (Generic) does not appear to be valid

![captura de tela 2017-06-23 as 09 31 44](https://user-images.githubusercontent.com/2514252/27482202-dcc7c9f0-57f6-11e7-945d-14b4fd441aa1.png)

**Comment by danielepolencic** [comment]
Same here:

```bash
$ eb local status
ERROR: Solution stack Multi-container Docker 17.03.1-ce (Generic) does not appear to be valid
```

```
$ docker -v
Docker version 17.06.0-ce, build 02c1d87

$ eb --version
EB CLI 3.10.1 (Python 2.7.1) 
```

**Comment by dsheets** [comment]
<https://forums.aws.amazon.com/thread.jspa?threadID=181785> indicates that this may be an EB permissions issue. Please try the suggestions in that thread and then, if you are still having issues, please post here more information about your configuration.

**Comment by dsheets** [comment]
@danielepolencic there may also be something in your 'platforms' or other configuration that demands `17.03.1-ce` when you have now upgraded to `17.06.0-ce`.

**Comment by danielepolencic** [comment]
Found the fix. Not obvious, though.

The right image for Elastic Beanstalk is: `64bit Amazon Linux 2017.03 v2.7.1 running Multi-container Docker 17.03.1-ce (Generic)`

**Comment by meurkens** [comment]
@danielepolencic Can you maybe explain a little more on how you made it work? Ran into the same problem. Thanks!

**Comment by danielepolencic** [comment]
In your `.elasticbeanstalk/config.yml` make sure that `default_platform` is `64bit Amazon Linux 2017.03 v2.7.1 running Multi-container Docker 17.03.1-ce (Generic)`. Like this:

```yaml
global:
  application_name: application_name
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2017.03 v2.7.1 running Multi-container Docker 17.03.1-ce (Generic)
  default_region: eu-west-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
```
