### ISSUE TITLE
DNS not resolving external networks.

### ISSUE THREAD

**Issue by ddaza** [docker/for-mac#1770]
I created a docker-compose cluster that looks more or less like this. 
```yml
version: '2'
networks:
  mynetwork:
    external:
      name: mynetwork
services:
  mynetwork:
    networks:
      - mynetwork
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - consul
      - memcached
    links:
      - consul
      - memcached

  memcached:
    networks:
      - mynetwork
    image: memcached:1.4-alpine
    ports:
      - "11211"

  consul:
    networks:
      - mynetwork
    image: consul:v0.6.4
    ports:
      - "8500"
    environment:
      CONSUL_CLIENT_INTERFACE: eth0```
```
Created an external network. But none of my address are resolving. 

### Expected behavior

`ping mynetwork.mynetwork` to resolve but it is not. 

I also tried to set an alias maybe so to make it work. 
```
$ docker network connect --alias mynetwork.app  mynetwork mynetwork2_mynetwork_1
Error response from daemon: service endpoint with name mynetwork2_mynetwork_1 already exists
```
### Actual behavior
ping is not resolving.  Some services `consul.mynetwork` resolve to the IP `92.242.144.2` but not my main service  I read somewhere that the IPs are added to the /etc/resolv.conf but nothing is added there.

```
#
# Mac OS X Notice
#
# This file is not used by the host name and address resolution
# or the DNS query routing mechanisms used by most processes on
# this Mac OS X system.
#
# This file is automatically generated.
#
nameserver 10.101.21.251
nameserver 216.70.53.6

```

### Information
```Docker for Mac: version: 17.03.1-ce-mac12 (d1db12684)
macOS: version 10.12.5 (build: 16F73)
logs: /tmp/B179119D-3E26-425F-BB46-7C8A2A1638FA/20170623-105432.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

### Steps to reproduce the behavior

  1. docker-compose up 
  2. ping mynetwork
