### ISSUE TITLE
Docker compose not using external named volume on Mac

### ISSUE THREAD

**Issue by sivagollapalli** [docker/for-mac#1856]
issue: https://github.com/docker/compose/issues/5012

**Comment by MikeMitterer** [comment]
I'm having the same problem.

**My DC file (lives in bitcon-folder)**
```yaml
version: '2.0'

services:
  mysql:
    image: 'mysql:5'

    environment:
      - MYSQL_ROOT_PASSWORD=secret

    volumes:
      - db:/var/lib/mysql

  php-fpm:
    image: wordpress:4.8-fpm

    environment:
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=secret

    volumes:
      - './data/html:/var/www/html'

  web:
    image: mikemitterer/bitcon-nginx

    environment:
      - PHP_FPM_SOCK=php-fpm:9000

    ports:
      - 8080:80

    volumes:
      - './data/html:/var/www/html'

volumes:
  db:
```

**docker volume inspect bitcon_db:**

```json
docker volume inspect bitcon_db
[
    {
        "CreatedAt": "2017-08-17T14:52:06Z",
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/bitcon_db/_data",
        "Name": "bitcon_db",
        "Options": {},
        "Scope": "local"
    }
]
```

**docker inspect bitcon_mysql_1:**
```json
    "Mounts": [
            {
                "Type": "volume",
                "Name": "211b3f93672befdc9f70a99d2c10e72ad15ba803ff8987e59f11137da3c2d2d7",
                "Source": "/var/lib/docker/volumes/211b3f93672befdc9f70a99d2c10e72ad15ba803ff8987e59f11137da3c2d2d7/_data",
                "Destination": "/var/lib/mysql",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            }
        ],
```
**docker run --rm -ti --name tmp-backup --volume 211b3f93672befdc9f70a99d2c10e72ad15ba803ff8987e59f11137da3c2d2d7:/volume ubuntu bash -c 'ls -la /volume'**
```bash
total 176200
drwxr-xr-x  6  999  999     4096 Sep  8 13:03 .
drwxr-xr-x 34 root root     4096 Sep  8 13:04 ..
-rw-r-----  1  999  999       56 Aug 17 14:38 auto.cnf
-rw-------  1  999  999     1679 Aug 17 14:38 ca-key.pem
-rw-r--r--  1  999  999     1074 Aug 17 14:38 ca.pem
-rw-r--r--  1  999  999     1078 Aug 17 14:38 client-cert.pem
-rw-------  1  999  999     1675 Aug 17 14:38 client-key.pem
-rw-r-----  1  999  999      634 Sep  8 13:03 ib_buffer_pool
-rw-r-----  1  999  999 50331648 Sep  8 13:03 ib_logfile0
-rw-r-----  1  999  999 50331648 Aug 17 14:38 ib_logfile1
-rw-r-----  1  999  999 79691776 Sep  8 13:03 ibdata1
drwxr-x---  2  999  999     4096 Aug 17 14:38 mysql
drwxr-x---  2  999  999     4096 Aug 17 14:38 performance_schema
-rw-------  1  999  999     1675 Aug 17 14:38 private_key.pem
-rw-r--r--  1  999  999      451 Aug 17 14:38 public_key.pem
-rw-r--r--  1  999  999     1078 Aug 17 14:38 server-cert.pem
-rw-------  1  999  999     1675 Aug 17 14:38 server-key.pem
drwxr-x---  2  999  999    12288 Aug 17 14:38 sys
drwxr-x---  2  999  999     4096 Aug 17 14:56 wordpress
```
**docker run --rm -ti --name tmp-backup --volume bitcon_db:/volume ubuntu bash -c 'ls -la /volume'**
```bash
total 8
drwxr-xr-x  2 root root 4096 Aug 17 14:52 .
drwxr-xr-x 34 root root 4096 Sep  8 13:05 ..
```
