### ISSUE TITLE
200% CPU

### ISSUE THREAD

**Issue by markfoodyburton** [docker/for-mac#1924]
### Actual behavior
I see about 200% CPU being used by the hyperkit when I have a single idle container running e.g. bash.  On the previous beta I didn't see this issue. I tried reseting etc, with no success.

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Shows everything is OK, but takes a VERY long time to run....
Docker for Mac: version: 17.07.0-ce-rc1-mac21 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/64A86697-16DA-45C0-8F6B-460C949607C5/20170801-151625.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW

Simply use e.g. jessie as an image.

### Steps to reproduce the behavior

Start docker, start a container, watch your computer get hot !

**Comment by luishdez** [comment]
Same problem hyperkit goes up to 300% and overheat my CPU insanely

**Comment by esetnik** [comment]
I have the same problem. I can also confirm diagnose taking 5-10 min. During the diagnose I see `log` and `grep` processes each using 100% cpu for the duration. I have also reproduced this on a "factory reset" `docker/for-mac` run. 

```
Docker for Mac: version: 17.06.2-ce-mac27 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/F72190F8-BF99-4F1C-B7BF-C70976E54F58/20170920-112728.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

It anecdotally appears to be related to the inclusion of named volumes in a compose file. I'm not sure if this is actually related but I've been unable to reproduce this problem when I do not include these volumes.

```
version: '3'

volumes:
  frontend_node_modules:
  warehouse_node_modules:
  server_node_modules:
  jobs_node_modules:
  worker_node_modules:

services:
  frontend:
    volumes:
      - ./web-frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
  warehouse:
    volumes:
      - ./warehouse:/usr/src/app
      - warehouse_node_modules:/usr/src/app/node_modules  
  api:
    ports:
      - 9229:9229
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
  worker:
    ports:
      - 9230:9229
    volumes:
      - ./server:/app
      - worker_node_modules:/app/node_modules  
  jobs:
    ports: 
      - 9231:9229  
    volumes:
      - ./server:/app 
      - jobs_node_modules:/app/node_modules
```
