### ISSUE TITLE
[2278F2F4-C0B0-4B16-8582-9074E1B164A1] Container port didn't mapping to Mac host.

### ISSUE THREAD

**Issue by zx1986** [docker/for-mac#1988]
Diagnostic ID: 2278F2F4-C0B0-4B16-8582-9074E1B164A1

### Expected behavior

mysql connect to docker container with 3306 port mapping.
`netstat -lnt | grep 3306` should get something.

### Actual behavior

```
mysql -v -u root -p -h 127.0.0.1
Enter password:
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (60)
```

```
netstat -lnt | grep 3306
# got nothing.
```

```
docker ps -a
a2b580ecc76c        mariadb             "docker-entrypoint..."      0.0.0.0:3306->3306/tcp   database
```

### Information

Docker for Mac: version: 17.06.1-ce-mac24 (4cdec4294a50b2233146b09469b49937dabdebdd)
macOS: version 10.13 (build: 17A352a)
logs: /tmp/2278F2F4-C0B0-4B16-8582-9074E1B164A1/20170823-235544.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

1. vim docker-compose.yml
```
database:
  image: mariadb
  container_name: database
  restart: always
  ports:
    - "3306:3306"
  volumes:
    - ./data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 12345678
```
  2. docker-compose up
