### ISSUE TITLE
Can't connect service ip address in swarm from host.

### ISSUE THREAD

**Issue by dream83619** [docker/for-mac#2125]
### Expected behavior
Can connect service ip address in swarm from host.

### Actual behavior
Can't connect service ip address in swarm from host.

### Information
I create a Redis master/slaves/sentinels stack using docker swarm. The ip addresses resolved by sentinels are 10.0.0.*, which are ip addresses in docker, and my application can't connect these addresses directly.

### Steps to reproduce the behavior

1. docker-compose.yml
```
  redis-master:
    image: redis:3
    ports: 
      - 6380:6379
  redis-slave:
    image: redis:3
    ports:
      - 6381:6379
    command: redis-server --slaveof redis-master 6379
    deploy:
      replicas: 2
  redis-sentinel:
    image: mengli/redis-sentinel
    ports:
      - 26379:26379
    command: redis-server --sentinel announce-ip 1.2.3.4
    deploy:
      replicas: 3
    environment:
      - MASTER_HOST=redis-mater
      - SENTINEL_PORT=26379
      - SENTINEL_QUORUM=2
```
2. `docker stack deploy -c docker-compose.yml redis-example`
3. Get ip addresses 10.0.0.*
4. Can't connect these ip addresses directly from host.
