### ISSUE TITLE
Starting multiple services(with Compose) ends in a compose.parallel.feed_queue loop

### ISSUE THREAD

**Issue by maxehmookau** [docker/for-mac#2153]
I'm trying to run docker-compose up on a project I've used hundreds of times before. Except now starting the containers takes up to half an hour just to get running and then the web server inside the containers runs very very slowly when it does work.

Running docker-compose --verbose up gives me a loop of this thousands of times:

compose.parallel.feed_queue: Pending: set([])

However, when I specify a single service inside the config file to start, this works as fast as normal. The issue only occurs when attempting to run multiple containers.

Using docker on its own in the CLI works as before.

Diagnostic ID: 66FA4AD4-2FBC-486C-8FA7-200F103D9222

I'm running Docker 17.09.0-ce-mac35, and docker-compose version 1.16.1, build 6d1ac21 and MacOS High Sierra.

I've attempted to reinstall, rebuild and using docker edge to no avail :(

I initially opened this ticket in the docker-compose repo but was told to repost here.
https://github.com/docker/compose/issues/5257

**Comment by padusumilli** [comment]
Same thing here, tried reinstall stable/edge version but same sluggish performance to the point where it's barely usable.

**Comment by maxehmookau** [comment]
I should also add, when starting my development environment using docker-compose if I start each service separately
```
docker-compose start web
docker-compose start worker
docker-compose start db
etc...
```

Everything works fine and very quickly.

**Comment by maxehmookau** [comment]
I've also just reimaged my entire computer and wiped everything and just installed nothing else except Docker. The issue is persisting across all of my projects.

I'm totally lost where to go to solve this, please help!

**Comment by maxehmookau** [comment]
After some more narrowing down I believe the issue is to do with native docker on mac specifically.
I've moved back to using docker toolbox/virtualbox/docker-sync for development and it's really fast.

**Comment by padusumilli** [comment]
> I should also add, when starting my development environment using docker-compose if I start each service separately
> 
> docker-compose start web
> docker-compose start worker
> docker-compose start db
> etc...
> Everything works fine and very quickly. (Something to try @padusumilli while a solution is figured out!)

@maxehmookau

**Comment by maxehmookau** [comment]
Hey @jasonbivins has there been any progress on this? What's the usual timeframe of something like this? I think I've managed to rule out anything on my system that might be causing the issue.

**Comment by jasonbivins** [comment]
HI @maxehmookau would you be able to share your dockerfile?

**Comment by maxehmookau** [comment]
Sure, we're not actually using a Dockerfile. All of the images in our projects use library images. It's happening with all projects that have multiple services on compose. This only affects High Sierra users too.

```
version: '2'
services:
  redis:
    image: redis
  db:
    image: postgres
    volumes:
      - "./.data/db:/var/lib/postgresql"
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    environment:
      RAILS_ENV: development
      PORT: 3000
    volumes:
      - .:/opt/substrakt/project
      - ~/.ssh:/root/.ssh
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  sidekiq:
    build: .
    volumes:
      - .:/opt/substrakt/project
    links:
      - db
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml
  clock:
    build: .
    volumes:
      - .:/opt/substrakt/myhealthcare
    links:
      - db
      - redis
    command: bundle exec clockwork clock.rb
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
```

**Comment by maxehmookau** [comment]
Sorry, I was wrong, we do use a Dockerfile (clearly!). Too early in the morning!

```
FROM ruby:2.3.1
MAINTAINER Max Woolf <max@substrakt.com>

WORKDIR /opt/substrakt/project
COPY Gemfile /opt/substrakt/project
COPY Gemfile.lock /opt/substrakt/project
RUN bundle install -j4
COPY . /opt/substrakt/project
```

**Comment by maxehmookau** [comment]
Has there been any update on this? I've seen a few people on Twitter and other forums having similar issues.

I've downgraded my iMac to Sierra for now and will keep it there for the forseeable...

**Comment by MatthewMi11er** [comment]
I am also experiencing this issue:

Using `docker-compose up` on this `docker-compose.yml` takes about 1 **second**:
```
version: '3.1'
services:
  n1:
    image: nginx:mainline-alpine
```

Using `docker-compose up` on this `docker-compose.yml` takes about **1 minute**:
```
version: '3.1'
services:
  n1:
    image: nginx:mainline-alpine
  n2:
    image: nginx:mainline-alpine
```

Using `docker-compose up` on this `docker-compose.yml` takes about **3 minutes**:
```
version: '3.1'
services:
  n1:
    image: nginx:mainline-alpine
  n2:
    image: nginx:mainline-alpine
  n3:
    image: nginx:mainline-alpine
```

`Docker-compose down` also takes an extended time when there are multiple services.
