### ISSUE TITLE
`dns_search` not supported despite code implementing such support

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [docker/for-mac#2189]
### Expected behavior

I have this `docker-compose.yml`

```yaml
version: '3.4'

services:
  foo:
    image: 'debian:9'
    command: ["/usr/bin/sleep", "100000"]
    deploy:
      dns_search: mydomain.com
      replicas: 2
  bar:
    image: 'debian:9'
    command: ["bash", "-c", "read"]
    deploy:
      replicas: 1
```

When I call `docker -H swarm.mydomain.com stack deploy --compose-file docker-compose.yml mk-test` it should deploy 3 instances.

### Actual behavior

The output is `dns_search Additional property dns_search is not allowed`

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
```
Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.13 (build: 17A405)
logs: /tmp/970E2686-B327-4416-B41D-D17B9B6D527C/20171031-113137.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```
  - Diagnostic ID: `970E2686-B327-4416-B41D-D17B9B6D527C`
  - The server is a GNU/Linux host running 17.06.2-ce
  - According to this commit: https://github.com/docker/docker-ce/commit/2ebde31440f3736b8a39ff0281f065c6ab29e3c7 it should be possible starting 17.06.0
  - The docs online seem to be outdated. They say `dns` and `dns_search` are not supported but it seems the pull request just did not update the docs.

### Steps to reproduce the behavior

  1. Write the `docker-compose.yml`
  2. Call the `docker stack deploy` command
