### ISSUE TITLE
docker daemon - Not able to run in Mac

### ISSUE THREAD

**Issue by SandeepMajety** [docker/for-mac#2267]
### Expected behavior
docker daemon command should be running
### Actual behavior
`docker daemon` is not supported on Darwin. Please run `dockerd` directly
### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
Docker for Mac: version: 17.09.0-ce-mac35 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G1036)
logs: /tmp/FFF769C8-5F16-4DFC-9389-FFC350D1F38F/20171125-102651.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior

  1. ...type docker daemon and you will get the error
`docker daemon` is not supported on Darwin. Please run `dockerd` directly
  2. ...type dockerd
dockerd
-bash: dockerd: command not found

**Comment by thaJeztah** [comment]
On Docker for Mac, the daemon runs in a lightweight Linux VM; the daemon (`dockerd`) itself can only run on Linux or Windows (for Windows containers).

Closing because this is not a bug, but feel free to discuss

**Comment by d3minem** [comment]
@thaJeztah - when running the command `docker-compose up`. I'm getting the below error:

```
Pulling auth-service (sqshq/project-name-auth-service:)...
ERROR: Get https://registry-1.docker.io/v2/: Service Unavailable
```
As you've suggested in one of another thread [here](https://github.com/moby/moby/issues/32270#issuecomment-290829987) that set the DNS port 8.8.8.8 for all containers. I'm trying `sudo dockerd --dns 8.8.8.8` according to the documentation [Daemon-dns-options #Doc] (https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-dns-options). Now the problem `dockerd` is not supported on mac, please suggest alternative option to fix the actual issue.

**Note:** Downloaded the Docker from website and installed it. Not brew!

**Docker Compose Version Info:**

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Docker Version Info:**

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by thaJeztah** [comment]
does the image in your compose file have a tag specified? Looking at this output;

```
Pulling auth-service (sqshq/project-name-auth-service:)...
```

it looks as if it's trying to pull `sqshq/project-name-auth-service:` (without a tag after `:`) ?

Can you pull other images? e.g. does `docker pull hello-world` work? If so, it's not a dns issue

**Comment by d3minem** [comment]
Thanks @thaJeztah for your feedback. I have pulled the hello-world image and tried with before/after docker authentication.

**Before Login:** `deminem$ docker pull hello-world`

```
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout
```
**After Login:** `deminem$ docker pull hello-world`

```
Using default tag: latest
latest: Pulling from library/hello-world
1b930d010525: Pull complete 
Digest: sha256:f9dfddf63636d84ef479d645ab5885156ae030f611a56f3a7ac7f2fdd86d7e4e
Status: Downloaded newer image for hello-world:latest
docker.io/library/hello-world:latest
```
All the downloaded images: `deminem$ docker images`

```
REPOSITORY                                  TAG                 IMAGE ID            CREATED             SIZE
rabbitmq                                    3-management        38e57f281891        2 days ago          184MB
sqshq/piggymetrics-mongodb                  latest              9c0e839ffb2e        2 months ago        442MB
sqshq/piggymetrics-turbine-stream-service   latest              652082cbaea2        2 months ago        356MB
sqshq/piggymetrics-monitoring               latest              7b2784dffdf5        2 months ago        343MB
sqshq/piggymetrics-notification-service     latest              ec04913a68f8        2 months ago        367MB
sqshq/piggymetrics-statistics-service       latest              0ad3e2105f7b        2 months ago        367MB
sqshq/piggymetrics-account-service          latest              cf140b0ab65e        2 months ago        367MB
sqshq/piggymetrics-auth-service             latest              5143fb2e4f9b        2 months ago        361MB
sqshq/piggymetrics-gateway                  latest              a79bf3816ce0        2 months ago        356MB
sqshq/piggymetrics-registry                 latest              74460780dd88        2 months ago        356MB
sqshq/piggymetrics-config                   latest              482790d91398        2 months ago        340MB
hello-world                                 latest              fce289e99eb9        15 months ago       1.84kB
```

The `hello-world` example is running perfectly fine without any issues: `deminem$ docker run hello-world`

```
Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```
As you can see other images are also downloaded with specified tags, I don't see it's the tag issue. I think it's more likely a network issue, where lousy internet connection drop the network packets and `docker-compose up` gives above error message. 

Please see the `docker-compose.yml` configuration for further clarification.

```
version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: sqshq/piggymetrics-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: sqshq/piggymetrics-registry
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: sqshq/piggymetrics-gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: sqshq/piggymetrics-auth-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: sqshq/piggymetrics-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: sqshq/piggymetrics-account-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: sqshq/piggymetrics-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
    image: sqshq/piggymetrics-statistics-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: sqshq/piggymetrics-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
    image: sqshq/piggymetrics-notification-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-mongodb:
    image: sqshq/piggymetrics-mongodb
    restart: always
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  monitoring:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: sqshq/piggymetrics-monitoring
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 9000:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  turbine-stream-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: sqshq/piggymetrics-turbine-stream-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
    - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"
```
