### ISSUE TITLE
Unable to make xdebug connection to host machine on port 9000 with 17.12.0-ce-mac45

### ISSUE THREAD

**Issue by jbrinley** [docker/for-mac#2373]
### Expected behavior

Containers can connect to port 9000 on the host machine.

### Actual behavior

The connection times out.

### Information

I have xdebug configured (via php.ini) to connect to 192.168.65.1:9000. This works great on Version 17.12.0-ce-rc4-mac44 (21438).

After updating to the latest build (Version 17.12.0-ce-mac45), it can no longer connect. The xdebug log states that the connection timed out.

I reverted back to version mac44, and it's working again, so it seems pretty certain that something in the mac45 version broke it.

I can't tell if it's related to issue #2320 mentioned in the release notes.

**Comment by djs55** [comment]
Thanks for your report. Rather than use the IP address `192.168.65.1`, could you use the DNS name `docker.for.mac.localhost`?

In the most recent builds the default IP addresses changed, but the DNS name should always point to the correct place.

**Comment by jbrinley** [comment]
Is there a new consistent IP address, or will it be changing regularly?

For additional context, our team runs a dnsmasq container that maps `host.tribe`to the host machine's IP address, which it pulls from an `.env` file.

```
  dns-internal:
    image: andyshinn/dnsmasq:latest
    container_name: tribe-dns-internal
    command:  --log-facility=/proc/self/fd/2 --no-resolv --server=8.8.8.8 --address=/mysql.tribe/172.20.10.200 --address=/smtp.tribe/172.20.10.90 --address=/host.tribe/${HOSTIP:-172.20.10.1}
    cap_add:
      - NET_ADMIN
    ports:
      - "53/udp"
      - "53/tcp"
    networks:
      proxy:
        ipv4_address: 172.20.10.250
```

Depending on environment (windows, osx, linux), team members can set that IP in the single `.env` file and the use that container for DNS resolution for all other containers. E.g.:

```
    php-fpm:
      build:
      image: tribe-phpfpm:7.0-rev2
      working_dir: /application
      networks:
        - proxy
      dns: 172.20.10.250
```

This allows us to have consistent php.ini files we can share for our project containers that will include:

```
xdebug.remote_host=host.tribe
xdebug.remote_port=9000
```
