### ISSUE TITLE
Unable to get inotify events inside container using kubernetes

### ISSUE THREAD

**Issue by christopherL91** [docker/for-mac#2375]
### Expected behavior

Should be able to get inotify events inside a container in kubernetes mounted with a host directory.

### Actual behavior

Not able to get inotify events if there isn't another container outside kubernetes that mounts the same directory directly using docker run -v ...

### Information

  - Full output of the diagnostics from "Diagnose & Feedback" in the menu
  - A reproducible case if this is a bug, Dockerfiles FTW
  - Page URL if this is a docs issue or the name of a man page

Docker for Mac: version: 17.12.0-ce-mac45 (a61e84b8bca06b1ae6ce058cdd7beab1520ad622)
macOS: version 10.13.2 (build: 17C88)
logs: /tmp/E73BC492-DDF5-4CBB-B43D-7F7874CF3802/20180109-011402.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

### Steps to reproduce the behavior

  1. run `docker run -it -v "some directory" alpine` and install inotify `apk --no-cache add inotify-tools` and then run `inotifywait -r -m --format "%e %f" 'some directory'` in order to watch for inotify events
  2. 
``` yaml
apiVersion: v1
kind: Service
metadata:
  name: alpine
spec:
  selector:
    app: alpine
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alpine
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        hostPath:
          path: data
```
create the following service and deployment using `kubectl create -f ./alpine.yaml` and exec into the container. There you run the same command as with the other container "apk --no-cache ..."

Write and modify the directory that is now mounted inside the two containers, and see that both containers receive inotify events.

Now remove the container that is running outside kubernetes and watch what happens inside the container that is running inside kubernetes. The container no longer receives any inotify events

**Comment by thaJeztah** [comment]
Possible duplicate of https://github.com/moby/moby/issues/35941

/cc @djs55

**Comment by majelbstoat** [comment]
Came here to report exactly the same thing. Thanks @christopherL91 for the info that events are passed if it's mounted in two places. That workaround aside, the inability for `webpack --watch` to receive notifications pretty much makes this a non-starter for fast iterative development in the local kubernetes cluster. I hope a fix for this can be made in an upcoming edge release.

**Comment by djs55** [comment]
Thanks for the report. I think what's happening is:
- kubernetes creates a container with a bind mount
- a controller sees the event and tells `com.docker.osxfs` to start sending events
- a periodic timer (with a 5 minute interval) fires
- a GC collects unused event registrations, where "unused" means "does not correspond to a running docker container". Since the kubernetes container names are not the same as the docker container names, the garbage collector deletes the kubernetes event registration. The reason `docker run -v ...` makes it work is that the GC sees the event registration is still in use and doesn't delete it.

I've got a prototype fix for this if you'd like to try it: https://download-stage.docker.com/mac/bysha1/98d31563898720b294dd40349228266a0dc2f969/Docker.dmg

Note that
- the build is a development build, only suitable for testing. It's not suitable for production.
- if it offers an auto-update, don't accept as this may upgrade to a build without the fix

If you get a chance to try it, let me know what happens!

**Comment by davidthornton** [comment]
I’m at Korean bbq rn but when I’m not drank I will test this.

**Comment by djs55** [comment]
Hi @fdanielsen -- that does sound like a very similar scenario. I'll investigate locally, but meanwhile if you could try starting a stack and then running:
```
/Applications/Docker.app/Contents/MacOS/com.docker.osxfs  state
```
It should display the active event registrations. Hopefully there's an entry for the host path mentioned in the compose file. When the events stop I suspect the entry will have been deleted.

**Comment by djs55** [comment]
@fdanielsen I created a very simple image:
```
$ cat build/Dockerfile
FROM alpine

RUN apk --no-cache add inotify-tools

CMD ["/bin/sh", "-c", "sleep 3000"]
```
and a very simple `docker-compose.yml`:
```
version: "3"
services:

  test:
    build: build
    image: test
    volumes:
      - /path:/foo
```
If I launch this with `docker-compose up` it seems to work as expected: `com.docker.osxfs state` shows the event registration. If I launch this with `docker stack deploy test -c docker-compose.yml` then the event registration is missing, which means no events at all :(
