### ISSUE TITLE
Cannot send file using PUT

### ISSUE THREAD

**Issue by nicodeur** [docker/for-mac#2586]
Hello

### Expected behavior
I would like send a file using `curl -T <file> url`

### Actual behavior
When I `curl -T <file> url`, curl waiting response, and return `read time out` after some time.

`curl url` works fine!

I reproduce it with some different machines, with different container. I'm using a proxy, but it seems seetings fine because on other protocol (GET,POST etc.) works fine.

### Information
* I'm using docker for mac `Docker version 17.12.0-ce, build c97c6d6`
* I configure proxy by preferences windows on docker for mac.
* When I'm on my hosted shell, I configured `http_proxy` & `https_proxy` env, `curl -T <file> url` works fine.
* When I using a network without proxy, it's work fine when I `curl -T <file> url` into the container

### Steps to reproduce the behavior

1. docker-compose up -d on   
```
jenkins:
  image: jenkins
  ports:
    - 8085:8080
  restart: always
  volumes:
    - ./jenkinshome:/var/jenkins_home
```

2. ` docker exec -it <container_name> bash`

3. curl -T <file> www.google.fr
4. curl waiting ... If curl respond something, that it's works.

Tanks for advance,

Nicolas
