### ISSUE TITLE
Pods with `hostNetwork` do not have access to cluster DNS

### ISSUE THREAD

**Issue by thrawn01** [docker/for-mac#2646]
### Expected behavior
Given a kubernetes service called 'etcd' exists, when starting a pod that includes `hostNetwork: true` service cluster names via DNS should resolve. 
### Actual behavior
ping: bad address 'etcd'
### Steps to reproduce the behavior
1. Setup a service in the cluster (I used etcd in this example)
2. Create a DaemonSet and attempt to resolve the dns name of the service with `hostNetwork: true` 
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dns-test
  labels:
    app: dns-test
spec:
  template:
    metadata:
      labels:
        app: dns-test
    spec: 
      hostNetwork: true # <-- The POD has access to the host network
      containers:
      - name: dns-test
        image: busybox
        imagePullPolicy: IfNotPresent
        args:
          - ping
          - etcd
```
3. Result
```
ping: bad address 'etcd'
```

### Workaround
1. Run `docker run -it --privileged --pid=host justincormack/nsenter1` to enter the docker host
2. Edit `/etc/resolv.conf`
3. Add the service ip address of CoreDNS running in kubernetes
```
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```
4. Re-create the daemon set
```
PING etcd (10.1.0.186): 56 data bytes
64 bytes from 10.1.0.186: seq=0 ttl=64 time=0.082 ms
64 bytes from 10.1.0.186: seq=1 ttl=64 time=0.365 ms
64 bytes from 10.1.0.186: seq=2 ttl=64 time=0.098 ms
```
