### ISSUE TITLE
Permissions are not specific in tmpfs subdirectory of volume directory

### ISSUE THREAD

**Issue by Kwadz** [docker/for-mac#2742]
Let's assume this docker-compose.yml:

```
version: '3'

services:
  website:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - .:/var/www/html/
    tmpfs:
      - /var/www/html/app/cache/
```

**Expected behaviour:** the permissions of `/var/www/html/app/cache/` should be 1777 (the default for _tmpfs-mode_).

**Actual behavior:**  the permissions of `/var/www/html/app/cache/` is overridden by the permissions of `/var/www/html/`
