### ISSUE TITLE
secrets not mounting

### ISSUE THREAD

**Issue by ninjail** [docker/for-mac#2774]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [* ] I have tried with the latest version of my channel (Stable or Edge)
  - [ *] I have submitted Diagnostics
  - [ *] I have included the Diagnostics ID in this Issue

### Expected behavior
secrets in /run/secrets

### Actual behavior
no secrets in /run/secrets

### Information

```
Docker for Mac: version: 18.03.0-ce-mac59 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/C1115A49-5041-4A15-857A-06A32D0A1E99/20180405-134457.tar.gz


```

```
version: '3.4'

services:

  service:
    tmpfs:
      - /run
    container_name: container_name

    build:
      context: ./context
      dockerfile: deploy/Dockerfile

    secrets:
      - source: sshkey
        target: sshkey
      - my_secret

secrets:
  my_secret:
    file: ./secret

  sshkey:
    file: ./

```

```ARG python_version=3.6

# jessie is required for couchbase lib
FROM python:${python_version}-jessie as builder

RUN mkdir ~/.ssh && ln -s /run/secrets/sshkey ~/.ssh/id_rsa
run ls /var/run/
run ls /mnt
run ls /run
run ls /run/secrets
run ls /opt
run ls /var/opt

run cat /root/.ssh/id_rsa
RUN ssh-keyscan github.com > /root/.ssh/known_hosts

# 4 CouchBase
RUN apt-get update && apt-get install -y lsb-release
RUN wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-4-amd64.deb
RUN dpkg -i couchbase-release-1.0-4-amd64.deb
RUN apt-get update && apt-get install -y libcouchbase-dev libcouchbase2-bin

ENV PYTHONUNBUFFERED 1
ADD ./requirements.txt /opt/app/requirements.txt
RUN pip install -r /opt/app/requirements.txt



FROM python:${python_version}-slim-jessie
ARG python_version=3.6
RUN echo 'alias ll="ls -la"' >> ~/.bashrc

# 4 CouchBase
COPY --from=builder /usr/include/libcouchbase /usr/include/libcouchbase
COPY --from=builder /usr/lib/x86_64-linux-gnu/libcouchbase* /usr/lib/x86_64-linux-gnu/

COPY --from=builder /usr/local/lib/python${python_version}/site-packages /usr/local/lib/python${python_version}/site-packages
COPY --from=builder /usr/local/bin/gunicorn /usr/local/bin/gunicorn
ADD ./src /opt/app
# ADD ./requirements.txt /opt/app/
ADD ./entrypoint.sh /opt/app/

WORKDIR /opt/app
```

```Step 1/28 : ARG python_version=3.6
Step 2/28 : FROM python:${python_version}-jessie as builder
 ---> efb6baa1169f
Step 3/28 : RUN mkdir ~/.ssh && ln -s /run/secrets/sshkey ~/.ssh/id_rsa
 ---> Running in 23e9b7f86b94
Removing intermediate container 23e9b7f86b94
 ---> b0a377700e5b
Step 4/28 : run ls /var/run/
 ---> Running in 5e02072b1134
lock
utmp
Removing intermediate container 5e02072b1134
 ---> c9092a1897f1
Step 5/28 : run ls /mnt
 ---> Running in 9a1c0e24d51a
Removing intermediate container 9a1c0e24d51a
 ---> 16b4b587d7de
Step 6/28 : run ls /run
 ---> Running in 889edc2242c9
lock
utmp
Removing intermediate container 889edc2242c9
 ---> 4fdb45200059
Step 7/28 : run ls /run/secrets
 ---> Running in 6fd1be3d1f4b
```
### Steps to reproduce the behavior

  1. ...
  2. ...
