### ISSUE TITLE
Docker for Mac with Kubernetes in Edge channel breaks Kubernetes 1.10 kubeconfig

### ISSUE THREAD

**Issue by leosunmo** [docker/for-mac#2829]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue

### Expected behavior
Docker for Mac should read the Kubernetes config but if it can't unmarshal a section, it shouldn't delete that section.

### Actual behavior
Docker for Mac removes the sections related to the external exec auth introduced in Kubernetes 1.10. 
If you specify anything under `users.user` it will simply delete it and you'll be left with an empty block:
```
users:
- name: ...
   user: {}
```
The external credentials was introduced in Kubernetes 1.10. Info on the change below.
PR: https://github.com/kubernetes/kubernetes/pull/59495
Docs: https://kubernetes.io/docs/admin/authentication/#client-go-credential-plugins

### Information
This is currently stopping anyone using external authentication from using Docker for Mac as their local Kubernetes dev environment. This will be more and more common as people start to use projects such as https://github.com/heptio/authenticator.
It's going to be especially common among AWS EKS users.

Not sure a diagnostic will show you much, but here it is!

ID: `A1EA1C42-EA22-4BDB-81E2-779A5FF07779`
```
Docker for Mac: version: 18.04.0-ce-mac62 (7e2bb492d35dc35ec0037d8024b7e7be57fc72a9)
macOS: version 10.13.4 (build: 17E199)
logs: /tmp/A1EA1C42-EA22-4BDB-81E2-779A5FF07779/20180420-095743.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior

  1. Fresh install of latest Docker for Mac version 18.04.0-ce-mac62 (23965).
  2. Enable Kubernetes in Preferences
  3. Before installation:
```
cat ~/.kube/config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://api.my-cluster.example.com
  name: my-cluster.example.com
contexts:
- context:
    cluster: my-cluster.example.com
    namespace: kube-system
    user: ext_auth_user
  name: ext_auth_user_ctx
current-context: ext_auth_user_ctx
kind: Config
preferences: {}
users:
- name: ext_auth_user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - heptio-authenticator-aws
      - token
      - --cluster-id
      - my-cluster.example.com
      command: aws-vault
      env: null
```
4. After Kubernetes installation completes
```
cat ~/.kube/config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://api.my-cluster.example.com
  name: my-cluster.example.com
contexts:
- context:
    cluster: my-cluster.example.com
    namespace: kube-system
    user: ext_auth_user
  name: ext_auth_user_ctx
current-context: ext_auth_user_ctx
kind: Config
preferences: {}
users:
- name: ext_auth_user
  user: {}
```
