### ISSUE TITLE
No Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by dockerworxinc** [docker/for-mac#2835]
# Existing Infrastructure:

- Docker for Mac 18.04 CE
- Kubernetes Enabled

## Aim: 
Trying to run a simple NginX application on GKE Cluster

#### Listing the GKE Cluster:

```
kubectl get nodes
NAME                                      STATUS    ROLES     AGE       VERSION
gke-k8s-lab1-default-pool-b2aaa29b-2gzh   Ready     <none>    19h       v1.8.8-gke.0
gke-k8s-lab1-default-pool-b2aaa29b-qpc7   Ready     <none>    19h       v1.8.8-gke.0
gke-k8s-lab1-default-pool-b2aaa29b-w904   Ready     <none>    19h       v1.8.8-gke.0

```

File: docker-stack.yml

```
version: '3.3'
services:
  web1:
    image: nginx:alpine
    ports:
      - 8082:80
  db1:
    image: nginx:alpine

networks:
  collabnix:
```

### Expected behavior

```
docker stack deploy -c docker-compose.yml myapp4
```

The command should run successfully on GKE cluster.

### Actual behavior

```
No Auth Provider found for name "gcp"
```

### Information

```
Docker for Mac: version...
18.04.0 CE Edition
```
