### ISSUE TITLE
Error: failed to prepare subPath for volumeMount on Docker for Mac (18.05.0-ce-rc1) only against /var/run

### ISSUE THREAD

**Issue by ccassagnol** [docker/for-mac#2865]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Expected behavior
Should just create the service as expected. Also doesn't seem to be related to #[61076](https://github.com/kubernetes/kubernetes/issues/61076) as it is version 1.9.6 of Kubernetes with the latest edge docker installed...

### Actual behavior

cat docker-compose.yml | docker stack deploy --compose-file - reverse-proxy
Ignoring unsupported options: restart

Stack reverse-proxy was created
Waiting for the stack to be stable and running.. 

hangs at this point with the below

```kubernetes
kubectl describe pod nginx-proxy-86f569b84f-tfsjt
Name:           nginx-proxy-86f569b84f-tfsjt
Namespace:      default
Node:           docker-for-desktop/192.168.65.3
Start Time:     Tue, 01 May 2018 19:09:10 -0700
Labels:         com.docker.service.id=reverse-proxy-nginx-proxy
                com.docker.service.name=nginx-proxy
                com.docker.stack.namespace=reverse-proxy
                pod-template-hash=4291256409
Annotations:    com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
Status:         Pending
IP:             10.1.0.5
Controlled By:  ReplicaSet/nginx-proxy-86f569b84f
Containers:
  nginx-proxy:
    Container ID:
    Image:          jwilder/nginx-proxy:alpine
    Image ID:
    Ports:          80/TCP, 443/TCP
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/nginx/certs from mount-1 (ro)
      /etc/nginx/vhost.d from mount-2 (rw)
      /tmp/docker.sock from mount-0 (ro)
      /usr/share/nginx/html from mount-3 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2pb8v (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  mount-0:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run
    HostPathType:
  mount-1:
    Type:          HostPath (bare host directory volume)
    Path:          /Volumes/Data/dockerstuff/volumes/proxy
    HostPathType:
  mount-2:
    Type:          HostPath (bare host directory volume)
    Path:          /Volumes/Data/dockerstuff/volumes/proxy
    HostPathType:
  mount-3:
    Type:          HostPath (bare host directory volume)
    Path:          /Volumes/Data/dockerstuff/volumes/proxy
    HostPathType:
  default-token-2pb8v:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2pb8v
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age               From                         Message
  ----     ------                 ----              ----                         -------
  Normal   Scheduled              26s               default-scheduler            Successfully assigned nginx-proxy-86f569b84f-tfsjt to docker-for-desktop
  Normal   SuccessfulMountVolume  26s               kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "mount-1"
  Normal   SuccessfulMountVolume  26s               kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "mount-2"
  Normal   SuccessfulMountVolume  26s               kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "mount-3"
  Normal   SuccessfulMountVolume  26s               kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "mount-0"
  Normal   SuccessfulMountVolume  26s               kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "default-token-2pb8v"
  Normal   Pulling                25s               kubelet, docker-for-desktop  pulling image "jwilder/nginx-proxy:alpine"
  Normal   Pulled                 16s               kubelet, docker-for-desktop  Successfully pulled image "jwilder/nginx-proxy:alpine"
  Warning  Failed                 3s (x3 over 16s)  kubelet, docker-for-desktop  Error: failed to prepare subPath for volumeMount "mount-0" of container "nginx-proxy"
  Normal   Pulled                 3s (x2 over 15s)  kubelet, docker-for-desktop  Container image "jwilder/nginx-proxy:alpine" already present on machine
```

### Information

**EBBC897B-B10A-4591-919E-49B424C9D09E**

```
Docker for Mac: version: 18.05.0-ce-rc1-mac63 (7e2bb492d35dc35ec0037d8024b7e7be57fc72a9)
macOS: version 10.13.4 (build: 17E202)
logs: /tmp/EBBC897B-B10A-4591-919E-49B424C9D09E/20180501-191201.tar.gz
[OK]     vpnkit
[OK]     virtualization hypervisor
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk

```
docker-compose.yml used

```yaml
version: '3.4'
services:
  nginx-proxy:
    image: 'jwilder/nginx-proxy:alpine'
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    restart: always
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - '/Volumes/Data/dockerstuff/volumes/proxy/certs:/etc/nginx/certs:ro'
      - '/Volumes/Data/dockerstuff/volumes/proxy/vhost.d:/etc/nginx/vhost.d'
      - '/Volumes/Data/dockerstuff/volumes/proxy/html:/usr/share/nginx/html'
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

  letsencrypt:
    image: 'jrcs/letsencrypt-nginx-proxy-companion:stable'
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/Volumes/Data/dockerstuff/volumes/proxy/certs:/etc/nginx/certs'
      - '/Volumes/Data/dockerstuff/volumes/proxy/vhost.d:/etc/nginx/vhost.d'
      - '/Volumes/Data/dockerstuff/volumes/proxy/html:/usr/share/nginx/html'
```
### Steps to reproduce the behavior

  1. Install Docker for Mac
  2. Enable Kubernetes
  3. run 'cat docker-compose.yml | docker stack deploy --compose-file - reverse-proxy'
  4. Wait for pods to be created, but not start
