### ISSUE TITLE
Proper configuration for native NFS in Docker For Mac

### ISSUE THREAD

**Issue by torenware** [docker/for-mac#3147]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:  0F41AD3F-6FD8-43E9-B1AE-02CECB5C2745/20180807013009

### Expected behavior
a directory can be shared using NFS native support, with a container not coming up before the share is actually available.
### Actual behavior
The container comes up with NFS related errors.
### Information

    The problem is completely reproduceable; I have yet to get the feature to work. No public documentation is available; Sean Hanley's approach sort of works for some people, but it's trial and error:  https://forums.docker.com/t/nfs-native-support/48531/21

  Here's an edited version of the docker-compose file, showing the volume relevant portion:
````

version: "3.7"

services:

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
    volumes:
      - d8-nfs:/var/www/html # Docker-sync

  nginx:
    image: wodby/drupal-nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - d8-nfs:/var/www/html

volumes:
  d8-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}"
````

  - macOS Version:  10.13.6
    
### Diagnostic logs

```
These aren't uploaded via the ID???
```

### Steps to reproduce the behavior

  1. docker-compose up -d...
  2. ...
