### ISSUE TITLE
Port redirect can't work

### ISSUE THREAD

**Issue by francisconp** [docker/for-mac#315]
### Expected behavior

I'm running a container that expose a port 8000, but it's not work correctly when using docker compose.
It's just work after the firts up state.
### Actual behavior

Access 8000 port after a docker-compose up
### My docker-compose file

``` yaml
version: '2'
services:
  app:
    image: django
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
```
### Information

```
Diagnostic ID: EBB2087A-5723-4878-B128-A4B3B3E8FB4E
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.5 (Build 15F34)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/fpereira/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/EBB2087A-5723-4878-B128-A4B3B3E8FB4E/20160816-235402/qemu-img-check.stdout 2> /tmp/EBB2087A-5723-4878-B128-A4B3B3E8FB4E/20160816-235402/qemu-img-check.stderr: exit 3")
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```
