### ISSUE TITLE
no /etc/hostname file causes compatibility issues

### ISSUE THREAD

**Issue by SvenDowideit** [docker/for-mac#3194]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: A436CF98-31D1-4911-B634-9759A9120D88/20180902235144

### Expected behavior

A compose file / setup / blog post / instruction that assumes it can bind mount /etc/hostname into the container will work on Docker for Mac

### Actual behavior

It fails, because the linuxkit host appears not to have this file.

### Information

  - macOS Version: 10.13.6

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

```
node-exporter:
    image: stefanprodan/swarmprom-node-exporter:v0.15.2
    networks:
      - net
      - infra_traefik
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
 ....
```
