### ISSUE TITLE
Cannot start service traefik

### ISSUE THREAD

**Issue by jvandenrym** [docker/for-mac#3265]
Hello,

I updated to Mac OS Mojave. Docker worked fine before. Now I get the message that traefik cannot use port 80? Nothing seems to be using port 80 like Apache or other...

Using Docker Version 18.06.1-ce-mac73 (26764)

Error

```
ERROR: for traefik  Cannot start service traefik: b'driver failed programming external connectivity on endpoint traefik (f8b1927407c460067eeae24a9b167e57f12460a669e8c9837f4aed8de4f9791b): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)'
ERROR: Encountered errors while bringing up the project.
```
docker-compose.yml (part with traefik)
```
services:
  traefik:
    container_name: traefik
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=traefik'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:traefik.loc'
```
