### ISSUE TITLE
Cannot expose multiple ports in Kubernetes NodePort Service

### ISSUE THREAD

**Issue by buckhx** [docker/for-mac#3315]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

With a NodePort Service that has multiple ports exposed, each port should be accessible on the host. Only the first port is accessible in any configuration.

Here is an example config where only :30080 is accessible on the host, changing the order of the defined ports always exposes the first:

```
spec:
  type: NodePort
  ports:
  - name: http-server
    port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP 
  - name: http-app
    port: 8088
    targetPort: 8088
    nodePort: 30088
```

```
$ curl http://localhost:30080
pong

$ curl http://localhost:30088
curl: (7) Failed to connect to localhost port 30088: Connection refused
```

### Expected behavior

Each port to be accessible as defined. (:30080 & :30088 in this example)
