### ISSUE TITLE
k8s type=LoadBalancer will never assign External-IP if same number of port and different protocol

### ISSUE THREAD

**Issue by hiyosi** [docker/for-mac#3322]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3CDCE464-1A25-4F7B-B06B-09ADFEF80031/20181108055643

### Expected behavior

On Kubernetes built with Docker for Mac,
It can be exposed a Port that is same number and different protocol (e.g., 8600/TCP, 8600/UDP) using with k8s Service type=LoadBalancer.

(e.g., )
```
apiVersion: v1
kind: Service
metadata:
  name: example-tcp
spec:
  type: LoadBalancer
  loadBalancerIP: localhost
  ports:
    - name: tcp-port
      port: 8600
      targetPort: 8600
      protocol: TCP
  selector:
    app: example-app
---
apiVersion: v1
kind: Service
metadata:
  name: example-udp
spec:
  type: LoadBalancer
  loadBalancerIP: localhost
  ports:
    - name: udp-port
      port: 8600
      targetPort: 8600
      protocol: UDP
  selector:
    app: example-app
```

### Actual behavior

Even if you create a service, example-udp will never be assigned External-IP.
```
❯ kubectl get svc
NAME          TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
example-tcp   LoadBalancer   10.107.35.47   localhost     8600:30894/TCP   16s
example-udp   LoadBalancer   10.103.18.90   <pending>     8600:30707/UDP   15s
```

If you changed .spec.ports.port to differenct number against TCP, The example-udp will be assigned External-IP.
```
❯ kubectl get svc
NAME          TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)           AGE
example-tcp   LoadBalancer   10.109.56.165    localhost     8600:30645/TCP    3s
example-udp   LoadBalancer   10.107.215.137   localhost     18600:32619/UDP   3s
```

### Information
  

- macOS Version: 10.14.1

I'm not sure when the problem originated from the version.
Even though, I confirmed that this problem can be reproduced not only on one computer but also on another computer.

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. start Kubernetes clusterr.
  2. apply manifests as follow.

```
apiVersion: v1
kind: Service
metadata:
  name: consul-tcp
spec:
  type: LoadBalancer
  loadBalancerIP: localhost
  ports:
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
    - name: http
      port: 8500
      targetPort: 8500
    - name: https
      port: 8443
      targetPort: 8443
    - name: rpc
      port: 8400
      targetPort: 8400
    - name: server
      port: 8300
      targetPort: 8300
    - name: consuldns-tcp
      port: 8600
      targetPort: 8600
  selector:
    app: consul
---
apiVersion: v1
kind: Service
metadata:
  name: consul-udp
spec:
  type: LoadBalancer
  loadBalancerIP: localhost
  ports:
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
    - name: consuldns-udp
      port: 8600
      targetPort: 8600
      protocol: "UDP"
  selector:
    app: consul
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: consul
  name: consul
spec:
  containers:
    - name: consul
      image: "consul:1.3.0"
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      args:
        - "agent"
        - "-advertise=$(POD_IP)"
        - "-bind=0.0.0.0"
        - "-bootstrap-expect=1"
        - "-retry-join"
        - 'provider=k8s label_selector="app=consul"'
        - "-client=0.0.0.0"
        - "-datacenter=test"
        - "-data-dir=/consul/data"
        - "-server"
        - "-ui"
        - "-disable-host-node-id"
      ports:
        - name: http
          containerPort: 8080
        - name: ui
          containerPort: 8500
        - name: rpc
          containerPort: 8400
        - name: serflan-tcp
          protocol: "TCP"
          containerPort: 8301
        - name: serflan-udp
          protocol: "UDP"
          containerPort: 8301
        - name: serfwan-tcp
          protocol: "TCP"
          containerPort: 8302
        - name: serfwan-udp
          protocol: "UDP"
          containerPort: 8302
        - name: server
          containerPort: 8300
        - name: consuldns-tcp
          containerPort: 8600
        - name: consuldns-udp
          protocol: "UDP"
          containerPort: 8600
```
  3. `kubectl get svc`
```
❯ kubectl get svc
NAME         TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                                                    AGE
consul-tcp   LoadBalancer   10.105.229.208   localhost     8301:31830/TCP,8302:30384/TCP,8500:31336/TCP,8443:31909/TCP,8400:31567/TCP,8300:31395/TCP,8600:31650/TCP   5m
consul-udp   LoadBalancer   10.105.236.221   <pending>     8301:30489/UDP,8302:30300/UDP,8600:32414/UDP                                                               5m
```

  3. `nmap -sT -sU -p8301,8302,8600 localhost`
```
PORT     STATE  SERVICE
8301/tcp open   amberon
8302/tcp open   unknown
8600/tcp open   asterix
8301/udp closed amberon
8302/udp closed unknown
8600/udp closed asterix
```
