### ISSUE TITLE
After upgrade, processes are very slow

### ISSUE THREAD

**Issue by corretge** [docker/for-mac#3361]
After upgrade docker in my developer workstation, some processes are very slow.

  - [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 2ACC2D91-A671-4254-89DD-E04851E950BC/20181123093106

### Expected behavior
execute Symfony cache:clear, fill a MySQL database and reindex Elastichsearch index in a reasonable time.

### Actual behavior
Slow three or four times.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible?  yes
  - Is the problem new? yes
  - Did the problem appear with an update? yes
  - macOS Version: 10.14.1 (18B75)

### Diagnostic logs
```
Docker for Mac: Version 2.0.0.0-mac78 (28905)
  - Diagnostics ID: 2ACC2D91-A671-4254-89DD-E04851E950BC/20181123093106

```

### Steps to reproduce the behavior
I cannot share it, but components used are:
  1. ... php
  2. ... mysql
  3. ... elasticsearch

**Comment by kluevandrew** [comment]
Confirm it, all filesystem operations are extremely slow, for example webpack file watchers and symfony 4.1 cache generating

MacOS 10.14, Docker for Mac: Version 2.0.0.0-mac78

**Comment by molszanski** [comment]
I would recommend trying binded mounts instead of volumes for disk IO heavy work.
Here is a docker-compose example:
```
node:
  build:
    context: ./
    dockerfile: ./dockerfiles/app-dev-1
  volumes:
    - type: bind
      source: ./
      target: /app
      consistency: cached
  ports:
      - 3030:80
```
I think this will "fix" it for you.
Check out the docs for more info about binded mounts. Check notes about cached|delegated in mac version
