### ISSUE TITLE
Bind mounts with shared bind propogation don't work

### ISSUE THREAD

**Issue by segevfiner** [docker/for-mac#3431]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
The following works:
```sh
mkdir /tmp/foo
docker run --rm -it -v /tmp/foo:/foo:shared ubuntu:bionic
```

### Actual behavior
It fails with the following error:
```
docker: Error response from daemon: linux mounts: path /foo is mounted on /foo but it is not a shared mount.
```

### Information

  - macOS Version: 10.14.2

This is due to the osxfs mounts inside the HyperKit VM being mounted with private bind propagation. Entering the VM with screen and changing that using `nsenter` and `mount --make-shared` makes this work until you reboot the VM:

```sh
nsenter -t $(pgrep docker-init) -m mount --make-shared /tmp
```

### Diagnostic logs

```
Docker for Mac: 2.0.0.0-mac81 (29211)
```

### Steps to reproduce the behavior

```sh
mkdir /tmp/foo
docker run --rm -it -v /tmp/foo:/foo:shared ubuntu:bionic
```

**Comment by ameyuuno** [comment]
@segevfiner Hi. Did you fix this problem with `shared` volume? If yes, how did you do that?

**Comment by lots0logs** [comment]
I used the workaround described by the OP (using `nsenter`)

**Comment by ameyuuno** [comment]
@lots0logs can you explain your solution?
I want to use [google-drive-ocamlfuse](https://github.com/mitcdh/docker-google-drive-ocamlfuse/blob/master/README.md) on my Mac via Docker, but it uses `:shared` volume, and I do not understand how to make it works on Mac((

**Comment by freshpomelo** [comment]
Hello everyone,
It seems that I also have this issues.
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/10544528/67142985-4438c500-f299-11e9-8deb-95c2ad1e8729.png">
I searched in Google, it seems that we could set MountFlags to "shared"
https://success.docker.com/article/not-a-shared-mount-error.
But I don't know how to do it on MacOS.

**Comment by segevfiner** [comment]
### Workaround
```sh
screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty
mount --make-shared <mount_point>
# Ctrl-a Ctrl-\
```

**Comment by scodeman** [comment]
Any chance to get a fix delivered on this one ?

**Comment by scodeman** [comment]
If using compose you can instantiate a small container image that makes the mount sharing work in the LinuxKit VM prior running the other containers.

Below worked for me:

**./shared-mount/Dockerfile** 
```
FROM alpine:latest
ENV  MOUNTDIR=/mnt
CMD  nsenter -t $(pgrep docker-init) -m -- mount --verbose --make-shared ${MOUNTDIR}
```

**./docker-compose.yml**
```
---
version: '3.7'

services:
  shared-mount:
    build:
      context: ./shared-mount
    privileged: true
    stdin_open: true
    tty: true
    pid: "host"
    environment:
      - MOUNTDIR=/mnt
  user:
    image: "alpine:latest"
    command: ls /mnt
    depends_on:
        - shared-mount
    volumes:
      - type: bind
        source: "/mnt"
        target: "/mnt"
        bind:
         propagation: rshared
         consistency: delegated
         nocopy: true
```
