### ISSUE TITLE
When two k8s services have an exposed port in common, the 2nd service has none of its ports exposed

### ISSUE THREAD

**Issue by dgageot** [docker/for-mac#3438]
I create two k8s services and those services have one exposed port (666) in common:
```
kind: Service
spec:
  type: LoadBalancer
  ports:
  - name: tcp
    port: 666
    targetPort: 666
  - name: http
    port: 80
    targetPort: 80
---
kind: Service
spec:
  type: NodePort
  ports:
  - name: tcp
    port: 666
    targetPort: 666
  - name: http
    port: 443
    targetPort: 443
```

(Let's assume those services are created in that order)

I expect Docker for Mac to:
 + expose port `80` successfully
 + expose port `666` successfully
 + expose port `443` successfully
 + fail to expose port `666` a second time

Instead, it will:
 + expose port `80` successfully
 + expose port `666` successfully
 + fail to expose port `666` a second time
 + Ignore port `443`

I hit this issue when trying to install [knative](https://github.com/knative/docs/blob/master/install/Knative-with-Docker-for-Mac.md)

Because Istio and Knative Serving both have services that expose the same port (31400), the `knative-ingressgateway` service ends up not being exposed at all.

ping @guillaumerose
