### ISSUE TITLE
Data volumes not shared

### ISSUE THREAD

**Issue by ErikGrimes** [docker/for-mac#356]
### Expected behavior
Given two containers sharing a volume through a data container,  filesystem changes to the volume in one container should be visible to the other container.
### Actual behavior
Filesystem changes in the volume are not shared.
### Information

Diagnostic ID: 121469DD-2625-4A51-8CBC-A3E2B9415D02
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)

### Steps to reproduce

1. Create a compose file with two containers,  data and app.  Export a directory from data and import it in app.
2. Run docker-compose up -d.
3. Exec into app and create a file in the volume.
4. Run docker-compose stop app.
5. Run docker-compose run --rm --entrypoint /bin/bash app.  Check for the file.

**Comment by dsheets** [comment]
Could you please post a more detailed reproduction? In particular, a `docker-compose.yml` file, and `Dockerfile`s, and exact shell commands to run would be very helpful. From your description, it certainly sounds like it should work so either there is an unknown problem with Docker for Mac or some issue with your reproduction.

**Comment by ErikGrimes** [comment]
The compose file is about as basic as it gets

```
data:
  image: healthdynamics/informix_hd:12.10
  volumes:
    - /var/lib/informix  
    - /home
    - /etc
  command: echo "initialize data container"
db:
  image: healthdynamics/informix_hd:12.10
  mem_limit: 3500m
  restart: always
  ports:
    - "12536:1536"
  volumes_from:
    - data
  env_file:
    - db.secrets
```
I'll have to see about the image file.  I'm not sure if there's anything in it I can't share.

I've been unable to reproduce the issue today. If you'd like to close the issue for now, I can request the the issue to be reopened if I see the issue again.  It's a process I repeat fairly regularly.
