### ISSUE TITLE
DNS search name lookups fail in 2.0.5.0, worked in previous edge builds

### ISSUE THREAD

**Issue by itaylor** [docker/for-mac#3715]
I updated today to 2.0.5.0-edge and began having DNS issues I've never had before.  In reading the release notes, there are significant changes to DNS with this release, and I think some of the changes are causing issues with DNS search name lookups.

Setup:
We use Cisco Anyconnect VPN.  I think how it works is it modifies my mac's resolv.conf to add/remove DNS entries.  It adds a search domain 'mycompany.com' and the correct DNS Servers.

I use a docker-compose file to set up my containers.  There is no network configuration specified in the docker-compose.yml, so Docker-compose creates a new bridge mode network for my containers.

With previous edge builds, inside of these containers, I could `curl http://someserver` and it would correctly resolve that as `someserver.mycompany.com`

Now when I do that, I instead get `curl: (6) Could not resolve host: someserver`.
I get the same when I try `docker run -it node:12 curl http://someserver`

I tried going into the Docker Desktop advanced tab and adding:
```
{
  "debug" : true,
  "experimental" : true
  "dns-search": ["mycompany.com"]
}
```
This appears to fix it for a simple case of:
`docker run -it node:12 curl http://someserver`
but fails to fix it for the containers that use docker-compose.  
I also tried setting the `dns_search` key in the docker-compose.yml for each of the containers and this also did not work.

I'm a bit confused why there is a difference between docker-compose and vanilla docker in this instance.

**Comment by thaJeztah** [comment]
Could you do a `docker inspect` of a container created with docker compose, and a container created without docker compose (and perhaps do a `diff` between them?) to see if there's anything that stands out in their configuration been different

**Comment by ruizmarlon** [comment]
Try 2.1
could be related to https://github.com/docker/pinata/pull/11518.  This affected Kube setup.

**Comment by itaylor** [comment]
I'll try creating a simplistic example that doesn't include all the complexities of my docker-compose setup and run `docker inspect` against it.

@ruizmarlon, where would I be able to get 2.1?  2.0.5.0 isn't even listed on the releases page yet.  https://docs.docker.com/docker-for-mac/edge-release-notes/

**Comment by ruizmarlon** [comment]
@itaylor Please disregard my post as I posted in error.  My apologies.

**Comment by itaylor** [comment]
Ok, it's weirder than I thought.  The difference is alpine vs debian.

Here's a docker-compose.yml that exhibits the problem (given my network setup above)
```
version: "2.4"

services:
  simpletest1:
    image: node:12-alpine
    command: sh -c 'apk add --no-cache --virtual curl && curl http://someserver'

  simpletest2:
    image: node:12
    command: curl http://someserver
```
simpletest1 does not resolve the DNS, simpletest2 does
I think they both work fine on 2.0.4.1-edge, but I will downgrade and verify that.

A bit of googling turned up this:
https://forums.docker.com/t/resolved-service-name-resolution-broken-on-alpine-and-docker-1-11-1-cs1/19307/20

Perhaps the changes to DNS handling in 2.0.5.0 have exposed this problem where it was previously hidden for Docker for Mac?

**Comment by itaylor** [comment]
I rolled back to 2.0.4.1 and the above test works again for both alpine and debian containers.

I think this might be the the same issue that's happening here
https://github.com/kubernetes/kubernetes/issues/64924

**Comment by itaylor** [comment]
I was able to get dns search domains to work with alpine-based containers in latest Edge build 2.1.1.0 (37260), but it's not pretty. 

All containers/services need to have `dns_search` explicitly passed due to #3814.  Additionally, alpine-based containers need `dns_opt` passed a value of `ndots:1`

Given that I have a search domain on my mac and can run
`curl http://someserver` and have it return a result from `http://someserver.mycompany.com`, here's what you need to do that same curl call alpine and debian based containers.
 
```
version: "2.4"

services:
  simpletest1:
    image: node:12-alpine
    command: sh -c 'apk add --no-cache --virtual curl && curl http://someserver'
    dns_search:
      - mycompany.com
    dns_opt:
      - ndots:1

  simpletest2:
    image: node:12
    command: curl http://someserver
    dns_search:
      - mycompany.com
```
