### ISSUE TITLE
All docker cli commands fail: "unable to resolve docker endpoint"

### ISSUE THREAD

**Issue by ehoner** [docker/for-mac#3790]
- [x] I have tried with the latest version of Stable
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 23C992DC-93A6-4337-BC79-341BC3DF67F5/20190802202022

### Expected behavior
All `docker` commands should work from the command line.

### Actual behavior
All `docker` commands return an error. No output from `docker`. 
Error:
```
unable to resolve docker endpoint: default orchestrator is kubernetes but unable to resolve kubernetes endpoint: stat /Users/ehoner/.kube/config:/Users/ehoner/.kube/docker-for-desktop:/Users/ehoner/.kube/tst-builds: no such file or directory
```

### Information
This started immediately after docker prompted for upgrade to the latest version. Other commands from `/Applications/Docker.app/Contents/Resources/bin` are working.
* `docker-compose` works correctly from any directory with `docker-compose.yml`
* `kubectl` commands work properly with running cluster in Docker and remote clusters.

  - macOS Version: 10.14.6

### Diagnostic logs
contents of `~/.kube/config`
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ....
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
- cluster:
    insecure-skip-tls-verify: true
    server: https://api.builds.kube.tstllc.net
  name: tst-builds-cluster
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-for-desktop
- context:
    cluster: tst-builds-cluster
    namespace: dataload
    user: tst-builds-user
  name: tst-builds
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: ...
    client-key-data: ...
- name: tst-builds-user
  user:
    client-certificate: tst-builds.crt
    client-key: tst-builds.key
```

```
Docker for Mac: version...
2.1.0.0 (36874) stable
```

### Steps to reproduce the behavior

  1. Uninstall Docker
  2. clean `$ rm -rf ~/.kube`
  3. Reinstall docker for mac
  4. `$ docker ps`
