### ISSUE TITLE
gelf driver doesn't work

### ISSUE THREAD

**Issue by dzirg44** [docker/for-mac#3864]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: ACA97E73-1FC1-48C4-BDB2-582B72FF82ED/20190824114547

### Expected behavior
 - sending logs via gelf driver to the logstash container
### Actual behavior
- nothing happens
### Information

  - it is reproducible
  - this problem doesn't appear on linux systems.
  - macOS Version: 10.14.6

### Diagnostic logs

```
Docker for Mac: 2.1.0.1 (stable)

```

### Steps to reproduce the behavior

  1. write simple docker-compose.yml file
```yml
version: "3"

services:
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.1.1
    ports:
      - 12201:12201/udp
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - logging-network

  httpd:
    image: httpd:latest
    depends_on:
      - logstash
    ports:
      - 8033:80
    logging:
      driver: gelf
      options:
        gelf-address: "udp://0.0.0.0:12201"
        tag: "http"
    networks:
      - logging-network


networks:
  logging-network:
    driver: bridge
```
  2. put into this directory `logstash.conf` file
```js
input {
  gelf {}
}

output {
  stdout {
    codec => rubydebug
  }
}
```
3. start with command
```
docker-compose up
```
4. use `curl` 
```
curl http://0.0.0.0:8033
```
