### ISSUE TITLE
[Kubernetes] Custom Data on Persistant Volume lost on Mac restart 

### ISSUE THREAD

**Issue by RobertoDonPedro** [docker/for-mac#4019]
I am running an app using MySQL mounted on a volume of `kind: PersistantVolume` via `kind: StorageClass`.
Pods a running fine and custom data are successfully applied to the DB. 
But when I restart the Mac all custom data is lost and the database is reset to its initial state of the image.

### Expected behavior
Custom data on Persistant volume should be still available after Mac restart
### Actual behavior
Custom data lost after Mac restart
### Information

  - macOS Version:
16.7.0 Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64

Docker for Mac: version...
2.1.0.4
Engine 19.03.4
Kubernetes: v1.14.7

**Comment by aferrandini** [comment]
Did you find a solution for this?

**Comment by RobertoDonPedro** [comment]
> Did you find a solution for this?

No...

**Comment by aferrandini** [comment]
I solved using what mention in this issue:

https://github.com/docker/for-mac/issues/3488

My configuration was something like this:
 1. Add the shared folder into Docker for Mac configuration. (Folder like `/usr/local/var/mysql/data`) you must create the folder before.

2. Apply the persistant volume like this:
```
#
# Persistent Volume
#
apiVersion: v1
kind: PersistentVolume                        # Create a PV
metadata:
  name: mysql-pv-volume
  labels:
    type: local
    app: app-mysql
spec:
  storageClassName: manual                    # Storage class. A PV Claim requesting the same storageClass can be bound to this volume.
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:                                   # hostPath PersistentVolume is used for development and testing. It uses a file/directory on the Node to emulate network-attached storage
    path: "/usr/local/var/mysql/data"
  persistentVolumeReclaimPolicy: Retain       # Retain the PV even after PVC is deleted.
---
#
# Persistent Volume Claim
#
apiVersion: v1
kind: PersistentVolumeClaim                   # Create a PersistentVolumeClaim to request a PersistentVolume storage
metadata:                                     # Claim name and labels
  name: mysql-pv-claim
  labels:
    app: app-mysql
spec:                                         # Access mode and resource limits
  storageClassName: manual                    # Request a certain storage class
  accessModes:
    - ReadWriteMany                           # ReadWriteMany means the volume can be mounted as read-write by many Nodes
  resources:
    requests:
      storage: 256Mi
```

3. Use the volume in your deployment:
```
#
# Deployment
#
apiVersion: apps/v1
kind: Deployment                              # Type of the kubernetes resource
metadata:
  name: app-mysql                         # Name of the deployment (Use this name as db host in your application)
  labels:                                     # Labels applied to this deployment
    app: app-mysql
spec:
  selector:
    matchLabels:                              # This deployment applies to the Pods matching the specified labels
      app: app-mysql
      tier: mysql
  strategy:
    type: Recreate
  replicas: 1
  template:                                   # Template for the pods in this deployment
    metadata:
      labels:                                 # labels to be applied to the pods in this deployment
        app: app-mysql
        tier: mysql
    spec:                                     # The spec for the containers that will be run inside the Pods in this deployment
      containers:
        - image: mysql:5.7                    # The container image
          name: mysql
          imagePullPolicy: "IfNotPresent"     # Get it from dockerhub if it is not present in our machine

          envFrom:                            # Environment variables passed to the container
            - secretRef:                      # Read environment variables from kubernetes secrets
                name: app-secret

          ports:
            - containerPort: 3306             # The port that the container exposes
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage  # This name should match the name specified in `volumes.name`
      volumes:                                # A PersistentVolume is mounted as a volume to the Pod
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
#
# Service
#
apiVersion: v1                                # API version
kind: Service                                 # Type of kubernetes resource
metadata:
  name: app-mysql                         # Name of the resource
  labels:                                     # Labels that will be applied to the resource
    app: app-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:                                   # Selects any Pod with labels `app=app-mysql,tier=mysql`
    app: app-mysql
    tier: mysql
```
