### ISSUE TITLE
Docker Desktop 2.1.0.5 (40693) does not support docker-compose file version 3.7 on macOS 10.13.6 High Sierra

### ISSUE THREAD

**Issue by philippefutureboy** [docker/for-mac#4131]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D300511C-01EE-476C-BE9B-F23D40CF09F5/20191214202237

### Expected behavior

Docker Desktop for Mac @2.1.0.5 (40693) should support docker-compose file version 3.7 based on version support section in the documentation [here](https://docs.docker.com/compose/compose-file/compose-versioning/)

### Actual behavior

Given:

```
version: "3.7"

services:
  node:
    container_name: node__server
    build:
      context: .
      target: production
    user: node
    ports:
      - "${DOCKER_HOST_PORT:-80}:8080"
      - "${DOCKER_HOST_TLS_PORT:-4433}:4433"
    restart: always
    env_file:
      - .env
      - .env.production
      - .env.production.local
```

`docker-compose up` returns:

```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

### Information
Please, help us understand the problem.  For instance:
  - *Is it reproducible?* Yes, at least it seems consistent on my machine.
  - *Is the problem new?* Yes, just attempted to use the `service.<name>.build.target` directive.
  - *Did the problem appear with an update?* No (or yes as manual update to troubleshoot)
  - *A reproducible case if this is a bug, Dockerfiles FTW.* Unnecessary as the bug doesn't even reach the Dockerfile step.
-->
  - *macOS Version:* macOS 10.13.6 High Sierra

### Steps to reproduce the behavior
1. Install any version of Docker Desktop with Docker Engine >=18.06.0+ for Mac on a macOS 10.13.6 machine. For optimal reproducibility use build 2.1.0.5 (40693) - stable.
2. Attempt to run the provided docker-compose.yml file above
3. Observe/Not Observe the bug

Then again, this may just be a setup error on my side. I couldn't find some troubleshooting guidelines beyond [the following](https://docs.docker.com/docker-for-mac/troubleshoot/), so if there is anything more precise that I should do, let me know :)
FYI I didn't restart my computer between re-installs.

Have a great day! ☀️
