### ISSUE TITLE
Performance got worse after update

### ISSUE THREAD

**Issue by alexandruluca** [docker/for-mac#4289]
I have recently updated to version 2.2.0.3 (42716)

I only have two containers running, one mysql container and one elastic container.

I am using the container to run tests for a nodejs application (nodejs application does not run in container).

After I updated docker, I noticed that my tests started to run a lot slower, ocasionally they even time out.

I'm using docker-compose to start the containers, the compose file looks like this:
```
version: '3.3'
services:
  mysql-development:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: test
    ports:
      - "3308:3306"
    volumes:
      - .:/application:cached
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  elastic:
    driver: bridge

```

Sorry if the opened issue does not comply to the standards, but it's the best I can do.
