### ISSUE TITLE
Pods are not discoverable in the default setup by their name

### ISSUE THREAD

**Issue by iillanmimecast** [docker/for-mac#4380]
I am trying to resolve DNS by pod name. More specifically I am trying to run Spark over Kubernetes, which is failing because the executors are not able to connect with the driver because of this behaviour. To keep things simpler, I will explain the problem without using Spark at all.

### Expected behavior
I should be able to resolve DNS for pods by name within Kubernetes

### Actual behavior
I get an NXDOMAIN error when trying to resolve the DNS for pods by name within Kubernetes.

### Information
I am not able to resolve the DNS for pods by name within kubernetes cluster. Check below for details.
  - macOS Version: macOS Mojave 10.14.6

### Diagnostic logs
```
Docker for Mac: 2.2.0.4 (43472)

```

### Steps to reproduce the behavior

In the default setup for Kubernetes, I try running the example in https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

Given the following `dnsutils.yaml` manifest file
```
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```
1. I run `kubectl apply -f dnsutils.yaml`
2. When I try running `kubectl exec -ti dnsutils -- nslookup kubernetes.default` this works fine
3. When running `kubectl exec -ti dnsutils -- nslookup kafka` works fine where kafka is defined as a `Service`
4. But when trying to lookup for pods, coredns is not able to resolve them, not even the local one. For example, if I try running
`kubectl exec -ti dnsutils -- nslookup dnsutils.default`
This will give an NXDOMAIN error.  I can check on the logs coredns is receiving the request and returning NXDOMAIN.
