### ISSUE TITLE
NFS Mount Fails with a Stale File handler

### ISSUE THREAD

**Issue by danielkleach** [docker/for-mac#4452]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
- [ x] I have uploaded Diagnostics
  - Diagnostics ID: ADA5034E-0652-4C3E-9598-A8D90544D273/20200414192507

### Expected behavior
NFS volume should be mounted and list files shared from my mac host.
I am following this guide. https://medium.com/@sean.handley/how-to-set-up-docker-for-mac-with-native-nfs-145151458adc

### Actual behavior
ls: cannot open directory '.': Stale file handle
### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes, but only on my machine.
  - Is the problem new? We are just starting to try using NFS. The problem does not exist with built-in file sharing.
  - Did the problem appear with an update? No.
  - A reproducible case if this is a bug, Dockerfiles FTW.

Here is my docker compose contents:
DB is MySQL
Web is Nginx
App is php 7.3 fpm
Redis is redis-server
ES is elasticsearch
KB is Kibana

All of our containers are built from the default docker hub official images. This works on at least two other computers in our company.
```
version: "3"
services:
  db:
    container_name: db
    image: db:latest
    environment:
      - MYSQL_ROOT_PASSWORD=redacted
      - APP=db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    container_name: redis
    image: cache:latest
    environment:
      - APP=redis
    ports:
      - "6379:6379"
    volumes:
      - ~/Documents/Repositories/Docker/redis/data:/data
  app:
    container_name: app
    image: app:latest
    environment:
      - APP=app
    links:
      - db
      - redis
    volumes:
      - "nfsmount:${CONTAINER_DIR}:delegated"
  web:
    container_name: web
    image: web:latest
    environment:
      - APP=web
    links:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nfsmount:${CONTAINER_DIR}:delegated"
  es:
    image: es:latest
    container_name: es
    hostname: es
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
  kb:
    image: kb:latest
    container_name: kb
    hostname: kb
    links:
      - es
    ports:
      - "5601:5601"
volumes:
  mysql_data:
    driver: local
  cache_data:
    driver: local
  elasticsearch_data:
    driver: local
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${SOURCE_DIR}"

```
  - macOS Version: 10.15.3 Catalina

### Diagnostic logs
It's a folder full of files. I am unsure what to paste here.
```
Docker for Mac: version...
2.2.0.5
```

### Steps to reproduce the behavior

  1. It happens consistently on my Mac, but not on others at the company.
  2. Docker compose up
