### ISSUE TITLE
Docker for Mac Kubernetes load balancer exposed on all interfaces

### ISSUE THREAD

**Issue by b4nst** [docker/for-mac#4490]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
 
LoadBalancer exposed only on local interface by default

### Actual behavior

LoadBalancer exposed on all interfaces

### Information

  - macOS Version: 10.15.3

First raised here : https://github.com/docker/for-mac/issues/2445#issuecomment-366374939

When a service is exposed with the LoadBalancer provided with Docker for Mac, it's exposed on all interfaces. 

Here is a simple deployment/service exposing the issue:

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  namespace: default
  labels:
    app: containous
    name: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: containous
      task: whoami
  template:
    metadata:
      labels:
        app: containous
        task: whoami
    spec:
      containers:
        - name: containouswhoami
          image: containous/whoami
          ports:
            - containerPort: 80
            
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  type: LoadBalancer
  selector:
    app: containous
    task: whoami
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: 80
```

### Steps to reproduce the behavior

  1. Deploy the provided example (`kubectl apply -f filename`)
  2. Find your *local_ip* (`ipconfig getifaddr en0`)
  3. Try to access to http://*local_ip* from another device on the same network
  4. That should not succeed (but it does)

Currently the only way I found was to enable pf firewall to drop incoming traffic from en0, but that's not a durable nor convenient way.
