### ISSUE TITLE
Unable to pull private repository images into K8s cluster (credsStore related)

### ISSUE THREAD

**Issue by malimccalla** [docker/for-mac#4545]
### Information

- macOS Version: 10.15.4
- Docker for Mac: 2.3.0.2
- [x] I have tried with the latest version of my channel (Stable or Edge)
- [x] I have uploaded Diagnostics
- Diagnostics ID: `1F3961D6-FF25-4E6F-B759-53A851F3B170/20200512100007`

### Issue

I need to be able to be able to pull private images into my docker-desktop k8s cluster. After making sure I've authenticated with `docker login` I run the command

```
kubectl create secret generic regcred \
  --from-file=.dockerconfigjson=/Users/mali/.docker/config.json \
  --type=kubernetes.io/dockerconfigjson
```

Which adds a Secret to my cluster looking like this

```yaml
apiVersion: v1
kind: Secret
metadata:
  ...
  name: regcred
  ...
data:
  .dockerconfigjson: eyJodHRwczovL2luZGV4L ... base64 ... J0QUl6RTIifX0=
type: kubernetes.io/dockerconfigjson
```

I then apply my Deployment config that uses the private image to the cluster but I am met with the error 

```
Failed to pull image "org/name": rpc error: code = Unknown desc = Error response from daemon: pull access denied for org/name, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

I know that I have successfully authenticated with docker on my machine to access this image as I can run `docker pull org/name` successfully. It seems to be an issue with the cluster reading the credentials

For completeness sake my docker config file looks exactly like this after a successful `docker login`

```json
{
  "auths": {
    "https://index.docker.io/v1/": {}
  },
  "HttpHeaders": {
    "User-Agent": "Docker-Client/19.03.8 (darwin)"
  },
  "credsStore": "osxkeychain"
}
```

I believe this may be related to #4100
