### ISSUE TITLE
Use Calico as a Container Network Interface for Kubernetes in Docker Desktop

### ISSUE THREAD

**Issue by Kelvin-M** [docker/for-mac#4626]
- [x] I have tried with the latest version of my channel : **Stable - v2.3.0.3**
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: None

### Expected behavior
Use [NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) to limit pod networking : it should not be able to fetch the url

Example (**test-cni.yaml**)
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test-cni
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: test-cni
spec:
  podSelector:
    matchLabels:
      task: no-network
  policyTypes:
  - Ingress
  - Egress
  egress: []
  ingress: []
---
apiVersion: v1
kind: Pod
metadata:
  name: test-cni-pod
  namespace: test-cni
  labels:
    task: no-network
spec:
  containers:
  - name: test-cni-pod
    image: busybox
    command: ["wget", "google.fr"]
  restartPolicy: Never

```

### Actual behavior
I tried to use [NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) in the local kubernetes single node DockerDesktop for mac but it was not taken into account.

As it seems there is no CNI installed by default, I tried to solve this issue with calico : 

`kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml` 

No issue in the installation, pods in kube-system are running but NetworkPolicy still doesn't work at all.

To confirm no issue with my example and setup with calico, I tried it with minikube with same kubernetes cluster version v1.16.5 but with option to allow CNI and the use of CNI plugin in kublet.
`minikube start --kubernetes-version="v1.16.5" --vm-driver=hyperkit --network-plugin=cni --extra-config=kubelet.network-plugin=cni`
 
As expected it works ! 

### Information

  - macOS Version: macOS Catalina 10.15.5
  - related question : https://github.com/docker/docker.github.io/issues/9535
### Diagnostic logs

```
Docker for Mac: version Stable - v2.3.0.3

```

### Steps to reproduce the behavior

  1. Start kubernetes cluster in Docker-Desktop for mac
  2. `kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml` 
  3. 'kubecctl apply -f test-cni.yaml` (yaml in the expected behavior)

### Questions:
 - Am I missing something in my example that prevent it from working in Docker-Desktop ?
 - Is it possible to use NetworkPolicy or install a CNI in the kubernetes cluster of Docker-Desktop ?

Thank you for your help !
