### ISSUE TITLE
[MUTAGEN] More than one cached folder gives error with no reason

### ISSUE THREAD

**Issue by JuanWilde** [docker/for-mac#4633]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

### Expected behavior
Cache more than one project folder

### Actual behavior
After run more than one project some of the folders fail and stop syncing

### Information
  - macOS Version: 10.15.4

### Diagnostic logs
Diagnose ID: `B570AD0E-9013-4156-B508-1F7FBF5B8146/20200601075449`
```
Docker for Mac: version...
2.3.1.0 (Edge)
```

### Steps to reproduce the behavior
Create 2 projects with its docker-compose.yml files. Add those 2 folders to the sync directories. Run both projects at the same time. After a while, one of them shows `Error`

**Comment by stephen-turner** [comment]
Thanks for the report, @JuanWilde. Could you please paste the docker-compose.yml files and the docker run commands you are using? Thanks.

**Comment by JuanWilde** [comment]
Sure. This is the `docker-compose.yml` file
```
version: '3.5'

services:
  project-web:
    container_name: project-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 500:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - project-be
    networks:
      - project-network

  project-be:
    container_name: project-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9005
    volumes:
      - ./:/appdata/www
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - project-db
    networks:
      - project-network

  project-db:
    container_name: project-db
    image: mysql:8
    ports:
      - 33000:3306
    environment:
      MYSQL_DATABASE: project_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - project-db-data:/var/lib/mysql
    networks:
      - project-network

volumes:
  project-db-data:

networks:
  project-network:

```
Dockerfile
```
FROM php:7.4.2-fpm

ARG UID
EXPOSE $UID

RUN adduser -u ${UID} --disabled-password --gecos "" appuser
RUN mkdir /home/appuser/.ssh
RUN chown -R appuser:appuser /home/appuser/
RUN echo "StrictHostKeyChecking no" >> /home/appuser/.ssh/config
RUN echo "export COLUMNS=300" >> /home/appuser/.bashrc
RUN echo "alias sf=/appdata/www/bin/console" >> /home/appuser/.bashrc

COPY ./php.ini /usr/local/etc/php/php.ini

RUN apt-get update \
    && apt-get install -y git acl openssl openssh-client wget zip vim librabbitmq-dev libssh-dev \
    && apt-get install -y libpng-dev zlib1g-dev libzip-dev libxml2-dev libicu-dev \
    && docker-php-ext-install intl pdo pdo_mysql zip gd soap \
    && pecl install xdebug \
    && docker-php-ext-enable --ini-name 05-opcache.ini opcache xdebug

RUN curl --insecure https://getcomposer.org/composer.phar -o /usr/bin/composer && chmod +x /usr/bin/composer
RUN composer self-update

RUN wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
RUN chmod a+x php-cs-fixer
RUN mv php-cs-fixer /usr/local/bin/php-cs-fixer

RUN mkdir -p /appdata/www

USER appuser
RUN composer global require "hirak/prestissimo:^0.3" --prefer-dist --no-progress --no-suggest --optimize-autoloader --classmap-authoritative \
	&& composer clear-cache

WORKDIR /appdata/www
```
Makefile to run some commands
```
#!/bin/bash

DOCKER_BE = project-be
UID = $(shell id -u)

help: ## Show this help message
	@echo 'usage: make [target]'
	@echo
	@echo 'targets:'
	@egrep '^(.+)\:\ ##\ (.+)' ${MAKEFILE_LIST} | column -t -c 2 -s ':#'

run: ## Start the containers
	U_ID=${UID} docker-compose up -d

stop: ## Stop the containers
	U_ID=${UID} docker-compose stop

restart: ## Restart the containers
	$(MAKE) stop && $(MAKE) run

build: ## Rebuilds all the containers
	U_ID=${UID} docker-compose build

prepare: ## Runs backend commands
	$(MAKE) composer-install
	$(MAKE) migrations

# Backend commands
composer-install: ## Installs composer dependencies
	U_ID=${UID} docker exec --user ${UID} -it ${DOCKER_BE} composer install --no-scripts --no-interaction --optimize-autoloader

migrations: ## Runs the migrations
	U_ID=${UID} docker exec -it --user ${UID} ${DOCKER_BE} bin/console doctrine:migrations:migrate -n

be-logs: ## Tails the Symfony dev log
	U_ID=${UID} docker exec -it --user ${UID} ${DOCKER_BE} tail -f var/log/dev.log
# End backend commands

ssh-be: ## ssh's into the be container
	U_ID=${UID} docker exec -it --user ${UID} ${DOCKER_BE} bash

code-style: ## Runs php-cs to fix code styling following Symfony rules
	U_ID=${UID} docker exec -it --user ${UID} ${DOCKER_BE} php-cs-fixer fix src --rules=@Symfony
#	php-cs-fixer fix tests --rules=@Symfony

generate-ssh-keys: ## Generate ssh keys in the container
	U_ID=${UID} docker exec -it --user ${UID} ${DOCKER_BE} mkdir -p config/jwt
	U_ID=${UID} docker exec -it --user ${UID} ${DOCKER_BE} openssl genrsa -passout pass:project -out config/jwt/private.pem -aes256 4096
	U_ID=${UID} docker exec -it --user ${UID} ${DOCKER_BE} openssl rsa -pubout -passin pass:project -in config/jwt/private.pem -out config/jwt/public.pem
```

So basically what I've tried was having 2 projects with this configuration and adding both folders in 
`preferences -> Resources -> File Sharing`
Then run both with `make run` and start editing some files in PHPStorm. After some refreshes and reloads one of the folders shows `Error` and I have to delete, create it and then re-create those containers.
