### ISSUE TITLE
How to make docker bind ipv4 address or make the ipv4 address being accessed?

### ISSUE THREAD

**Issue by PCanyi** [docker/for-mac#4640]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:011438BA-D1BB-4307-BDFC-684924F2C61F/20200603143839

### Expected behavior
Docker desktop 2.3.0.3 bind docker nginx container with ipv4 address or the docker nginx container can be accessed by an ipv4 ip

### Actual behavior
Docker desktop 2.3.0.3 bind docker nginx container with ipv6 address and the docker nginx can not be accessed by an ipv4 ip

Not only the nginx container, It seems that all docker containers bind the ipv6 address and have no way to be accessed by the other mathine in the local network.

On linux system, I can use sysctl to set ipv6 forward to ipv4 to make this problem solved, such as:
```
net.ipv6.conf.all.forwarding = 1
net.ipv6.bindv6only = 0
```
But it seems that there are no solutions to solve this on macos. I have found and tried many of ways, but no effect.

### Information

  - macOS Version:10.15.5
I use the command `lsof -i -P |grep -i "listen"`， And the result is as follows:

```
#lsof -i -P|grep -i "listen"              
com.docke 50512 pcanyi   49u  IPv6 0x94fa169a9f816219      0t0  TCP *:10443 (LISTEN)
com.docke 50512 pcanyi   50u  IPv6 0x94fa169a9f817479      0t0  TCP *:10080 (LISTEN)
com.docke 50512 pcanyi   51u  IPv6 0x94fa169a9f814fb9      0t0  TCP *:443 (LISTEN)
com.docke 50512 pcanyi   52u  IPv6 0x94fa169a9f814999      0t0  TCP *:80 (LISTEN)
```

### Diagnostic logs

```
Docker for Mac: version...

I have upload the logs

```

### Steps to reproduce the behavior

  1. Only need to install Docker Desktop for mac of version 2.3.0.3
  2. Only need to generate any docker container service which need binding ports

My docker-compose configure is as follows:
```
web-master:
    image: nginx
    container_name: nginx-master-1
    restart: always
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    environment:
      - TZ=Asia/Shanghai
      - NGINX_HOST=master.test.com
      - NGINX_PORT=80
    volumes:
      - '$GITLAB_HOME/srv/nginx/conf:/etc/nginx'
      - '$GITLAB_HOME/srv/nginx/conf/conf.d/mysite.template:/etc/nginx/conf.d/mysite.template'
      - '$GITLAB_HOME/srv/nginx/htdocs:/usr/share/nginx/html'
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"  
```
