### ISSUE TITLE
Docker swarm mode on OS X does not let me connect to containers using port mapping

### ISSUE THREAD

**Issue by ujwal-setlur** [docker/for-mac#4704]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I should be able to connect to mapped ports onto my host in swarm mode. 

### Actual behavior
I cannot connect to mapped ports in swarm mode. The port seems to be open, but the traffic is not routed to container.

### Information

  - Is it reproducible? Yes
  - Is the problem new? I don't know
  - Did the problem appear with an update? No
  - A reproducible case if this is a bug, Dockerfiles FTW.

I ran a simple stack file on my OS X host with docker in swarm mode:

```yaml
# This YAML docker compose file will launch a rabbitmq cluster
#
version: "3.8"

# NGINX service
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
```

```docker stack deploy -c docker-compose.yml test```

Then I did a ```curl http://localhost```, and it hung. Port 80 does seem to be open on my OS X host, but the traffic is not routed to the ```nginx``` service.

This works just fine with ```docker-compose```, just not with ```docker swarm```

  - macOS Version:

### Diagnostic logs

```
Docker for Mac: 2.3.1.0 edge channel

Diagnostic ID: 8C0BD9CE-4CCF-4F83-A558-ABDABC519DA6/20200624191322

```
