### ISSUE TITLE
kubernetes rbac rules (still) not enforced

### ISSUE THREAD

**Issue by davidje13** [docker/for-mac#4774]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

This is a refresh of #3694, as that issue was believed to be fixed but actually still exists in 2.3.0.3 (45519). The old issue has been locked due to age.

Run the following:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa

---

apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  serviceAccountName: test-sa
  containers:
  - image: alpine
    name: test-container
    command: [sh]
    args:
    - -ec
    - |
      apk add curl;
      KUBE_NAMESPACE="$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)";
      curl \
        --cacert "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt" \
        -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
        "https://kubernetes.default.svc/api/v1/namespaces/$KUBE_NAMESPACE/services";
      while true; do sleep 1; done;
```

```sh
kubectl apply -f test.yml
kubectl logs test-pod
```

### Expected behavior

Permissions error (403)

### Actual behavior

API request succeeds

### Information

```sh
kubectl get clusterrolebinding docker-for-desktop-binding -o yaml
```

> ```
> apiVersion: rbac.authorization.k8s.io/v1
> kind: ClusterRoleBinding
> metadata:
>   creationTimestamp: "2020-06-22T13:01:34Z"
>   name: docker-for-desktop-binding
>   resourceVersion: "478"
>   selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/docker-for-desktop-binding
>   uid: f4d43180-d35e-448c-ba41-db0a1330baff
> roleRef:
>   apiGroup: rbac.authorization.k8s.io
>   kind: ClusterRole
>   name: cluster-admin
> subjects:
> - apiGroup: rbac.authorization.k8s.io
>   kind: Group
>   name: system:serviceaccounts
>   namespace: kube-system
> ```

```sh
kubectl auth can-i --list --as system:serviceaccount
```

> ```
> Resources                                       Non-Resource URLs   Resource Names   Verbs
> *.*                                             []                  []               [*]
>                                                 [*]                 []               [*]
> selfsubjectaccessreviews.authorization.k8s.io   []                  []               [create]
> selfsubjectrulesreviews.authorization.k8s.io    []                  []               [create]
>                                                 [/api/*]            []               [get]
>                                                 [/api]              []               [get]
>                                                 [/apis/*]           []               [get]
>                                                 [/apis]             []               [get]
>                                                 [/healthz]          []               [get]
>                                                 [/healthz]          []               [get]
>                                                 [/livez]            []               [get]
>                                                 [/livez]            []               [get]
>                                                 [/openapi/*]        []               [get]
>                                                 [/openapi]          []               [get]
>                                                 [/readyz]           []               [get]
>                                                 [/readyz]           []               [get]
>                                                 [/version/]         []               [get]
>                                                 [/version/]         []               [get]
>                                                 [/version]          []               [get]
>                                                 [/version]          []               [get]
> ```

rnsv posted the necessary fix in the old issue here: https://github.com/docker/for-mac/issues/3694#issuecomment-619474504 (the namespace was applied to the wrong part of the spec)

### Diagnostic logs

```
Docker for Mac: 2.3.0.3 (45519)
```
