### ISSUE TITLE
mount point keeps getting unmounted

### ISSUE THREAD

**Issue by kzw** [docker/for-mac#4869]
I have been using docker-compose to run a nginx container with multiple mount points for a year or so.  But recently, one of the mount points will mysteriously get unmounted without any warning during usage.  It does get mounted at first.  I turned on debugging in docker daemon and tried to watch the log and I am also unable to find a pattern when it would get unmounted.  I gave up docker mac and start relying on linux instance; at some point I also experienced the same issue with linux but I believe the problem went away when I changed to mounted only ro.   Now I revisit docker mac: even with mounted ro, one mount point is getting dismounted some time later after working as expected.  

I think this problem is similar to https://github.com/docker/for-mac/issues/3976 but in my case there is no need to do anything like touch a file anywhere

This might help: when the volume disappear nginx will time out serving assets from disappearing volume; browser will take a very long time to load the assets.  At that point, i will `exec -it` in the container and find that the volume is no longer there.

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: E5CC1351-3F8A-4220-A7B5-552E8D18C53D/20200829122615

### Information

  - macOS Version: 10.15.6

### Diagnostic logs

```
Docker for Mac: version  2.3.0.4 (46911)

```

### Steps to reproduce the behavior

Snippet of docker-compose

```
version: "3"
services:
  html:
    container_name: html
    depends_on:
      - loyal
    image: redacted.dkr.ecr.us-east-1.amazonaws.com/nginx-base:local
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./firm-data:/loyal-root/firm-data:ro
      - ./ui/docs/dist:/loyal-root/docs:ro
      - ~/docs-img:/loyal-root/docs/img:ro
      - ~/ico:/loyal-root/ico:ro
      - ~/img:/loyal-root/img:ro
      - ~/admin-assets:/html:ro
      - /tmp/:/nginx
      - ./django/nose-cover:/nose:ro
      - ./ui/app/coverage/lcov-report:/jest:ro
      - ./ui/app/code/root:/loyal-root
      - ~/ssl:/etc/ssl:ro
      - /tmp/letsencrypt:/tmp/letsencrypt

```
