### ISSUE TITLE
Volume stop syncing with host after update to 2.4.0.0

### ISSUE THREAD

**Issue by bogdan-dubyk** [docker/for-mac#4969]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FB5E219A-C1FB-45DC-99D4-1E6E3D7DA347/20201003222902

### Expected behavior
Changes between host and volume should sync in real-time

### Actual behavior

It's syncing for a few minutes after I run `docker-compose up`, to make it sync again I need to re-run containers

### Information

I'm working with docker locally on my MAC already for years, I have different projects running on docker with a docker-compose. All were fine until I update the docker desktop to version 2.4.0.0.

After updating, I was not able to make docker-compose up because the docker told me that something wrong with volumes, I do not remember the exact error, but I had a similar issue before and the re-creation of volumes helped. At this time it also helped, but something happened with sync between host and container, some times I can edit files and they are syncing correctly for some period of time (like 15 minutes) and then stop syncing, and I need to rerun containers. Sometimes rerun helps and sync starts working again for some period of time, sometimes it does not help and I need re-run a few times in a raw.

Here is how mo volumes initialized in docker_compose.yml:
```
volumes:
  postgresql_data:
    driver: local
  mysql_data:
    driver: local
  mongo_data:
    driver: local
  workspace_volume:
    driver: local
    driver_opts:
      type: bind
      device: "$PWD/../services"
      o: bind
  redis_data:
    driver: local
```

  - macOS Version: 10.15.6

### Diagnostic logs

```
Docker for Mac: 2.4.0.0
```
