### ISSUE TITLE
Not mounting on docker.sock anymore

### ISSUE THREAD

**Issue by soupli** [docker/for-mac#4973]
- [x] I have tried with the latest version of my channel (Stable)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Simply run the whole stack. No problems with 2.3.8.0

### Actual behavior
```shell
Creating tool ... error

ERROR: for tool  Cannot start service tool: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/run/host-services/docker.proxy.sock\\\" to rootfs \\\"/var/lib/docker/overlay2/85340584fadd4522737bebf44d7179526fbb3e7fd47b0dc2c6933875895d3919/merged\\\" at \\\"/var/run/docker.sock\\\" caused \\\"stat /run/host-services/docker.proxy.sock: no such file or directory\\\"\"": unknown

ERROR: for tool  Cannot start service tool: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/run/host-services/docker.proxy.sock\\\" to rootfs \\\"/var/lib/docker/overlay2/85340584fadd4522737bebf44d7179526fbb3e7fd47b0dc2c6933875895d3919/merged\\\" at \\\"/var/run/docker.sock\\\" caused \\\"stat /run/host-services/docker.proxy.sock: no such file or directory\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.
```

### Information
  - Is it reproducible?
yes
  - Is the problem new?
since 2.4.0.0
  - Did the problem appear with an update?
yes

### Diagnostic logs
macOS Version:
Docker for Mac Version: 19.03.13, build 4484c46d9d

### Steps to reproduce the behavior
docker-compose.yml
```yaml
tool:
    container_name: tool
    hostname: tool
    image: repo/tool:latest      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
`docker-compose up -d`

**Comment by stephen-turner** [comment]
@soupli Does it work if you switch back to osxfs in the settings?

**Comment by soupli** [comment]
No, sorry. Forgot to mention!

Switched back to osxfs did not work unfortunately

Added the `/run` dir to resources > file sharing didn't work either.

Thanks

Op ma 5 okt. 2020 11:44 schreef Stephen Turner <notifications@github.com>:

**Comment by StefanScherer** [comment]
I tried to reproduce it with the following docker-compose.yml, but it works fine for me. I tested both gRPC FUSE and the old osxfs setting. I have tested it with DD 2.4.0.0 Stable on Catalina.

```yaml
version: "3.7"
services:
  portainer:
    image: portainer/portainer:1.24.1
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './data/portainer:/data'
    expose:
      - 9000
    ports:
      - 80:9000
```

**Comment by soupli** [comment]
Thank you Stefan, i will try this out asap and report back



Op ma 5 okt. 2020 om 14:44 schreef Stefan Scherer <notifications@github.com

**Comment by soupli** [comment]
disclaimer: `tmpfs` mounts are only available on Linux hosts

---

With some trial and error i have concluded that the problem is lying in the `tmpfs` portion of the docker compose file.
The stack containing a mount to `docker.sock` works just fine with the file below;
```yml
version: '3.7'
services:
  tool:
    container_name: tool
    hostname: tool
    image: repo/tool:latest      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    tmpfs:
      - /var/cache  
    depends_on:
      - proxy
    environment:
      - SUHOMEDIR=${HOME}
    networks:
      local-net:
        ipv4_address: 172.24.0.70
```
but this is failing:
```yaml
version: '3.7'
services:
  tool:
    container_name: tool
    hostname: tool
    image: repo/tool:latest      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    tmpfs:
      - /var/run
      - /var/cache  
    depends_on:
      - proxy
    environment:
      - SUHOMEDIR=${HOME}
    networks:
      local-net:
        ipv4_address: 172.24.0.70
```
(both gRPC FUSE and the old osxfs setting)

So `/var/run` seems to be "the problem". As i said; no problems with 2.3.8.0 before. Did i misuse the `tmpfs` option wrong, or did things change since 2.4.0.0?

I have updated the initial issue with my setup used: DD 2.4.0.0 stable on Catalina 10.15.7 (19H2) - Docker for Mac Version: 19.03.13, build 4484c46d9d
