### ISSUE TITLE
"docker-compose start" serviceX fails, except for initial up/start after Docker Desktop restart

### ISSUE THREAD

**Issue by turvas** [docker/for-mac#5000]
- [ x] I have tried with the latest version of my channel (Stable 2.4.0.0)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 4C2D703F-831E-4DFA-BF73-CEB20B332DF7/20201016113006

### Expected behavior
```
docker-compose up -d filebeat2
Removing filebeat
Recreating cae1619d8c97_filebeat ... done
```
### Actual behavior
```
docker-compose up -d filebeat2
Starting filebeat ... error
ERROR: for filebeat  Cannot start service filebeat: error while creating mount source path '/host_mnt/Users/changed/git/project/filebeat.docker.yml': mkdir /host_mnt/Users/changed/git/project/filebeat.docker.yml: file exists
```
### Information
  - Is it reproducible? YES, but not always, sometimes it takes some time (less than hr) or several start/stop cycles for happen
  - Is the problem new? YES
  - Did the problem appear with an update? not sure
  - A reproducible case if this is a bug, Dockerfiles FTW.
  - macOS Version: 10.14.6
  - docker-compose.yml : 
```
version: '3.1'
services:
  filebeat2:
    container_name: filebeat2
    image: docker.elastic.co/beats/filebeat:7.9.2
    user: root
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log
      - ./filebeat:/usr/share/filebeat/modules.d
```

### Diagnostic logs

```
Diagnose succeeded
Docker for Mac: version...  2.4.0.0
dig.zip uploaded
```

### Steps to reproduce the behavior
0. restart Docker Desktop (to succeed step 1.)
1. start or create service
```docker-compose up -d filebeat2```
2. spend some time.., and resrtart service (result is same if recreate with: up -d)
```
docker-compose stop filebeat
docker-compose start filebeat
```
