### ISSUE TITLE
Cannot override the specified file on rprivate's volumes

### ISSUE THREAD

**Issue by midoridge** [docker/for-mac#5053]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

I updated Docker Desktop for Max from 2.4.0.0 to 2.5.0.0 a few days ago.
After that, cannot override the specified file on rprivate's volumes.

Summary of docker-compose.yml is the following
```
version: '3'

services:
  app:
    volumes:
      - ./app/html:/var/www/html
      - ./app/env.dev:/var/www/html/.env
```

./app/html has .env file. 
Before updating Docker Desktop, it was override .env file by ./app/env.dev. But now cannot override it.

I checked docker-compose version of both 2.4.0.0 and 2.5.0.0. Both versions are the same version 1.27.4, build 40524192. 

### Information

  - macOS Version: 10.15.7 (19H2)

### Diagnostic logs

```
Docker for Mac: version 2.5.0.0

```

### Steps to reproduce the behavior

  1. Create base directory and .env file under the directory
```
$ mkdir -p app/html
$ touch app/html/.env
```
  2. create env.dev file
```
$ echo "TEST=TEST" > app/env.dev
```
  3. create docker-compose.yml
```
version: '3'

services:
  app:
    volumes:
      - ./app/html:/var/www/html
      - ./app/env.dev:/var/www/html/.env
```
  4. docker-compose up -d
```
$ docker-compose up -d
```
  5. connect to docker container and check file
```
$ docker-compose exec app ls -la /var/www/html/.env
$ docker-compose exec app cat /var/www/html/.env
```

**Comment by stephen-turner** [comment]
Hmmm, I can't reproduce this. I'm always seeing the proper dev version of the file.

Can you reproduce it with a simple `docker run -v` command, without using compose?

**Comment by midoridge** [comment]
@stephen-turner san,

Thank you for you reply.

> Can you reproduce it with a simple `docker run -v` command, without using compose?

I did it on docker-for-mac version 2.5.0.0 as the following.
It looks fine.

```
% docker run -v $(pwd)/html:/var/www/html -v $(pwd)/env.development:/var/www/html/.env -it app /bin/bash
  
# ls -la /var/www/html/.env
-rw-r--r-- 1 root root 3681 Oct 20 04:58 /var/www/html/.env
```

When I use docker-compose on docker-for-mac version 2.5.0.0, it didn't work.
Now I downgraded version 2.4.0.0 and using, it can work.

In other hand, I found the different between 2.4.0.0 and 2.5.0.0.

**docker version's output**
```
Client: Docker Engine - Community
 Cloud integration  0.1.18                  <=== 2.5.0.0 is 1.0.1
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false
```
* 2.4.0.0 :  Cloud integration  0.1.18
* 2.5.0.0 : Cloud integration  1.0.1
Other versions are same.

**docker-compose version's output**
all same

**docker inspect's output**
2.4.0.0 has the following parameters, but 2.5.0.0 doesn't have them. But it's only label. I'm not sure whether important or not.
```
[
    {
        "Config": {
            "Labels": {
                "com.docker.compose.config-hash": "9b2f5e15ff672a3bf7faf772110f0c2149e2e90e93e361120347bf909f1efe09",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "test",
                "com.docker.compose.project.config_files": "docker-compose-test.yml",
                "com.docker.compose.project.working_dir": "/Users/midoridge/work/docker/test",
                "com.docker.compose.service": "app",
                "com.docker.compose.version": "1.27.4",
                "desktop.docker.io/binds/0/Source": "/Users/midoridge/work/docker/test/app",
                "desktop.docker.io/binds/0/SourceKind": "hostFile",
                "desktop.docker.io/binds/0/Target": "/var/www/html",
                "desktop.docker.io/binds/1/Source": "/Users/midoridge/work/docker/test/app/env.dev",
                "desktop.docker.io/binds/1/SourceKind": "hostFile",
                "desktop.docker.io/binds/1/Target": "/var/www/html/.env"
            }
        },
    }
]
```

**Comment by noud-github** [comment]
I can confirm,  with `docker run -v` it works as expected:

```
root@8d726354d0b0:/# mount | grep grpcfuse
grpcfuse on /var/www type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
grpcfuse on /var/www/.env type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
````

but on multiple docker for mac 2.5.0.0 installs, the composer version is not working as expected.
docker inspect has all 5 mounts present in the docker-compose.yml: 

```   "Mounts": [
            {
                "Type": "bind",
                "Source": "/Users/user/docker/data/logs",
                "Destination": "/var/logs",
                "Mode": "delegated",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/Users/user/docker/config/dotenv",
                "Destination": "/var/www/.env",
                "Mode": "cached",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/Users/user/site",
                "Destination": "/var/www",
                "Mode": "cached",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/Users/user/docker/config/php.ini",
                "Destination": "/usr/local/etc/php/php.ini",
                "Mode": "cached",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/Users/user/docker/config/development.php",
                "Destination": "/var/www/config/environments/development.php",
                "Mode": "cached",
                "RW": true,
                "Propagation": "rprivate"
            }
```

but mount says only the 3 "base" once are mounted

```
root@50e5c73acf0d:/var/www/html# mount | grep grpc
grpcfuse on /var/logs type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
grpcfuse on /var/www type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
grpcfuse on /usr/local/etc/php/php.ini type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
root@50e5c73acf0d:/var/www/html#
```

**Comment by thaJeztah** [comment]
@noud-github are there any other changes between the `docker inspect` for the `docker run` and `docker-compose up` cases (perhaps in other areas, e.g. (`HostConfig.Binds`, `HostConfig.Mounts`, `HostConfig.Volumes`)?

Would it be possible for you to do a `diff` between the two variants? (OK to redact unrelated info)

**Comment by noud-github** [comment]
was running the 2 diff, you ask, than checked for the last time if the .env was the wrong one... and it is mounted.
and it suddenly works as expected....

```root@68d3ceb91dad:/var/www# mount | grep grp
grpcfuse on /var/www type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
grpcfuse on /var/www/.env type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
grpcfuse on /etc/nginx/conf.d/site.conf type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
grpcfuse on /var/www/config/environments/development.php type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
```
main difference updated Mac to "Big Sur" 
second  disabled gRPC FUSE  (for normal running) and enabled it again for this test....

**Comment by noud-github** [comment]
I still have the issue, let me explain:
we have a compose with 5 containers. 
a nginx container and a "custom container", both mounting the same (almost) files. (one more on the "custom" )
first: The above comment covers the Nginx one where it now is working (thought I tested it failing two before) 
second: on our custom container, it is failing.

tp put is sort
So I have one composer file mounting files in one container it is working as expected and on a other container the manting basically the same files. this issue is experienced.

will do a diff on the inspect later.

**Comment by stephen-turner** [comment]
@noud-github Are you saying that everything is good if you only have one container in your compose file, but if you have two or more it breaks?

@midoridge Your original example only had one container, are you seeing the bug with only one container, or do you need a second container to show the bug?

**Comment by aless673** [comment]
I have the same issue with Docker Desktop > 2.3

It happens with multiple containers :

```
version: '3.4'
  services:
    app:
      build: ./docker/symfony
      volumes:
        - ./source:/var/www/html
        - ./docker/.env.dev:/var/www/html/.env.local
    app2:
      build: ./docker/symfony
      volumes:
        - ./source:/var/www/html
        - ./docker/.env.dev:/var/www/html/.env.local
```

=> .env.local is empty

Otherwise with Docker Desktop 2.3.0.5 it works well

**Comment by stephen-turner** [comment]
Thanks @aless673. So just to confirm, for you it only happens with multiple containers, not a single container?

**Comment by noud-github** [comment]
Yes I can confirm that, two. only with multiple, not a single container.

**Comment by stephen-turner** [comment]
OK, thanks, that's a good clue. It looks like the original report was oversimplified. We'll try again to reproduce it.

**Comment by noud-github** [comment]
Maybe abundant but with multiple containers the issue occurs in the second and up (containers)not the first one. 
so keep in mind there was one GOOD container in the tests we did.  

we tested with docker desktop 2.5.0.X

**Comment by aless673** [comment]
> Hmmm, unfortunately I can't reproduce it even with two containers. Both containers' file systems have the extra file in my experiments.

File exists but is empty

**Comment by stephen-turner** [comment]
Yes, but I looked at the contents too and it has the correct contents.

**Comment by stephen-turner** [comment]
It's possible that there's a race condition that I'm not triggering. That might also explain why more people haven't found this.

**Comment by noud-github** [comment]
do jou think that condation  is triggered by some thing in the compose file or some where else.

**Comment by stephen-turner** [comment]
Possibly, but more likely it's just something random in the order of events. It might be worse on a fast computer, or a slow computer, or something.

**Comment by midoridge** [comment]
@stephen-turner 
Sorry for late reply.

> Your original example only had one container, are you seeing the bug with only one container, or do you need a second container to show the bug?

I did three containers first, it didn't work. After that, I tested only container, also didn't work.
So, I think for example one container is easy to understand, and posted here.

**Comment by if-kenn** [comment]
I am seeing this with Docker for Mac 3.0.3 with 16 containers running, when I simplify to 1 container I do not see the issue. Turning off gRPC FUSE fixes the issue.

**Comment by if-kenn** [comment]
I have been able to consistently repeat this reducing this down to 6 containers.

```yml
version: '3.7'

volumes:
  db-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":$FULCRUM_HOME_DC/fulcrum/var/lib/mysql"
  web-sites:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":$FULCRUM_HOME_DC/fulcrum/sites"
  php7.3-log:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":$FULCRUM_HOME_DC/fulcrum/var/log/php7.3"
  nginx-log:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":$FULCRUM_HOME_DC/fulcrum/var/log/nginx"

services:
  # db-data is exported twice for compatibility w debian & alpine
  mariadb:
    container_name: mariadb
    image: fulcrum/mariadb:latest
    network_mode: bridge
    volumes:
     - $FULCRUM_HOME_DC/fulcrum/etc/mysql:/etc/mysql:ro
     - $FULCRUM_HOME_DC/fulcrum/var/log/mariadb:/var/log
     - db-data:/var/lib/mysql
     - db-data:/data/mysql
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    dns: $FULCRUM_HOST_IP

  php7.3:
    container_name: php7.3
    image: fulcrum/php7.3-drush8
    network_mode: bridge
    volumes:
      - $FULCRUM_HOME_DC/fulcrum/etc/php7.3:/etc/php7:ro
      - php7.3-log:/var/log/php7
      - $FULCRUM_HOME_DC/fulcrum/etc/fulcrum/php/fulcrum.php:/fulcrum.php:ro
      - $FULCRUM_HOME_DC/fulcrum/etc/fulcrum/php/fulcrum.php:/fulcrum/fulcrum.php:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/private_files:/private
      - web-sites:/var/www/html
    ports:
      - "9073:9073"
    dns: $FULCRUM_HOST_IP
    cap_add:
      - SYS_PTRACE

  nginx:
    container_name: nginx
    image: fulcrum/nginx:1.19
    network_mode: bridge
    volumes:
      - $FULCRUM_HOME_DC/fulcrum/etc/nginx:/etc/nginx
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/nginx/resolver.conf:/etc/nginx/conf.d/resolver.conf:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/nginx/fulcrum/fulcrum_proxypass.conf:/etc/nginx/fulcrum/fulcrum_proxypass.conf
      - nginx-log:/var/log
      - web-sites:/var/www/html:ro
    ports:
      - "8080:80"
    dns: $FULCRUM_HOST_IP

  varnish:
    container_name: varnish
    image: fulcrum/varnish:6.4
    network_mode: bridge
    volumes:
      - $FULCRUM_HOME_DC/fulcrum/etc/varnish:/etc/varnish
      - $FULCRUM_HOME_DC/fulcrum/etc/varnish/backends-webs-decoupled.vcl:/etc/varnish/backends-webs.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/etc/varnish/include/audience-public.vcl:/etc/varnish/include/audience.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/etc/varnish/include/x-forward-for-localdev.vcl:/etc/varnish/include/x-forward-for.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/etc/varnish/include/beresp-ttl-dev.vcl:/etc/varnish/include/beresp-ttl.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/etc/varnish/include/cache-tag-debug.vcl:/etc/varnish/include/cache-tag-remove.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/var/log/varnish:/var/log
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/varnish/include/vcl_backend_response_tail.vcl:/etc/varnish/include/vcl_backend_response_tail.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/varnish/include/vcl_deliver_tail.vcl:/etc/varnish/include/vcl_deliver_tail.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/varnish/include/vcl_hash_tail.vcl:/etc/varnish/include/vcl_hash_tail.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/varnish/include/vcl_hit_tail.vcl:/etc/varnish/include/vcl_hit_tail.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/varnish/include/vcl_recv_tail.vcl:/etc/varnish/include/vcl_recv_tail.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/varnish/include/vcl_miss_tail.vcl:/etc/varnish/include/vcl_miss_tail.vcl:ro
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/varnish/include/vcl_pass_tail.vcl:/etc/varnish/include/vcl_pass_tail.vcl:ro
    command: -F -P /var/run/varnish.pid -a :6081,PROXY -f /etc/varnish/default.vcl -S /etc/varnish/secret -T 0.0.0.0:6082 -t 120 -s malloc,128M -p workspace_backend=131072 -p http_resp_hdr_len=65536 -p http_resp_size=98304
    ports:
      - "6081:6081"
      - "6082:6082"
    dns: $FULCRUM_HOST_IP

  # 4433 is for testing, bypass varnish on TLS
  haproxy:
    container_name: haproxy
    image: fulcrum/haproxy:1.8
    network_mode: bridge
    volumes:
      - $FULCRUM_HOME_DC/fulcrum/etc/haproxy:/etc/haproxy
      - $FULCRUM_HOME_DC/fulcrum/etc/certs.d:/etc/certs.d:ro
      - $FULCRUM_HOME_DC/fulcrum/var/log/haproxy:/var/log
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/haproxy/local-dev.cfg:/etc/haproxy/haproxy.cfg:ro
    ports:
      - "80:80"
      - "443:443"
      - "4080:4080"
      - "4433:4433"
      - "5080:5080"
      - "1936:1936"
    depends_on:
      - dnsmasq
    dns: $FULCRUM_HOST_IP

  dnsmasq:
    container_name: dnsmasq
    image: fulcrum/dnsmasq
    network_mode: bridge
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - $FULCRUM_HOME_DC/fulcrum/etc/dnsmasq:/etc/dnsmasq
      - $FULCRUM_HOME_DC/fulcrum/var/fulcrum/hinge-config/etc/dnsmasq/ifdev.conf:/etc/dnsmasq/ifdev.conf:ro
    cap_add:
      - NET_ADMIN
```
