### ISSUE TITLE
High CPU usage by com.hyperkit.docker, above 20% with no containers running 

### ISSUE THREAD

**Issue by rabkins** [docker/for-mac#5070]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4DC48EB2-7B74-4A83-82EC-93F9741B76C3/20201116103107

### Information

  - macOS Version: 11.0.1

### Diagnostic logs

```
Docker for Mac: 2.5.0.1 stable
i9 2,3 GHz
```

### Steps to reproduce the behavior

  1. Install Docker
  2. Run Docker

**Comment by stephen-turner** [comment]
@rabkins Do you have Kubernetes enabled? We know that has some CPU load.

**Comment by ebriney** [comment]
@rabkins : In the diagnostic you provided, you have 4 running containers for 12% CPU which seems acceptable

**Comment by back-2-95** [comment]
I got this too.

- clean install of Big Sur
- Docker for Mac 2.5.0.1
- checked with 6 containers running (all of them had barely any cpu usage)
- com.docker.hyperkit is steady at 18-40% CPU

My Diagnostics ID: fa766d86-8e58-4125-b7fa-f43e69beb1f8/20201116185213

**Comment by rabkins** [comment]
> @rabkins : In the diagnostic you provided, you have 4 running containers for 12% CPU which seems acceptable

This is diagnostics w/o any container running 4DC48EB2-7B74-4A83-82EC-93F9741B76C3/20201117055954
 Kubernetes is disabled on my.

**Comment by kyloon** [comment]
I'm seeing the same high CPU usage behavior too without any container running and Kubernetes disabled running Docker for mac 2.5.0.1 on macOS Big Sur 11.0.1.

Diagnostic ID: 599659F8-1AF5-4EFC-A50B-8685A5A153F1/20201117071741

**Comment by slash686** [comment]
Same behavior - CPU usage is around 25% when no containers are running.

macOS Big Sur 11.0.1
MacBook Pro (16-inch, 2019)
2,3 GHz 8‑core Intel Core i9
16Gb

Diagnostic ID: 99E9079C-E84E-4D6F-9452-C57B91368BD6/20201117120837

**Comment by infolock** [comment]
This is the same issue reported here in [https://github.com/docker/for-mac/issues/4994](https://github.com/docker/for-mac/issues/4994).

Also note that the energy impact issue is also still there.   The only way to make it stop draining the battery on my laptop (while the power cable is plugged in!) is to either set the CPU cores down to 1 or just exit docker until the laptop can charge to 100% and try it again.   Very frustrating.

![Screen Shot 2020-11-17 at 11 08 32 PM](https://user-images.githubusercontent.com/808850/99482431-d9d5d680-2929-11eb-87af-8fedc71dc20e.png)

**Comment by infolock** [comment]
The next closest app that has this amount of Energy Impact is Chrome - and its energy impact (with over 20 tabs opened) is `10.2` lol

**Comment by JustinTArthur** [comment]
I see this on Mojave with 2.5.0.1 so it's not just Big Sur that's affected.

**Comment by robertrossmann** [comment]
Here is my diagnostic ID with `hyperkit` consuming around 20% CPU with no containers running and occasionally jumping to ~40% CPU with Redis & Postgres v9.6 containers running after receiving load from a test suite.

*Diagnostic ID*: `70E7E5DC-537D-45A7-A195-C291A623CB2A/20201119085501`

Here is a sample of the `hyperkit` process captured in macOS 11. There is a weirdly deep stack calling `camlLwt_main__run_loop_129`, see the screenshots. This looks highly unhealthy... 🤔 

![deep stack trace - start](https://user-images.githubusercontent.com/3058150/99645559-abeab200-2a4f-11eb-89ab-0e444611287f.png)
![deep stack trace - end](https://user-images.githubusercontent.com/3058150/99645576-af7e3900-2a4f-11eb-89fe-ae5f22543454.png)
[Sample of com.docker.hyperkit.txt](https://github.com/docker/for-mac/files/5565657/Sample.of.com.docker.hyperkit.txt)

**Comment by robinharms** [comment]
I have the same problem, running Catalina (pre big sur)

15-40% CPU usage without any running containers. No Kubernetes.

**Comment by N1gma** [comment]
Does some even working on this? Its literally impossible to use docker on mac - getting 300% CPU usage.

**Comment by Andorxor** [comment]
I've been using kde neon linux for a year now and never faced any issues with docker. Some folks persuaded me to switch to the shiny mac  :) 70% of battery usage is due to docker. Most of the time with no containers.

**Comment by stephen-turner** [comment]
Yes, we're working on this. We made a lot of improvements to the CPU recently, but it seems to have regressed again. We're not sure why: we suspect it's something in one of our upstream dependencies that has changed, but we're still looking into it.

**Comment by ptica** [comment]
macOS Catalina 10.15.7
mac mini 6 core i5
8 gb
no container running, ±17-20% for com.docker.hyperkit

diagnostics uploaded:
F962E0A2-20E3-4F3A-B9F4-B3CC68973CE6/20201123163645

**Comment by eugene-s** [comment]
macOS BigSur 11.0.1
MacBook Pro 13 core i5 2020
16 GB
no container running, ~30% CPU loading

**Comment by jahpola** [comment]
macOS Big Sur 11.0.1
MacBook Pro 16 i9 2019
16GB
No containers running, 10-20% cpu load

Diag id: 8A0107F8-1DD8-4D19-A714-53CED7C11B38/20201125204014

**Comment by stephen-turner** [comment]
Update: We've pinpointed this to the new Linux kernel we took between 2.4 and 2.5. We see the CPU load of a supposedly idle system double across that boundary.

This conversation is currently going on in two tickets. I'm going to combine them by closing this one in favour of #5044. Please follow that ticket for updates. Thanks.

**Comment by tomchapin** [comment]
My battery keeps slowly draining all day even when it is plugged in, often running completely out of battery and dying before I even reach 5 PM. The only solution that worked was to kill programs that were using excess energy (such as Docker).

I finally called Apple support about the issue and they revealed to me that the new macbook pro laptops are designed to pull energy from the battery whenever the CPU needs extra power. So the charger only provides 96 watts, but the laptop can boost to higher wattage usage when needed, and when it does so, it pulls this extra wattage from the battery.
Unfortunately, they told me that this behavior was automatic and there was no way to disable it.

I did a little bit of digging, however, and I discovered a tool called “Turbo Boost Switcher” that allows you to toggle off Turbo Boost on your mac. http://tbswitcher.rugarciap.com/

The moment I disabled Turbo Boost, my macbook battery amperage draw went from -187 (slowly draining the battery) up to +138 (slowly charging the battery).

I believe I have finally fixed the problem! Unfortunately, this means I have to throttle my laptop so it doesn’t run as fast, which is annoying… but at least it shouldn’t die on me anymore, hopefully…

**Comment by NaeemSohrabi** [comment]
Hi,
i have the same problem of high cpu usage abut 320 to 350 %
OS : Big Sur 11.1.
Docker: 3.0.2

docker-compose.yml 
```
version: "3.2"

services:
  node:
    build:
      dockerfile: node_watch.Dockerfile
      context: ./logger
      args:
        REGISTRY_URI: ${REGISTRY_URI}
    volumes:
      - ./logger/public/:/var/www/logger/public/
      - ./logger/resources/:/var/www/logger/resources/
      # - ./logger/node_modules:/var/www/logger/node_modules
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/timezone:/etc/timezone:ro
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/localtime:/etc/localtime:ro
    container_name: node
    networks:
      - mavara-network

  laravel_echo_server:
    build:
      dockerfile: Dockerfile
      context: ./echo
      args:
        REGISTRY_URI: ${REGISTRY_URI}
    restart: unless-stopped
    container_name: laravel_echo_server
    volumes:
      - ./echo/laravel-echo-server.json:/opt/echo/laravel-echo-server.json
      - ./echo/certs:/opt/echo/certs/
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/timezone:/etc/timezone:ro
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/localtime:/etc/localtime:ro

    ports:
      - 6001:6001
    depends_on:
      - php
      - redis
    networks:
      - mavara-network

  mysql:
    image: ${REGISTRY_URI}/mysql:5.7
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/data:/var/lib/mysql
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/timezone:/etc/timezone:ro
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/localtime:/etc/localtime:ro
    env_file: ./mysql/.env
    networks:
      - mavara-network

  nginx:
    image: ${REGISTRY_URI}/nginx:1.19.2
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logger/:/var/www/logger
      - ./nginx/cert:/etc/nginx/certs/
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/timezone:/etc/timezone:ro
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
    networks:
      - mavara-network

  redis:
    image: ${REGISTRY_URI}/redis:6.0.8
    container_name: redis
    restart: unless-stopped
    networks:
      - mavara-network
    volumes:
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/timezone:/etc/timezone:ro
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/localtime:/etc/localtime:ro

  php:
    restart: unless-stopped
    build:
      dockerfile: php_dev.Dockerfile
      context: ./logger
      args:
        REGISTRY_URI: ${REGISTRY_URI}
    container_name: php
    hostname: php
    environment:
      SOURCE_DIR: ${SOURCE_DIR}
      HOST_USER: ${HOST_USER}
      HOST_ADDR_NAME: ${HOST_ADDR_NAME}
    volumes:
      - ./logger/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./logger/:/var/www/logger/
      - ~/.ssh/:/root/.ssh/
      - /etc/sudoers:/var/www/logger/sudoers
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/timezone:/etc/timezone:ro
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/localtime:/etc/localtime:ro
    env_file:
      - ./logger/.env.dev
    depends_on:
      - mysql
      - redis
    networks:
      - mavara-network

  snmp-server:
    build:
      dockerfile: Dockerfile
      context: ./snmp
      args:
        REGISTRY_URI: ${REGISTRY_URI}
    restart: unless-stopped
    container_name: snmp-server
    volumes:
      - /proc:/proc
      - ./snmp/snmpd.conf:/etc/snmp/snmpd.conf
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/timezone:/etc/timezone:ro
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/localtime:/etc/localtime:ro
    networks:
      - mavara-network
  reporter:
    restart: unless-stopped
    build:
      context: ./pdf-reporter
      args:
        REGISTRY_URI: ${REGISTRY_URI}
    container_name: reporter
    networks:
      - mavara-network
# Docker Networks
networks:
  mavara-network:
    driver: bridge

```
