### ISSUE TITLE
All containers hang

### ISSUE THREAD

**Issue by Nuru** [docker/for-mac#5081]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7DDDF979-417F-442C-B930-719FC131249A/20201122020444

### Actual behavior

While running several containers running interactive shells (`-it`) and host volumes mounted, all of them hung. I could not exit them from within the container by exiting the shell or outside by using the Docker dashboard to kill the containers.

### Information
Never saw this before, not reproducible

  - macOS Version:  10.15.7 (19H15)
  - Docker Desktop version 2.5.0.1 (49550)

I had to quit Docker desktop itself to force-quit all the containers. When I did, they all spit out the same error message:
```
ERRO[25697] error waiting for container: invalid character 'u' looking for beginning of value 
```
While the error message was the same, even though the containers were running different distributions of Linux, the number inside the brackets was different for each container.

**Comment by Nuru** [comment]
Happened again with Docker Desktop Community 3.0.1
```
ERRO[0041] error waiting for container: invalid character 'u' looking for beginning of value
```

**Comment by kerak19** [comment]
Happens to me too, the container hangs and the only way to kill the command is to kill the docker

Error message
```sh
ERRO[2894] error waiting for container: invalid character 'u' looking for beginning of value
```

Docker version
```sh
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:55:43 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

OS version

```sh
ProductName:	macOS
ProductVersion:	11.0.1
BuildVersion:	20B50
```

**Comment by lorenzoranucci** [comment]
It happens to me too, containers hang and are unresponsive to stop signals. It seems to be "solved" by turning off the experimental features and/or removing the old container image.

**Comment by geoff-smith** [comment]
I have the same issue (in 3.0.2). For me, it is not solved by rebuilding the image.

**Comment by qiujiangkun** [comment]
Happens to me too, even after resetting the whole docker and losing all my testing data

**Comment by kerak19** [comment]
It doesn't happen for me anymore.

Docker version:
```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

OS version:
```
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```

I also have both experimental features turned on

**Comment by koppor** [comment]
Happens here while running a Docker container with "some" load

    time="2021-04-13T18:11:33+02:00" level=error msg="error waiting for container: invalid character 'u' looking for beginning of value"

```yaml
Docker version 20.10.5, build 55c4c88
Windows: 1809 (Build 17763.1817)

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.36GiB
 Name: docker-desktop
 ID: ESQX:4PUP:4V3D:JPN3:WEUA:I4ID:UQJF:2C4A:4MN6:X7OC:R23G:QUD4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

Oliver Kopp <oliver.kopp@mbition.io>, Mercedes-Benz AG, on behalf of MBition GmbH
