### ISSUE TITLE
2379 and 2380 ports can't be binded to on Mac when Kubernetes is enabled

### ISSUE THREAD

**Issue by m0un10** [docker/for-mac#5089]
Docker Desktop on Mac with Kubernetes should allow for a local Etcd to run on 2379 and 2380. But it doesn't so there is no easy way to run Etcd locally at least that I am aware of... Please let me know if there is any workaround available.

I suspect it's a similar issue to [this one](https://github.com/docker/for-mac/issues/3522)

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 963FBE16-8190-4611-BE3F-7C8CAA168CAD/20201130024416
  - The above diagnostics was taken was Kubernetes was not enabled. i.e. when things were working. I'm happy to provide an additional diagnostics record after enabling Kubernetes if it is useful.

### Expected behavior

Given I am on Mac 10.15.7
And I have Kubernetes enabled
And I have no ports running on 2379 or 2380
And I have the following docker-compose.yml
```
version: '2.1'
services:
    api:
        image: 'bitnami/etcd:latest'
        hostname: etcd-server
        ports:
         - '2379:2379'
         - '2380:2380'
```
When I run `docker-compose up`
Then it is successful

### Actual behavior

It displays the following error

```
Error starting userland proxy: listen tcp 0.0.0.0:2380: bind: address already in use
```

### Information

This is reproducible.
macOS Version: 10.15.7

### Diagnostic logs

Diagnostics ID is included at the top of this ticket.

### Steps to reproduce the behavior

Use Mac 10.15.7 and Docker Desktop
Enable Kubernetes
Ensure no ports running on 2379 or 2380
Use the following docker-compose.yml
```
version: '2.1'
services:
    api:
        image: 'bitnami/etcd:latest'
        hostname: etcd-server
        ports:
         - '2379:2379'
         - '2380:2380'
```
Run `docker-compose up`
Observe the error
