### ISSUE TITLE
CPU Usage Still High on Docker 3.0.0

### ISSUE THREAD

**Issue by pjjanak** [docker/for-mac#5116]
Seems like the issue described in #5044 is persisting even after the latest upgrade. I have removed unneeded shares (as mentioned in #3499) but that has not fixed the problem.

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 5F7920E2-CFFC-44A8-9509-AE9C0DDF6CE2/20201210183007

### Expected behavior
com.docker.hyperkit takes up a normal amount of CPU

### Actual behavior
com.docker.hyperkit is constantly running at > 100% CPU

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? - Yes
  - Is the problem new? - No (probably not given the amount of times this has been reported)
  - Did the problem appear with an update? - Yes after the 3.0.0 update the problem resurfaced
  - macOS Version: 10.15.7

### Steps to reproduce the behavior

  1. Start docker

**Comment by ricristian** [comment]
Now it's worst 

<img width="1792" alt="Screenshot 2020-12-10 at 22 38 24" src="https://user-images.githubusercontent.com/6584521/101827169-a1947300-3b38-11eb-8374-9cfc9931979e.png">

OS: Catalina 10.15.7
Diagnostic ID: 152E874F-49F1-48A0-9A4E-30D9B88D56EA/20201210203925
File sharing is not working anymore if gRPC is enabled.

Settings: 
Experimental: all disabled 

docker-compose.yml 
```
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    volumes:
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

```

**Comment by stephen-turner** [comment]
@pjjanak @ricristian Can you clarify whether you're also seeing high CPU load when no containers and no Kubernetes are running, or only when there are running containers? Those would likely have different causes. Thanks.

**Comment by ricristian** [comment]
@stephen-turner I can confirm that by default when all containers are stopped the load is small under 10% 
When I'm starting containers with docker-compose ( in my case ) for 10-15 minutes the load increases to between 100-500% and after those 10-15 minutes the load decreases back to 10% which is really great. 
So the high load appears only when I'm trying to start containers and after that load decreases to more than decent

**Comment by stephen-turner** [comment]
@ricristian Thanks, that's very interesting. I'm still surprised the images take quite so long to download: are they enormous?

**Comment by ricristian** [comment]
@stephen-turner it's highly probable that it is caused by my network ... sometimes bandwidth is not that high ...

**Comment by pjjanak** [comment]
@stephen-turner - I noticed this right after docker restarted after update, so no containers were running. I also don't use kubernetes on this machine, so don't have any running on here ever. I will say that things have quieted down _a little_ since reporting, but my usage is still hovering around 70-80% with no containers running.

**Comment by osi** [comment]
I'm seeing the same observation as https://github.com/docker/for-mac/issues/5070#issuecomment-730235895  w/3.0.1 on Big Sur, 11.0.1 (20B50)

**Comment by pposca** [comment]
I have the same issue, but it only happens when there is a volume bound:

- Container with volume bounded: ~20% CPU usage
- Same container without volume bounded: ~4% CPU usage

**Comment by dawi** [comment]
After update to 3.0.0 the cpu usage is around 80 % without running any containers.
With running containers it's constantly over 200 %.

**Comment by OzoTek** [comment]
Having the same issue, upgraded to v3 and CPU got back to >200% usage.
Diagnostic ID: `74807466-79B8-4824-8035-608D77708609/20201214144155`

Version 2.3 is the latest version that doesn't have this issue for me.

**Comment by Patrick-Remy** [comment]
HyperKit takes about 200% CPU (no K8s) on 3.0.1 without any containers running – exactly the same as at 2.5.0.

**Comment by Ky6uk** [comment]
Yep, it's back, but not all the time as it was on `v2.5`. Sometimes it's eating all attached CPUs, sometimes not. I have no idea about the condition, it looks random at the moment.

`C1E3D580-6312-45F9-8E7F-B7D86211FCF9/20201215122501`

**Comment by YotillaMarco** [comment]
I habe the same problem. ~170% CPU usage without any container running. Version 3.0.1 on macOS 10.15.7

**Comment by cyberatz** [comment]
Similar issue here. 
I stopped all container but one - watchtower - which is set to run at 15min intervals. 

CPU usage of docker:
![image](https://user-images.githubusercontent.com/2226414/102593633-6801d000-4115-11eb-84b1-4ca0ccb8899a.png)

CPU usage of the container:
![image](https://user-images.githubusercontent.com/2226414/102593746-88318f00-4115-11eb-8542-03cc6276e0fb.png)

These are the hyper kit process stats:
![image](https://user-images.githubusercontent.com/2226414/102593907-caf36700-4115-11eb-8072-0f564f3aa997.png)

My gut feeling currently is that there's something running aggressively inside the docker created VM (~/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw) that is eating up cycles - but this is just a hypothesis at the moment and I've no idea how to test that theory just yet. 

Diagnostic ID:
55ADF900-D456-4893-BC2B-812E6F6622DD/20201218084210

**Comment by n00bvn** [comment]
I've just updated to the latest version which is `3.0.2` but hyperkit cpu usage still at more than 200%.
I'm using Big Sur 11.1.

**Comment by NaeemSohrabi** [comment]
Hi,
i have the same problem of high cpu usage abut 320 to 350
OS : Big Sur
Docker: 3.0.2

docker-compose.yml 
```
version: "3.2"

services:
  node:
    build:
      dockerfile: node_watch.Dockerfile
      context: ./logger
      args:
        REGISTRY_URI: ${REGISTRY_URI}
    volumes:
      - ./logger/public/:/var/www/logger/public/
      - ./logger/resources/:/var/www/logger/resources/
      # - ./logger/node_modules:/var/www/logger/node_modules
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/timezone:/etc/timezone:ro
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/localtime:/etc/localtime:ro
    container_name: node
    networks:
      - mavara-network

  laravel_echo_server:
    build:
      dockerfile: Dockerfile
      context: ./echo
      args:
        REGISTRY_URI: ${REGISTRY_URI}
    restart: unless-stopped
    container_name: laravel_echo_server
    volumes:
      - ./echo/laravel-echo-server.json:/opt/echo/laravel-echo-server.json
      - ./echo/certs:/opt/echo/certs/
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/timezone:/etc/timezone:ro
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/localtime:/etc/localtime:ro

    ports:
      - 6001:6001
    depends_on:
      - php
      - redis
    networks:
      - mavara-network

  mysql:
    image: ${REGISTRY_URI}/mysql:5.7
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/data:/var/lib/mysql
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/timezone:/etc/timezone:ro
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/localtime:/etc/localtime:ro
    env_file: ./mysql/.env
    networks:
      - mavara-network

  nginx:
    image: ${REGISTRY_URI}/nginx:1.19.2
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logger/:/var/www/logger
      - ./nginx/cert:/etc/nginx/certs/
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/timezone:/etc/timezone:ro
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
    networks:
      - mavara-network

  redis:
    image: ${REGISTRY_URI}/redis:6.0.8
    container_name: redis
    restart: unless-stopped
    networks:
      - mavara-network
    volumes:
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/timezone:/etc/timezone:ro
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/localtime:/etc/localtime:ro

  php:
    restart: unless-stopped
    build:
      dockerfile: php_dev.Dockerfile
      context: ./logger
      args:
        REGISTRY_URI: ${REGISTRY_URI}
    container_name: php
    hostname: php
    environment:
      SOURCE_DIR: ${SOURCE_DIR}
      HOST_USER: ${HOST_USER}
      HOST_ADDR_NAME: ${HOST_ADDR_NAME}
    volumes:
      - ./logger/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./logger/:/var/www/logger/
      - ~/.ssh/:/root/.ssh/
      - /etc/sudoers:/var/www/logger/sudoers
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/timezone:/etc/timezone:ro
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/localtime:/etc/localtime:ro
    env_file:
      - ./logger/.env.dev
    depends_on:
      - mysql
      - redis
    networks:
      - mavara-network

  snmp-server:
    build:
      dockerfile: Dockerfile
      context: ./snmp
      args:
        REGISTRY_URI: ${REGISTRY_URI}
    restart: unless-stopped
    container_name: snmp-server
    volumes:
      - /proc:/proc
      - ./snmp/snmpd.conf:/etc/snmp/snmpd.conf
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/timezone:/etc/timezone:ro
      - /Users/naiemsohrabi/Documents/Project/Docker/Mavara/localtime:/etc/localtime:ro
    networks:
      - mavara-network
  reporter:
    restart: unless-stopped
    build:
      context: ./pdf-reporter
      args:
        REGISTRY_URI: ${REGISTRY_URI}
    container_name: reporter
    networks:
      - mavara-network
# Docker Networks
networks:
  mavara-network:
    driver: bridge

```
