### ISSUE TITLE
How to downgrade to Docker for Mac 2.5.0.1?

### ISSUE THREAD

**Issue by jdahdah** [docker/for-mac#5117]
The [download page](https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-community-2501) does not offer a direct link to Docker for Mac 2.5.01 like all the other older versions do, it instead goes to Docker Hub which in turn downloads 3.0.0. I need to downgrade to 2.5.0.1 as I am running Big Sur and 3.0.0 is perpetually stuck on "Starting up".

**Comment by yemster** [comment]
+1 seeing the same and unable to find a link either.

**Comment by jcushman** [comment]
Looks like it's this:

https://desktop.docker.com/mac/stable/49550/Docker.dmg

**Comment by jdahdah** [comment]
@jcushman Yep, that's it. Thanks!

**Comment by visualex** [comment]
On Catalina and 3.0.0 is perpetually stuck on "Starting up" as well.

**Comment by FraGoTe** [comment]
On MacBigSur the same it gets stuck:
![image](https://user-images.githubusercontent.com/1095778/101832219-0df57f00-3b05-11eb-87ca-af9fab46fcf2.png)

**Comment by chenkai0520** [comment]
一样的问题，手贱点了更新

```shell
ERROR: for postgis  Cannot start service postgis: Mounts denied: approving /Users/chenkai/Documents/docker/postgres_postgis: file does not exist
```
yaml

```
  postgis:
    container_name: postgis
    image: postgis/postgis:13-master
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - localhost
    ports:
      - "5432:5432"
    volumes:
      - /Users/chenkai/Documents/docker/postgres_postgis:/var/lib/postgresql/data
    restart: always
```
