### ISSUE TITLE
with gRPC-fuse on: containers are remounted when other services are started or restarted

### ISSUE THREAD

**Issue by qhenkart** [docker/for-mac#5124]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:88536E2D-D1AC-4794-B87F-EA52F09784B0/20201212004740

### Expected behavior

I can run multiple services using docker-compose on my local machine. It starts fast, uses very little memory, and volumes are properly mounted. (i.e. anything < 2.4)

### Actual behavior

with gRPC-fuse I cannot run many services, it consumes the max memory possible and times out before it can stabilize. Without gRPC-fuse, everything works as expected, except volumes are not mounted properly and updates in the host do not propagate to the container [(there are issues already for this last point](https://github.com/docker/for-mac/issues/5046) )

### Information

  - macOS Version: 11.0.1

### Diagnostic logs
 
I've included the diagnostic ID, I don't see "Diagnose & Feedback" in the menu, please tell me how I can provide better or more information
```
Docker for Mac: 3.0

```

### Steps to reproduce the behavior

I am going to walk you through to be able to reproduce the behavior I have been noticing. 

Here is a simple docker file that uses a common/simple go-watcher on golang1.14, The watcher isn't required, but it really easily illustrates all of the problems occurring here 

```
FROM golang:1.14-stretch
RUN go get github.com/cespare/reflex
COPY reflex.conf /
```
now build the image and tag it. `golang:1.14-watcher`

now let's create the docker-compose.yml file

I have created an ultra simple server for this example. This server literally does nothing, but that's not the point. please `git clone https://github.com/qhenkart/docker-example to $GOPATH/src/github.com/qhenkart/docker-example`
and again
`git clone https://github.com/qhenkart/docker-example to $GOPATH/src/github.com/qhenkart/docker-example2`

at the base of your go path, let's make this docker-compose.yml file
```
service1:
    image: golang:1.14-watcher
    command: reflex --verbose -r '(\.go$$|go\.mod)'  -s -- go run main.go
    working_dir: /go/src/github.com/qhenkart/docker-example
    volumes:
      - ./go/src/github.com/qhenkart/docker-example:/go/src/github.com/qhenkart/docker-example

  service2:
    image: golang:1.14-watcher
    command: reflex --verbose -r '(\.go$$|go\.mod)' -s -- go run main.go
    working_dir: /go/src/github.com/qhenkart/docker-example2
    volumes:
      - ./go/src/github.com/qhenkart/docker-example2:/go/src/github.com/qhenkart/docker-example2

```
okay we're ready!
**Scenario 1**
with gRPC-fuse there is a major crossover between services which causes a massive slowdown, memory leak and if there are many services, a downright failure. Using gRPC-fuse over the last few weeks has destroyed my battery life and productivity. But with this example, we will see why very easily

Let's make sure that the defaults match gRPC-fuse is turned on and buildkit is turned on 

open up 2 terminal windows. 
terminal 1:
docker-compose up service1
wait for it to say "service started"

terminal 2:
docker-compose up service2

you will notice in terminal 1 the following 
```

service1_1  | [00] Starting service
service1_1  | [00] service started
service1_1  | [info] fsnotify event: "./main.go": REMOVE.    **Here it unmounted every file (in this case just 1) causing the watcher to reset twice**
service1_1  | [00] Killing service
service1_1  | [00] ^Csignal: interrupt
service1_1  | [00] Starting service
service1_1  | [00] service started
```
In the end, both services are up and available. However, starting service #2 should not remount/restart service #1 . Multiply this by 20 services and add a large file structure to each, and you have a broken system that times out and uses too many resources before it can stabilize

**Scenario 2**
But since I have you (I hope I still have you), let's showcase what's going on in https://github.com/docker/for-mac/issues/5046

Simply turn off gRPC-fuse, and modify the main.go file. You will notice that starting or restarting service #2 does not affect service #1 (yay).... but you will also notice the changes are not updating into the container and a docker-compose restart is required every time a change is made to update the container

Let me know if there is anything I can do to better explain the issue here
