### ISSUE TITLE
Docker Desktop 3.0.2 fails to mount volumes with (overlapping?) mounts, breaks ddev

### ISSUE THREAD

**Issue by rfay** [docker/for-mac#5157]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics 
  - Diagnostics ID: 4878CE31-EDDB-4988-A949-52FEC38CFC79/20201219035944

### Expected behavior

For years prior to Docker Desktop for Mac 3.0.2, the following docker-compose worked fine (and I reinstalled Docker Desktop 3.0.1 to test it). (This is a stripped-down version of what [ddev](https://github.com/drud/ddev) uses as its basic functionality.)

```
version: '3.6'
services:
  db:
    image: drud/ddev-dbserver-mariadb-10.5:v1.16.0
    volumes:
    - source: ~/tmp/junk/base
      target: /mnt/ddev_config
      type: bind
  web:
    image: drud/ddev-webserver:v1.16.3
    links:
    - db:db
    volumes:
    - consistency: cached
      source: ~/tmp/junk
      target: /var/www/html
      type: bind
    - ~/tmp/junk/base/nginx_full:/etc/nginx/sites-enabled:ro
```

### Actual behavior

Now, in Docker Desktop 3.0.2 for Mac:

```
$ docker-compose -f test4-compose.yaml up
Creating ddev_db_1 ... done
Creating ddev_web_1 ... error

ERROR: for ddev_web_1  Cannot start service web: error while creating mount source path '/host_mnt/Users/rfay/tmp/junk/base/nginx_full': mkdir /host_mnt/Users/rfay/tmp/junk/base/nginx_full: no such file or directory

ERROR: for web  Cannot start service web: error while creating mount source path '/host_mnt/Users/rfay/tmp/junk/base/nginx_full': mkdir /host_mnt/Users/rfay/tmp/junk/base/nginx_full: no such file or directory
ERROR: Encountered errors while bringing up the project.
```

### Information

  - macOS Version: Big Sur 11.1 (amd64)

### Diagnostic logs

Docker for Mac: version: 3.0.2

### Steps to reproduce the behavior

1. Use the above docker-compose.yaml, call it `test4-compose.yaml`
2. `mkdir -p ~/tmp/junk/base/nginx_full`
3. `docker-compose -f test4-compose.yaml up`

I am able to try a number of things that will make the `docker-compose up` start to work (but of course break the underlying functionality:

* I can remove the `links: db:db` stanza in the web service.
* I can remove the single volume mount in the db service.
* I can remove the /var/www/html volume mount in the web service
* I can turn off the "experimental" gRPC Fuse feature and it works fine.

My assumption is that the failure has to do with overlapping volume mounts. 

Since the docker-compose in both Docker Desktop for Mac 3.0.1 and 3.0.2 is the same, "docker-compose version 1.27.4, build 40524192", I have to assume this is a Docker for Mac issue, not a docker-compose issue.

In addition to launching fine on Docker Desktop for Mac 3.0.1 and all previous versions, this works fine in Docker Desktop for Windows 3.0.0 (which has the same docker-compose version) on both the Windows side and the WSL2 side (with a WSL2 back-end).

**Comment by ebriney** [comment]
Thanks @rfay I will fix it on monday and do another release!

**Comment by teaforchris** [comment]
Just to confirm I am experiencing a very similar issue which I suspect is related to the root cause for this one. For **_ages_** the following docker-compose.yml has worked for us **_no issues at all_**, but since 3.0.2 update, the subdirectory in the php container which shares the mount point with the node container is EMPTY from the perspective of the php container!

Our docker-compose.yml file (for reference only, some information redacted)
```
version: '3.2'

services:
  php:
    image: xxxxx/wordpress:7.3-apache
    ports:
      - "8083:80"
    links:
      - db
    volumes:
      - .:/var/www:delegated
    networks:
      - custom
  db:
    image: mysql:5.7.23
    restart: always
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d:delegated
    environment:
      - MYSQL_DATABASE=xxxxxx
      - MYSQL_USER=xxxxxx
      - MYSQL_PASSWORD=xxxxxx
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    ports:
      - "3309:3306"
    networks:
      - custom
    env_file:
      - ./.env
  node:
    image: "node:14.8.0"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - ./web/app/themes/affected-directory/:/app
    expose:
      - "8081"
    command: tail -F /dev/null
networks:
  custom:
    driver: bridge
#volumes:
#  data:

```

For those who are curios, this is a WordPress Bedrock project. Long story short we use the php/db containers like you might expect, plus the additional node container is for consistent local builds without having to rely on nvm locally etc.

So, what is expected (and has worked for all Docker versions 3.0.1 or earlier):

The local directory (our theme) in `/web/app/themes/affected-directory` should be accessible under `/var/www/web/app/themes/affected-directory` in the php container and `/app` in the node container.

This has been the case and has worked perfectly for as long as I can remember.

With Docker Desktop for Mac 3.0.2 the theme directory in the php container is empty - almost as if there is some kind of conflict with shared mount points.

**Comment by olvlvl** [comment]
Same here with WireMock:

```
  recipe_service:
    command: --verbose
    image: rodolpheche/wiremock:2.18.0-alpine
    volumes:
    - ./wiremock:/home/wiremock/mappings
```

"data" is automatically mounted at "/home/wiremock/" and "mappings" is not mounted anymore. I downgraded to v2.5.0.1 in the meantime.
