### ISSUE TITLE
Service does not have load balancer ingress IP address

### ISSUE THREAD

**Issue by hazcod** [docker/for-mac#5229]
Checks
  - [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 8F32DCD2-92AD-48DB-8BCB-1E1433359FC4/20210106163108
 
### Expected behavior
I should be able to deploy services without an ingress.

### Actual behavior
`helm install` times out with the error: `wait.go:206: [debug] Service does not have load balancer ingress IP address`
I *guess* something is going wrong with automatically mapping the ports to the Mac host?

### Information
  - macOS Version: 11.1
  - Docker for Mac: 3.0.3

```yaml
% k -n venclave describe services
Name:                     backend
Namespace:                venclave
Labels:                   app=backend
                          app.kubernetes.io/managed-by=Helm
                          owner=hazcod
Annotations:              meta.helm.sh/release-name: backend
                          meta.helm.sh/release-namespace: venclave
Selector:                 app=backend
Type:                     LoadBalancer
IP Families:              <none>
IP:                       10.108.70.155
IPs:                      <none>
Port:                     backend  9300/TCP
TargetPort:               8080/TCP
NodePort:                 backend  30728/TCP
Endpoints:                10.1.0.11:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

```
% k -n niels get pods    
NAME                       READY   STATUS    RESTARTS   AGE
backend-558467f5d9-vmxwj   1/1     Running   0          3m32s
```

```
% k -n niels get services
NAME      TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
backend   LoadBalancer   10.108.70.155   <pending>     9300:30728/TCP   4m52s
```
