### ISSUE TITLE
Docker preview version for apple silicon is fail to run 'apache/airflow' image

### ISSUE THREAD

**Issue by kevin1172** [docker/for-mac#5232]
### Issue:
I tried to run the 'apache/airflow' image (https://hub.docker.com/r/apache/airflow) with docker-compose. 
The container is able to start, but after running some airflow commends, the container is terminated with an error 'qemu: uncaught target signal 4 (Illegal instruction) - core dumped'

### Actual behavior
Following is my docker-compose.yml file
```
version: '3.8'
services:
    webserver:
        image: apache/airflow
        command: bash -c
            "airflow db init 
            && airflow users create -u admin -f Peter -l Parker -r Admin -e spiderman@superhero.org -p ****
            && airflow webserver"
        volumes:
            - ./dags:/opt/airflow/dags
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqldb://airflow:airflow@192.168.64.1:3306/airflow
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        ports:
            - "8080:8080"
```
After I run "docker-compose up", I get:
```
Recreating docker-airflow_webserver_1 ... done
Attaching to docker-airflow_webserver_1
webserver_1  | DB_BACKEND=mysql+mysqldb
webserver_1  | DB_HOST=192.168.64.1
webserver_1  | DB_PORT=3306
webserver_1  | 
webserver_1  | DB: mysql+mysqldb://airflow:***@192.168.64.1:3306/airflow
webserver_1  | [2021-01-08 04:28:45,451] {db.py:678} INFO - Creating tables
webserver_1  | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
webserver_1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
webserver_1  | qemu: uncaught target signal 4 (Illegal instruction) - core dumped
webserver_1  | /bin/bash: line 1:    21 Illegal instruction     airflow db init
docker-airflow_webserver_1 exited with code 132
```

### Information

  - macOS Version: Big Sur
  - Docker for Mac: Apple silicon preview version released on Dec 16

Do I have to wait for the production version of Docker Desktop for Mac? How can I fix it? Thanks!
