### ISSUE TITLE
Possible shm memory issue with Docker version 20.0

### ISSUE THREAD

**Issue by saramorsi** [docker/for-mac#5254]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Snapshot tests should pass within our Docker container in our functional environment. 

### Actual behavior

Snapshot tests fail within our Docker container in our functional environment. The problem of the crashing tab is most likely that the container has no access to `/dev/shm` memory (that is where our image is mounted).

Docker container logs include this message: 
`[1610656951.894][SEVERE]: bind() failed: Cannot assign requested address (99)`

See snippet here: 

```
selenium:
    image: selenium/standalone-chrome-debug:3.141.59-20210105
    container_name: proj-selenium
    network_mode: "service:frontend"
    depends_on:
      - frontend
    environment:
      - TZ=America/New_York
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING
      - SCREEN_HEIGHT=1700
      - SCREEN_WIDTH=1380
    volumes:
      - /dev/shm:/dev/shm
```

It seems to be an issue with shm memory. Downgrading from Docker 20.10.2 to 19.03.13 helped resolve the issue. 

### Information

Please, help us understand the problem.  For instance:

It seems to be an issue with shm memory. Downgrading from Docker 20.10.2 to 19.03.13 helped resolve the issue. 

macOS Version: Mac OSX Catalina 10.15.7 (19H114)
