### ISSUE TITLE
gRPC Fuse - Secrets do not mount into volumes when running as swarm

### ISSUE THREAD

**Issue by karillo** [docker/for-mac#5284]
Given a compose file which maps a local file as a secret and a local volume as a mounted volume, mapping the secret into a path governed by the mounted volume (see reproduction steps below for a short example).

If the compose file is deployed as a stack on top of swarm and if the experimental gRPC FUSE filesystem is being used, then the secret will not appear at the designated location within the mounted filesystem.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 484B409B-6B25-47B7-9268-8A3B5183050A/20210121181427

### Expected behavior
- The mounted secret should appear at the target location within the mounted volume. (With immutable content on swarm.)
- If a file already exists at that location in the mounted volume, the mounted secret should appear in the place of that file when the mounted volume is observed within the container.

(These behaviors are consistent with existing behaviors if the filesharing uses `osxfs` or if the compose file is run with `docker-compose`/`docker compose`.)

### Actual behavior
If no file exists, a zero-length file with 0755 permissions is created as a mount point, but it does not include the contents of the secret.

If a file exists in the directory being mounted as a volume, then that file appears directly, as if the secret were not mapped at all.

### Information

  - macOS Version: 10.5.6 through 11.1
  - I first observed the problem with the 2.4.0.0 Release as it defaulted "gRPC FUSE" to on.

### Diagnostic logs

```
Docker for Mac: version 3.1.0 (51484)

```
See Logs from Diagnostic ID 484B409B-6B25-47B7-9268-8A3B5183050A/20210121181427

### Steps to reproduce the behavior

The script below demonstrates the problem.
Prerequisites: `docker swarm init`
If gRPC FUSE is enabled, the file `/mnt/foo` will be empty
If gRPC FUSE is disabled (falling back on `osxfs`), the file `/mnt/foo` contains the date

```
#!/bin/sh

# Local file to use as a secret
date > foo

# Directory to mount as a volume
mkdir -p mnt
echo "hello" > mnt/bar

# Compose file maps the secret onto the mapped volume.
docker stack deploy grpc --compose-file - <<EOF
version: '3.9'

secrets:
  foo:
    file: ./foo
    name: foo

services:
  mount:
    image: alpine
    init: true
    entrypoint: ["/usr/bin/tail","-F","/etc/hosts"]
    volumes:
      - ./mnt:/mnt
    secrets:
      - source: foo
        target: /mnt/foo
EOF

sleep 2

# Notice that the secret's mount location becomes a zero-length file 
docker exec -it $(docker ps --filter "name=grpc" --filter "status=running" --latest --format "{{.Names}}") ls -l /mnt
```
