### ISSUE TITLE
Docker-compose: ssh-agent forward

### ISSUE THREAD

**Issue by fabiofdsantos** [docker/for-mac#5303]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

I'm unable to get ssh-agent working inside the container. However, it works properly with `docker run -it -v...`.

### Information

  - macOS Version: 11.1 (Big Sur)

### Diagnostic logs

```
Docker for Mac: 3.1.0

2021-01-28 23:04:10.683155+0000  localhost com.docker.backend[13748]: 
grpcfuseClient.Add(XXXXXXX, /my-app-php, [host=,VM=php-sync,dst=/home/XXX/my-app,
option=nocopy host=/private/tmp/com.apple.launchd.EO2rUUToAS/Listeners,
VM=/host_mnt/private/tmp/com.apple.launchd.XXXXX/Listeners,dst=/run/host-services/ssh-auth.sock,option=rw])

```

### Output

**Host:**

```bash
$ ssh-add -l
4096 SHA256:XXXXXXXXX XX@XX. (RSA)
```

**Container:**
```
Cloning into '/home/XXX/XXX'...

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

### docker-compose.yml

```
version: "3"
services:
  php:
    build:
      context: ./.docker
      dockerfile: php.dockerfile
      args:
        - PROJECT_NAME=my-app
        - PROJECT_PORT=8081
        - XDEBUG_HOST=${DOCKER_GATEWAY_HOST:-host.docker.internal}
        - XDEBUG_PORT=9003
    container_name: my-app-php
    hostname: my-app-php
    volumes:
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
      - php-sync:/home/XXX/my-app:nocopy
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    ports:
      - 8081:8081
networks:
  default:
    external:
      name: dev-network
volumes:
  php-sync:
    external: true
```

### php.dockerfile

```
FROM php:7.4-fpm-alpine3.12
(...)
RUN apk add    \
  git        \
  openssh    \
(...)

USER myUser

CMD ["/usr/bin/entrypoint"]
```
