### ISSUE TITLE
M1 preview: docker-compose depends_on doesn't seem to work

### ISSUE THREAD

**Issue by stijn-gravity** [docker/for-mac#5315]
Reporting this here because this is not an issue for any of my coworkers who are not running on the M1 version. It is exclusive to the M1 preview.

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features -> I have not, because I need them.
  - [ ] I have uploaded Diagnostics

### Expected behavior
Exerpt of the docker-compose file:
```
version: '3.6'
services:
  postgres:
    image: mdillon/postgis:11
    restart: always
    ports:
      - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
  functions-mock:
    image: kennethreitz/httpbin
    restart: always
    ports:
    - "4001:80"
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0.cli-migrations
    restart: always
    ports:
    - "4000:8080"
    depends_on:
    - "postgres"
    volumes:
    - ./migrations:/hasura-migrations
    environment:
        ....obfuscated
volumes:
  db_data:

```

On older versions this would crash and restart because postgres was not started yet. After this restart this would work as intended.

### Actual behavior

On this new version the hasura/graphql-engine container keeps restarting. We can connect to postgres ourselves, and it started correctly. But the hasura/graphql-engine keeps restarting as if it's not there yet. The issue seems to lie in the connection between hasura/graphql-engine and postgres.

Logs from a single loop (this repeats) 
```
{"timestamp":"2021-02-04T08:44:31.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"port env var is not set, defaulting to 8080"}}

{"timestamp":"2021-02-04T08:44:31.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"server timeout is not set defaulting to 30 seconds"}}

{"timestamp":"2021-02-04T08:44:31.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"starting graphql engine temporarily on port 8080"}}

{"timestamp":"2021-02-04T08:44:31.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"waiting 30 for 8080 to be ready"}}

{"timestamp":"2021-02-04T08:45:03.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"failed waiting for 8080"}}
```

### Information
I asked a few colleagues with new M1 chips to test this, and they all had the same experience. All colleagues with old intel chips could run this without issues.

### Steps to reproduce the behavior
Additional dockerfile:
```
FROM hasura/graphql-engine:v1.0.0.cli-migrations

COPY migrations /hasura-migrations
```

If no immediate solution can be found we understand this. We are on a preview version and will have to deal with the consequences. A way to work around this issue we can't find ourselves, so any help in that direction would also be great.
