### ISSUE TITLE
Unable to mount directory persistent locally

### ISSUE THREAD

**Issue by dennypenta** [docker/for-mac#5361]
### Expected behavior
PersistentVolumeClaim creates mount directory that provides data after restart docker

### Actual behavior
it doesn't

### Information
  - macOS Version: 0.15.7 (19H2)
  - Docker Desktop Version: 3.1.0 (51484)

**Comment by dennypenta** [comment]
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
spec:
  storageClassName: localstorage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/pvc/psql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
spec:
  storageClassName: localstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
...
volumeMounts:
            - name: psql-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: psql-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-volume-claim
```
