### ISSUE TITLE
"platform" option in docker-compose.yml ignored (preview version)

### ISSUE THREAD

**Issue by flevanti** [docker/for-mac#5364]
Just updated to the latest preview version and the configuration previously working is giving an error when running docker compose up. when pulling the image for mysql:5.7  the usual "no match for platform in manifest" error is shown.

I managed to have it working fine using the "platform: linux/amd64" option in the docker-compose.yml file but that parameter is now ignored.
I tried to use it again on the previous version with no problem.

**important:**
the image used is not specified directly in the docker-compose file but in a separate Dockerfile (in the same context/folder for the sake of testing).
If the image to pull is specified in the docker-compose file the "platform" option is then used correctly also in the latest version.

I found a workaround/solution moving the platform option inside the dockerfile directly when specifing the "FROM".

I can pull/use the image directly using docker pull specifying the platform with no problem as expected
  - [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: `e4b1243f-92a5-455c-9614-0427f574b5d9/20210218172042`

### Expected behavior
image is pulled successfully
### Actual behavior
image is not pull, and error related to the manifest is shown.

### Information

  - macOS Version: 11.2
  - Docker Desktop Version: 3.1.0 (60984).  Engine 20.10.3.   Compose 1.28.2

### Steps to reproduce the behavior

(using your terminal)
- create a test folder and make it your current working folder (`cd` into it!)
- create a `docker-compose.yml` file and past this content inside it:
```
version: '3.6'
services:
  mysql:
    platform: linux/amd64
    build:
        context: .
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'default'
      MYSQL_USER: 'data'
      MYSQL_PASSWORD: 'data'
```
- create a `Dockerfile` and past this content into it:
```
FROM mysql:5.7
```
- run `docker-compose up --build -d`

You will get an error, something like "failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest"

This configuration was working in the previous version.

If you now edit your `Dockerfile` and change the first (and only) line to 

`FROM --platform=linux/amd64 mysql:5.7`

and run again `docker-compose up --build -d`

it will work.
