### ISSUE TITLE
high cpu issue using v3.1.0

### ISSUE THREAD

**Issue by jsharpe-ctm** [docker/for-mac#5413]
Similar to:
https://github.com/docker/for-mac/issues/3539
https://github.com/docker/for-mac/issues/3499

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
CPU Consumption would be more 'normal'

### Actual behavior
After a few minutes of starting redis instance, cpu spikes to 200%, but redis isn't doing much

### Information

  - Is it reproducible? For me, very reproducible.  It seems very tied to starting a container using redis:latest
  - Is the problem new? It's been going on for weeks now, but might be getting worse.  I find myself restarting docker multiple times throughout the day.  Though, now, the issue shows up within a minute or two.  
  - Did the problem appear with an update?  Not sure. I don't recall docker notifying me it was updating.  I haven't initiated an update.  So... probably not?
  - A reproducible case if this is a bug, Dockerfiles FTW.
-->
  - macOS Version: 10.15.7
  - Docker Desktop Version: 3.1.0

### Steps to reproduce the behavior

```
version: "3.9"
services:
  mysql:
    restart: always
    image: percona:5.6.51
    volumes:
      - ./config/my_dev.cnf:/etc/my.cnf.d/my_dev.cnf
      - ./../data/mysql-5.6:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  memcache:
    restart: always
    image: memcached:latest
    ports:
      - "11211:11211"

  mongodb:
    restart: always
    image: mongo:3.0.15
    volumes:
      - ./db/:/db-backup/
      - ./../data/mongodb-3.0:/usr/local/var/mongodb
    ports:
      - "27017:27017"

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    volumes:
      - ./../data/elasticsearch-7.5:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - node.name=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Dmapper.allow_dots_in_name=true -Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
```

For me, it seems tied to the redis instance.  If I stop redis, the issue mostly goes away:

Lightly using redis:
![Activity_Monitor__My_Processes__and_tmux](https://user-images.githubusercontent.com/73131646/109700028-47b3b000-7b5f-11eb-9fd6-dd20a28e072a.jpg)

Stopped processes (on host) using redis lowers CPU... but host CPU is still seemingly way too high.
![Activity_Monitor__My_Processes__and_tmux](https://user-images.githubusercontent.com/73131646/109700086-5ac68000-7b5f-11eb-9fd5-92f23754ec88.jpg)

Docker should have plenty of resources:
![Settings](https://user-images.githubusercontent.com/73131646/109700212-7b8ed580-7b5f-11eb-927b-0b4e8349acc0.jpg)
