### ISSUE TITLE
Garbled screen on desktop client

### ISSUE THREAD

**Issue by TheCycoONE** [docker/for-mac#5424]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2997D142-C55F-4CBE-AA57-A3D94815DFA2/20210305140236

### Expected behavior
To be able to see the containers in the desktop client

### Actual behavior
Pattern changes as I move the mouse while the docker client has focus, and sometimes I can see it clearly. As long as the window does not have focus or I don't move the mouse it stays static. If I collapse the docker-compose stack and move my mouse away from it the screen goes back to normal:

<img width="1318" alt="Screen Shot 2021-03-05 at 8 20 20 AM" src="https://user-images.githubusercontent.com/823433/110121289-33a0c600-7d8c-11eb-9209-108f4605da37.png">

<img width="1362" alt="Screen Shot 2021-03-05 at 8 59 25 AM" src="https://user-images.githubusercontent.com/823433/110125269-1fab9300-7d91-11eb-9b7e-038b3e3d3f96.png">

### Information
I believe the problem started when I expanded the number of containers in my docker compose file.

  - macOS Version: 11.2.1
  - Docker Desktop Version: 3.2.0

### Steps to reproduce the behavior

Create a docker compose file with quite a few containers. Here is mine:
```
version: "3.9"
services:
  db:
    image: "155159780906.dkr.ecr.us-east-2.amazonaws.com/rave-db-apps"
    ports:
      - "23306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/etc:/etc/mysql
    environment:
      -  MYSQL_ALLOW_EMPTY_PASSWORD=1

  smppsim:
    image: "155159780906.dkr.ecr.us-east-2.amazonaws.com/smppsim:latest"
    command: mkdir /logs
    command: java -Djboss.server.log.dir=/logs -cp /lib/rave-messaging-smppsim.jar:lib/smpp.jar:/lib/jakarta-regexp-1.2.jar:/lib/rave-messaging-internalcommon.jar:/lib/rave-messaging-proputil.jar:/lib/log4j.jar:conf:/lib/jboss-common-client.jar com.raveu.messaging.smppsim.Main -P /conf/smppsim.conf
    ports:
      - 2080:88
    volumes:
      - ./smppsim/conf:/conf
      - ./smppsim/logs:/logs

  artemis-1:
    image: artemis-adoptopenjdk-11
    volumes:
      - ./artemis_1:/var/lib/artemis-instance
    ports:
      - 2101:8161
      - 2102:61616

  artemis-2:
    image: artemis-adoptopenjdk-11
    volumes:
      - ./artemis_1:/var/lib/artemis-instance
    ports:
      - 2101:8161
      - 2102:61616
    profiles:
      - clustered

  artemis-1-m:
    image: artemis-adoptopenjdk-11
    volumes:
      - ./artemis_1_m:/var/lib/artemis-instance
    ports:
      - 2201:8161
      - 2202:61616
    profiles:
      - mirror

  msg-sms:
    image: "155159780906.dkr.ecr.us-east-2.amazonaws.com/wildfly"
    depends_on:
      - "db"
      - "smppsim"
      - "artemis-1"
    command: /msg-sms/start.sh
    env_file:
      - msg-sms.env
    environment:
      - NODE_ID=sms1
    volumes:
      - ./sb_sms_1:/msg-sms
    ports:
      - 2189:9990
      - 2188:8080
      - 2187:8787
    profiles:
      - clustered

  msg-sms-2:
    image: "155159780906.dkr.ecr.us-east-2.amazonaws.com/wildfly"
    depends_on:
      - "db"
      - "smppsim"
      - "artemis-2"
    command: /msg-sms/start.sh
    env_file:
      - msg-sms.env
    environment:
      - NODE_ID=sms2
    volumes:
      - ./sb_sms_2:/msg-sms
    ports:
      - 2289:9990
      - 2288:8080
      - 2287:8787
    profiles:
      - clustered
```

  1. Run docker-compose up
  2. Hover over, or expand the resulting compose stack in the desktop client
