### ISSUE TITLE
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mountXXXXXXXXX/<git repository>#master/docker/Dockerfile.Local: no such file or directory

### ISSUE THREAD

**Issue by derekhubbard** [docker/for-mac#5439]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

`docker-compose` supports the ability to configure a serivce to pull from a hosted git repository, using a dockerfile with a custom name and sitting in a non-default/custom location. 

### Actual behavior

`docker-compose` fails to build the service and runs into the following error: 

```
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount428930559/<git repo url>#master/docker/Dockerfile.Local: no such file or directory
```

### Information

  - macOS Version: 10.14.6
  - Docker Desktop Version: 3.2.1
 
This appeared after updating Docker Desktop to version 3.2.1. I was previously running version 3.1.0.

Here's a pseudo-version of our docker-compose setup: 
```
  test_service:
    container_name: test_container
    build:
      context: <git_repo_url>#${GQL_BRANCH:-master}
      dockerfile: ./docker/Dockerfile.Local
```
