### ISSUE TITLE
com.docker.backend at 100% CPU with gRPC FUSE enabled

### ISSUE THREAD

**Issue by iameli** [docker/for-mac#5528]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features (enabling, too!)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Not 100% CPU usage on com.docker.backend with "Use gRPC FUSE for file sharing enabled"

### Actual behavior

100% CPU usage on com.docker.backend with "Use gRPC FUSE for file sharing enabled"

### Information
  - macOS Version: 11.2.3 (I also encountered the problem with Catalina, but the upgrade to Big Sur did not help.)
  - Docker Desktop Version: 3.2.2

### Steps to reproduce the behavior
* Factory Reset
* `docker-compose up` with this `docker-compose.yml`:

```yaml
version: "3.9"
services:
  dev-container:
    container_name: dev-container
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8200:8200"
    command: /app/docker/runforever.sh
    volumes:
      - .:/app
      - $HOME:$HOME
volumes:
  dev-container-data: {}
```

Contents of `runforever.sh`:

```
#!/bin/bash

echo "Container is now up and running"
tail -f /dev/null
```

* `com.docker.backend` CPU usage goes up to 100%:

![image](https://user-images.githubusercontent.com/257909/113347388-f62b4c00-92e9-11eb-9967-a447558ff276.png)

* Uncheck this box and allow Docker to restart:
![image](https://user-images.githubusercontent.com/257909/113347457-0e9b6680-92ea-11eb-839d-f99d5fefffa8.png)

* CPU is no longer at 100%.

Oddly, the problem doesn't seem to come back when I re-check the box, so perhaps the problem isn't with gRPC FUSE but instead with something else that's fixed when I swapped around the storage engine.
