### ISSUE TITLE
M1 Docker Desktop RC2/ RC3:  Unable to mount NFS volumes with QEMU or with new virtualisation framework (it was working on RC1)

### ISSUE THREAD

**Issue by sigurpol** [docker/for-mac#5534]
- [X ] I have tried with the latest version of Docker Desktop
  - [X ] I have tried disabling enabled experimental features

### Expected behavior
NFS mount should just work, as it did until RC1
### Actual behavior
NFS mount fails systematically

### Information
  - Is it reproducible? Systematically
  - Is the problem new? Yes
  - Did the problem appear with an update? yes, starting from RC2
  - macOS Version: 11.2.3
  - Docker Desktop Version: 3.3.0 M1 RC2 / RC3

### Steps to reproduce the behavior
Starting from RC2 and including current latest (RC3) I am not able anymore to mount an NFS volume on my M1 Mac.

It was working just fine until RC1.

How to reproduce:

This is my /etc/exports
```
/Users/paolo/projects -alldirs -mapall=501:20 192.168.64.2
```
where 192.168.64.2 is the address associated to host.docker.internal

And this is an example of docker-compose.yaml
```
volumes:
    nfsmount:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":/Users/paolo/projects"
services:
  mysrv1:
    cap_add:
    - SYS_PTRACE
    command: /bin/sh
    image: "alpine:latest"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    tty: true
    volumes:
    - "nfsmount:/workspace"
version: '3'
```

Then I enter
```
docker compose up
```
or `docker-compose up`

and I get the following error:

```
Error response from daemon: error while mounting volume '/var/lib/docker/volumes/downloads_nfsmount/_data': failed to mount local volume: mount :/Users/paolo/projects:/var/lib/docker/volumes/downloads_nfsmount/_data, data: addr=192.168.64.2,nolock,hard,nointr,nfsvers=3: permission denied
```

It was working fine until RC1.
I've tried both via QEMU (error: permission denied) and via new virtualisation framework (error: operation not supported)
