### ISSUE TITLE
works on apple m but not on apple intel

### ISSUE THREAD

**Issue by shorif2000** [docker/for-mac#5577]
I have the following docker file and docker-compose file which i made on apple mac with apple chip.

Now when I run it on apple intel the app fails to start with exit error 255

Dockerfile.local
```
# Set the base image for subsequent instructions
FROM php:7.3

# Update packages
RUN apt-get update

# Install zip
RUN apt-get -y install zip unzip libzip-dev

# Install PHP and composer dependencies
RUN apt-get -y install -qq git curl libmcrypt-dev libjpeg-dev libpng-dev libfreetype6-dev libbz2-dev yarn

# Install python for running AWS code dpeloy
RUN apt-get install -y python python-pip
# Need boto for aws deploy..
RUN pip install boto3

RUN apt-get install -y nodejs npm

RUN npm install -g yarn
#RUN npm i npm@latest -g


# Clear out the local repository of retrieved package files
RUN apt-get clean

# Install needed extensions
# Here you can install any other extension that you need during the test and deployment process
RUN docker-php-ext-install pdo_mysql zip gd

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copy existing application directory contents
COPY . /var/www/html/

# Copy existing application directory permissions
COPY --chown=www:www . /var/www/html/

# Install Composer
RUN curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


# Change current user to www
USER www

# Set working directory
WORKDIR /var/www/html/
RUN composer install
#RUN npm i

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]

#RUN php artisan migrate:refresh --seed
#RUN php artisan passport:install
#RUN php artisan passport:client --password --name 'Internal Api'
#RUN php artisan passport:client --client --name 'Results API'
#RUN php artisan passport:client --personal --name 'External Partners Api'
#RUN php artisan storage:link

CMD php artisan serve --host=0.0.0.0 --port=8080 >> access.log 2>&1
EXPOSE 8080


```

docker-compose.yaml
```yaml
version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      - mysql
    ports:
      - "80:8080"
    volumes:
      - .:/var/www/html
    links:
      - mysql:mysql
    environment:
      APP_NAME: app
      APP_ENV: local
      APP_KEY: base64:W81ZHKIJohhTPNipN1WwUdzljzHYLPSH2U3zJJmzMZQ=
      JWT_SECRET: PhBMYqWu4c0cAm5KpxWXgx25to32xIUy
      APP_DEBUG: 'true'
      APP_URL: https://app.local

      DB_HOST: mysql
      DB_DATABASE: app_local
      DB_USER: root
      DB_PASSWORD: root

  mysql:
    image: mysql:5.7@sha256:b3b2703de646600b008cbb2de36b70b21e51e7e93a7fca450d2b08151658b2dd
    container_name: app_mysql
    ports:
      - "33067:3306"
    environment:
      - MYSQL_DATABASE=app_local
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root

```
