### ISSUE TITLE
Docker for Mac 3.3.0 `/dev/null: Permission denied` (downgrading to 3.2.2 resolves issue)

### ISSUE THREAD

**Issue by gerbenoostra** [docker/for-mac#5580]
I'm getting the follow error:
` /usr/local/bin/docker-entrypoint.sh: line 296: /dev/null: Permission denied`

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

I am running a gitlab runner locally on my macbook, on Docker desktop for Mac.
In a build step, I'm attaching postgres as a service.

### Expected behavior
Up till including version 3.2.2 ran as expected, resulting in following output in gitlab:
```
Starting service postgres:12.6-alpine ...
Pulling docker image postgres:12.6-alpine ...
Using docker image sha256:bc493ea5711b2b577de577e5c9073e3ce46458cc3ce377a238e5c16d75d5fc68 for postgres:12.6-alpine with digest postgres@sha256:b5c57d326a4cb8cf2fd5cdedc758ed72146a69304ae434b177088b94a7c9e6b8 ...
Waiting for services to be up and running...
```

### Actual behavior
After updating to version 3.3.0, I get the following error:
```
Starting service postgres:12.6-alpine ...
Pulling docker image postgres:12.6-alpine ...
Using docker image sha256:bc493ea5711b2b577de577e5c9073e3ce46458cc3ce377a238e5c16d75d5fc68 for postgres:12.6-alpine with digest postgres@sha256:b5c57d326a4cb8cf2fd5cdedc758ed72146a69304ae434b177088b94a7c9e6b8 ...
Waiting for services to be up and running...
*** WARNING: Service runner-bysuewxm-project-18782304-concurrent-0-2ca260fc82806f49-postgres-0 probably didn't start properly.
Health check error:
start service container: Error response from daemon: Cannot link to a non running container: /runner-bysuewxm-project-18782304-concurrent-0-2ca260fc82806f49-postgres-0 AS /runner-bysuewxm-project-18782304-concurrent-0-2ca260fc82806f49-postgres-0-wait-for-service/service (docker.go:1156:0s)
Service container logs:
2021-04-15T10:06:03.261000371Z /usr/local/bin/docker-entrypoint.sh: line 296: /dev/null: Permission denied
```

I've tried:
* Clean/Purge data
* Reset to factory defaults
* Uninstall Docker for Mac completely, and installing 3.3.0 cleanly.
* Therefore have also pulled gitlab/gitlab-runner:latest again
* With different postgres tags (postgres:12.5-alpine, postgres:13.2-alpine)
Non of these resolved the issue.

After downgrading to Docker for Mac 3.2.2, the issue was resolved.

### Information
  - macOS Version: 11.2.3 (macOs Big Sur)
  - Docker Desktop Version: 3.3.0

### Steps to reproduce the behavior

I'm running a gitlab runner with the following config
```toml
# config.toml
concurrent = 2
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "my_laptop_runner"
  url = "https://gitlab.com"
  token = "MY_GITLAB_TOKEN"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/certs/client", "/cache"]
    shm_size = 0
```

On my Docker for Mac, which is installed as 
```sh
docker run -d --name gitlab-runner --restart always \
   -v /Users/Shared/gitlab-runner/config:/etc/gitlab-runner \
   -v /var/run/docker.sock:/var/run/docker.sock \
   gitlab/gitlab-runner:latest
```

I'm then running a build with a job defined similar to:
```yaml
# .gitlab-ci.yml:
variables:
  DOCKER_TLS_CERTDIR: "/certs"

default:
  image: python:3.8

my-job:
  stage: test
  services:
    - postgres:12.6-alpine
  variables:
    POSTGRES_DB: my_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
```
