### ISSUE TITLE
Docker desktop 3.3.1 cannot connect to exposed ports

### ISSUE THREAD

**Issue by sptrakesh** [docker/for-mac#5610]
- [ x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker containers that have ports exposed should be accessible vial the loopback host.

### Actual behavior
Containers are no longer reachable.  I can hop on a container and access all containers on the docker network, but no access via `localhost`. 

### Information

  - macOS Version: 11.2.2
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.1

### Steps to reproduce the behavior

  1. Docker stacks that worked without issues till 3.2.2 became inaccessible with 3.3.1
  2. Reverting back to 3.2.2 made them all available.
  3. Does 3.3 series implement a k8s style access policy?  In other words do I need to run some kind of proxy service to make the containers accessible via localhost?

**Comment by djs55** [comment]
@sptrakesh thanks for your report. Could you provide a small repro example which I could use to investigate?

**Comment by sptrakesh** [comment]
Here is a simple stack file that stopped working when I had upgraded to 3.3.1.  Could not access service on port 2000...

```
version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - $DATA_DIR/mongo:/data/db

  mongo-service:
    image: sptrakesh/mongo-service
    stop_signal: SIGTERM
    ports:
      - "2000:2000"
    environment:
      - "MONGO_URI=mongodb://test:test@mongo/admin?authSource=admin&compressors=snappy&w=1&maxPoolSize=1000&maxIdleTimeMS=30000"
      - VERSION_HISTORY_DATABASE=versionHistory
      - VERSION_HISTORY_COLLECTION=entities
      - METRICS_COLLECTION=metrics
      - LOG_LEVEL=debug
      - THREADS=8
    volumes:
      - $DATA_DIR/mongo-service:/opt/spt/logs
```
