### ISSUE TITLE
Network Connectivity Issues after moving to 3.3.0+

### ISSUE THREAD

**Issue by davidamin** [docker/for-mac#5614]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3FD9A0FF-429C-4FF3-BF7B-3F57F402A622/20210421205552

### Expected behavior

In past versions of Docker, I was able to run `envoy` locally to route requests from my Mac to an external host on port 80. After upgrading to 3.3.0, that is no longer working. The expected behavior is to be able to proxy traffic from a Docker container in Docker Desktop to an external host on any port.

### Actual behavior

Traffic from Envoy proxy inside a Docker container fails to route if it is trying to reach an external host on port 80. The requests seem to forward infinitely and eventually time out. This only seems to happen with `80`, I'm not able to reproduce the behavior when targeting an external host on any other port.

### Information
  - macOS Version: 10.15.7
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.1

This issue seems tied to the latest update(s), I am unable to reproduce the error on version 3.2.2.

### Steps to reproduce the behavior

  1. While running Docker Desktop Version 3.3.0 or 3.3.1, create an Envoy container with a config similar to the following
  ```
version: "2.4"
services:
  envoy:
    container_name: "envoy"
    image: envoyproxy/envoy:v1.18.2
    cpus: 0.5
    mem_limit: 128m
    restart: unless-stopped
    ports:
      - 9002:9002
      - 9901:9901
    volumes:
      - /path/to/your/envoy-config.yaml:/etc/envoy-config.yaml
    command: "envoy --config-path /etc/envoy-config.yaml --service-node envoy_1 --service-cluster dev"
  ```
  2. Replace `/path/to/your/envoy-config.yaml` above with a path on your host to a file like the following:
  ```
admin:
  access_log_path: "/dev/stdout"
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901}

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 9002 }
      filter_chains:
      - filters:
        - name: envoy.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            stat_prefix: egress_http
            codec_type: AUTO
            use_remote_address: true
            http_protocol_options:
              accept_http_10: true
            http_filters:
            - name: envoy.filters.http.router
            route_config:
              name: local_route
              virtual_hosts:
              - name: local_service
                domains: ["*"]
                routes:
                - match:
                    prefix: "/"
                  route:
                    cluster: service_test_fail
  clusters:
    - name: service_test_fail
      connect_timeout: 0.25s
      type: LOGICAL_DNS
      # Comment out the following line to test on v6 networks
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: service_test_fail
        endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                      address: 216.58.194.46
                      port_value: 80
  ```
3. Run `curl -v http://localhost:9002`. The request should time out.
4. Downgrade to Docker Desktop 3.2.2 and retry, the request will return a valid response.

I have not tried to recreate this issue with any proxy other than Envoy, but I'm willing to try just to confirm it's not Envoy-specific.
