### ISSUE TITLE
Containers cant resolve other containers in the same docker compose network after Docker update v3.3.x

### ISSUE THREAD

**Issue by a7ul** [docker/for-mac#5616]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 225A08E5-C48D-4E19-BE25-0BBAE8E9AD6B/20210422151048

### Expected behavior

Containers should be able to talk to each other in the same network using the docker compose network name.

### Actual behavior
```
database-setup_1  | psql: error: could not translate host name "db" to address: Name or service not known
```

### Information
 
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes after upgrading docker for mac from v3.2.x to v3.3.x
  - A reproducible case if this is a bug, Dockerfiles FTW. - See below.
 
  - macOS Version: BigSur 11.2.3
  - Intel chip or Apple chip: Intel chip
  - Docker Desktop Version: 3.3.1 (63152)

### Steps to reproduce the behavior

The example below works with docker for mac v3.2.x 
If you upgrade to v3.3.x

You get the following error when `database-setup` container tries to connect to the postgres instance.

```
database-setup_1  | Ensuring database: postgres
database-setup_1  | psql: error: could not translate host name "db" to address: Name or service not known
```

Create a new repo with two files `docker-compose.yaml` and `initdbs.sh` with the following contents.

`docker-compose.yaml`

```yaml
version: "3.9"

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:12
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    networks:
      main:
        aliases:
          - db

  database-setup:
    image: postgres:12
    volumes:
      - ./initdbs.sh:/initdbs.sh
    depends_on:
      - postgres
    command: bash /initdbs.sh
    networks:
      main:
        aliases:
          - database-setup

networks:
  main:


```

`initdbs.sh`

```sh
#!/bin/bash
set -e

create_database () {
   echo "Ensuring database: $1"
   echo "SELECT 'CREATE DATABASE $1' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$1')\gexec" | psql postgres://postgres:secret@db
}


create_database postgres
create_database test1
create_database test2
create_database test3
create_database test4
create_database test5

```

Now run

```
 docker compose up
```

The following setup works in docker for mac v3.2.x but not in v3.3.x
Downgrading from 3.3.x solves the issue.
