### ISSUE TITLE
I/O Delay since ever on Apple M1 when using many Containers

### ISSUE THREAD

**Issue by venomone** [docker/for-mac#5626]
Hey Folks,

can anybody imagen where the following behaviour comes from: When I execute my whole stack (Around 8 Continers, including Redis, Elasticsearch, MariaDB (not MySQL), Python) I always run into some kind of IO delay it seems. The Projekt comes up fine but when I try to exec some functions of my Programm I very often have to wait 3-5 sec before I get any response, even if the function is at a very low complexitiy like a simple filter statement.

Since the M1 Version has been updated to 3.3.1 I also see some Improvements on the RAM management. Docker does less swapping it seems. Thanks for that fix! But sadly that hasen't solved my issue.

I tried both virtualization types Docker Desktop offers under the experimental Tab but with the same result :(

Can smb. Help?

Kind regards and Thanks in advance

**Comment by SwenVanZanten** [comment]
Hi I have the same issue, running 3.3.3 over here.
When I do a curl request from one container to another.
It always happens to be ~5 seconds and happens randomly.

```
docker-compose exec php curl http://statics:4000/manifest.json -w %{time_connect}:%{time_starttransfer}:%{time_total}
{
  "_hash": "v1619773217126",
  "js/activate-js.js": "js/activate-js.js",
  "js/m.js": "js/m.js"
} 5.118593:5.118996:5.119123
```

```
docker-compose exec php curl http://statics:4000/manifest.json -w %{time_connect}:%{time_starttransfer}:%{time_total}
{
  "_hash": "v1619773217126",
  "js/activate-js.js": "js/activate-js.js",
  "js/m.js": "js/m.js"
} 0.004253:0.004689:0.004720
```

**Comment by SwenVanZanten** [comment]
Okay looks like it is caused by DNS resolving. After adding dedicated IP's and add them to my images host files it was resolved and I get a quick respons every request.

**Comment by ruudk** [comment]
I notice the same. Connecting to Redis from PHP sometimes takes a few seconds because resolving `redis` hostname is slow. When I change the hostname to the ip of the container, it's fast again.

**Comment by markshust** [comment]
@SwenVanZanten what are the exact steps you did to resolve this issue? I'm noticing the same thing happening on the new M1X chip.

**Comment by markshust** [comment]
Never mind, figured it out. This is definitely a confirmed issue with Docker for Mac on Apple Silicone.

```
❯ docker-compose exec phpfpm curl http://elasticsearch:9200/manifest.json -w %{time_connect}:%{time_starttransfer}:%{time_total}

{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [manifest.json]","resource.type":"index_or_alias","resource.id":"manifest.json","index_uuid":"_na_","index":"manifest.json"}],"type":"index_not_found_exception","reason":"no such index [manifest.json]","resource.type":"index_or_alias","resource.id":"manifest.json","index_uuid":"_na_","index":"manifest.json"},"status":404}5.101758:5.105394:5.105483%                                                                                      ❯ docker-compose exec phpfpm curl http://172.17.0.1:9200/manifest.json -w %{time_connect}:%{time_starttransfer}:%{time_total}

{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [manifest.json]","resource.type":"index_or_alias","resource.id":"manifest.json","index_uuid":"_na_","index":"manifest.json"}],"type":"index_not_found_exception","reason":"no such index [manifest.json]","resource.type":"index_or_alias","resource.id":"manifest.json","index_uuid":"_na_","index":"manifest.json"},"status":404}0.000886:0.008343:0.008373%     
```

**Comment by markshust** [comment]
A potential workaround, instead of using the ip, is to use:

`host.docker.internal`

The services defined in the `docker-compose.yml` file don't seem to be resolving to this internal hostname.

**Comment by markshust** [comment]
I can also confirm that the `host.docker.internal` hostname also fails lookups randomly 😅

The only way to get rid of the lag is to add an entry to the container's `/etc/hosts` file:

```
172.17.0.1 host.docker.internal
```

Then use `host.docker.internal` everywhere rather than the service name.

**Comment by jayfk** [comment]
Maybe I'm missing something, but how is hardcoding an IP address to `host.docker.internal` helping to resolve other  services? Do you do this for all your services?

**Comment by markshust** [comment]
@jayfk I actually went with the names of the services instead. But, this will just force-resolve the DNS for that name to the ip of Docker, which definitely fixes this I/O issue:

https://github.com/markshust/docker-magento/blob/master/compose/docker-compose.yml#L28-L37

**Comment by SwenVanZanten** [comment]
I solved this by doing the following:

docker-compose.yml
```
version: "3.8"

x-extra_hosts: &extra_hosts
    extra_hosts:
        - "service-a:172.20.0.4"
        - "service-b:172.20.0.5"
        - "service-c:172.20.0.6"

services:
    service-a:
        <<: *extra_hosts
        networks:
            default:
                ipv4_address: 172.20.0.4

    service-b:
        <<: *extra_hosts
        networks:
            default:
                ipv4_address: 172.20.0.5

    service-c:
        <<: *extra_hosts
        networks:
            default:
                ipv4_address: 172.20.0.6

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: "172.20.0.0/24"
```

Define a network so you can fix the subnet.
Assign IP's to the different services.
And define a hosts list where every service knows which service is which IP than assign that list to every service.

**Comment by pinktig** [comment]
> I solved this by doing the following:
> 
> docker-compose.yml
> 
> ```
> version: "3.8"
> 
> x-extra_hosts: &extra_hosts
>     extra_hosts:
>         - "service-a:172.20.0.4"
>         - "service-b:172.20.0.5"
>         - "service-c:172.20.0.6"
> 
> services:
>     service-a:
>         <<: *extra_hosts
>         networks:
>             default:
>                 ipv4_address: 172.20.0.4
> 
>     service-b:
>         <<: *extra_hosts
>         networks:
>             default:
>                 ipv4_address: 172.20.0.5
> 
>     service-c:
>         <<: *extra_hosts
>         networks:
>             default:
>                 ipv4_address: 172.20.0.6
> 
> networks:
>     default:
>         ipam:
>             driver: default
>             config:
>                 - subnet: "172.20.0.0/24"
> ```
> 
> Define a network so you can fix the subnet. Assign IP's to the different services. And define a hosts list where every service knows which service is which IP then assign that list to every service.

Thanks for this. I've been having exact same issue with 16" MacBook Pro with M1 Pro chip. 
In my case I had to unquote subnet setting as follow: 
`networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/24 # unquote IP address
`

**Comment by SwenVanZanten** [comment]
> Thanks for this fix, @SwenVanZanten. I've been having exact same issue with 16" MacBook Pro with M1 Pro. 
> 
> 
> 
> In my case, I was running Django server on docker-compose and response from Django server was delayed approximately 5 seconds for no apparent reason. I wasted quite some time until I figured out that it was the issue with my codebase. 
> 
> 
> 
> I've applied your fix and now it works fine. In my case I had to unquote subnet setting as follow: 
> 
> 
> 
> ```
> 
> networks:
> 
>     default:
> 
>         ipam:
> 
>             driver: default
> 
>             config:
> 
>                 - subnet: 172.20.0.0/24 # unquote IP address
> 
> ```

Awesome! Now let's hope this issue finally gets fixed so this work around isn't needed

**Comment by bweinzierl** [comment]
Ran into the same issue, took me quite some time to figure it out. Hope this will get fixed soon. The described workaround worked for me too...

**Comment by pinktig** [comment]
> 

Hi, @SwenVanZanten, just in case if you're still following this issue, I found another solution that worked for me. @annemarietannengrund suggested this in #5548, and now it seems to be working normally so far. If your base image is buster(-slim), upgrading to bullseye(-slim) might solve this issue. 

At least it worked for me!

**Comment by SwenVanZanten** [comment]
> Hi, @SwenVanZanten, just in case if you're still following this issue, I found another solution that worked for me. @annemarietannengrund suggested this in #5548, and now it seems to be working normally so far. If your base image is buster(-slim), upgrading to bullseye(-slim) might solve this issue.
> 
> At least it worked for me!

Yup that solved the problem #:+1:

**Comment by folkvir** [comment]
Any news on this? 
I still have to use fixed ip addresses in my configurations otherwise I always get a 5 seconds latency between my containers. Something like that is not convenient at all to use:
```yaml
version: "3.7"

networks:
  default:
    ipam:
      config:
        - subnet: "172.25.0.0/24"
          gateway: "172.25.0.1"

x-extra_hosts: &extra_hosts
    extra_hosts:
        - "mysql:172.25.0.2"

services:
  server:
     depends_on:
        - mysql
     <<: *extra_hosts

  mysql:
    <<: *extra_hosts
    networks:
      default:
        ipv4_address: 172.25.0.2
```
My setup is working correctly on older Macbook without M1 chips without the ip addressing. 
Is it related to my containers? Or related to internal docker name resolving with M1?
