### ISSUE TITLE
Docker desktop(3.3.3) docker-compose up is slow(at least 12 seconds), and logs are empty or incomplete.

### ISSUE THREAD

**Issue by jjqq2013** [docker/for-mac#5683]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
- when docker-compose up shows "creating xxx...conainter", it should finish soon, like in previous Docker (3.2.1),  8 containers takes around 0.1s.

- logs in Dashboard should be complete
 
### Actual behavior
- like in previous Docker (3.2.1),  8 containers takes around 0.1s in the "creating xxx..container" stage, but now it takes 12 seconds.

- logs of some containers are empty or incomplete. Note, this issue also exists in Windows version.

### Information

  - macOS Version: macOS Catalina
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.3

### Steps to reproduce the behavior

 The first issue(docker-compose up slow) can be reproduced by following steps
 ```
#!/bin/bash
set -e -o pipefail
mkdir -p test-docker-compose-up
cd test-docker-compose-up
cat <<EOF > docker-compose.yml
version: "3.4"

services:
  svc1:
    image: alpine
    command: [echo, hi]
  svc2:
    image: alpine
    command: [echo, hi]
  svc3:
    image: alpine
    command: [echo, hi]
  svc4:
    image: alpine
    command: [echo, hi]
  svc5:
    image: alpine
    command: [echo, hi]
  svc6:
    image: alpine
    command: [echo, hi]
  svc7:
    image: alpine
    command: [echo, hi]
  svc8:
    image: alpine
    command: [echo, hi]
EOF
docker-compose up

echo ============begin test docker-compose up===========
time docker-compose up
echo ============end===========
```
  

 But the second issue(logs incomplete), I can not reproduce, but often seen the issue.
