### ISSUE TITLE
Volumes are not removed with `docker compose down --volumes`

### ISSUE THREAD

**Issue by hiroy** [docker/for-mac#5709]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I tried `docker compose down --rmi all --volumes --remove-orphans`, but the volumes were not removed.

### Actual behavior

The volumes defined with `docker-compose.yml` are not removed.
As I try `docker-compose down --rmi all --volumes --remove-orphans`, all the volumes are removed clearly.

My `docker-compose.yml` is like below:
```yml
version: "3.8"
networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.10.0/24
volumes:
  foo_pgsql:
  bar_pgsql:
  baz_pgsql:
...
```

### Information

  - macOS Version: 11.3
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.3 (64133) 

### Steps to reproduce the behavior

  1. `docker compose up` with volume-defined `docker-compose.yml`
  1. docker stop with ^C key
  1. `docker compose down --rmi all --volumes --remove-orphans`
