### ISSUE TITLE
uncaught target signal 6 (Aborted) - core dumped when running bitnami/neo4j:4-debian-10

### ISSUE THREAD

**Issue by nashid** [docker/for-mac#5724]
- [x] I have tried with the latest version of Docker Desktop
- [  ] I have tried disabling enabled experimental features
- [  ] I have uploaded Diagnostics
 
### Expected behavior
Image runs using qemu.

### Actual behavior
Container crashes with error.

```
plume-neo4j | Welcome to the Bitnami neo4j container
plume-neo4j | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-neo4j
plume-neo4j | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-neo4j/issues
plume-neo4j |
plume-neo4j | nami    INFO  Initializing neo4j
plume-neo4j | neo4j   INFO  Setting initial password...
plume-neo4j | Error executing 'postInstallation': qemu: uncaught target signal 6 (Aborted) - core dumped
plume-neo4j |
plume-neo4j exited with code 1
```

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior
docker-compose -f neo4j.yml up

neo4j.yml up
```
version: '3'
services:
  neo4j:
    image: bitnami/neo4j:4-debian-10
    container_name: plume-neo4j
    environment:
      NEO4J_PASSWORD: "neo4j123"
    ports:
      - "7687:7687"
      - "7474:7474"
    healthcheck:
      test: perl -MIO::Socket::INET -e 'exit(! defined( IO::Socket::INET->new("localhost:7687")))'
      interval: 5s
      timeout: 10s
      retries: 5
    stdin_open: true
    tty: true
```
