### ISSUE TITLE
Docker Desktop cannot see environment variables

### ISSUE THREAD

**Issue by Toberumono** [docker/for-mac#5745]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: N/A - doesn't actually get far enough to throw an error

### Expected behavior
Docker compose command allows referencing multiple files. Paths to those files can contain environment variables ex: docker-compose -f 'docker-compose.yml' -f "${COMMON_FILES}/common-configuration.yml". In versions prior to 3.4.0, these images could be managed via Docker Desktop. Managing an image for me primarily means stopping and/or removing it.

### Actual behavior
Docker Desktop now throws an error when attempting to interact with these images, says that it cannot find the "common-configuration.yml" file. Copying that file into the root directory of the project allows Docker Desktop to find the file, but then it says that "${COMMON_FILES}" (which is also referenced in the "common-configuration.yml" file) is not defined, and fails again.

### Information

  - macOS Version: 10.15.7
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.4.0

### Steps to reproduce the behavior

  1. Create a Container with docker-compose that references any environment variable
  2. Try to remove the container from Docker Desktop

Minimum files (I think these should work. Our build process is a lot more involved):
docker-compose.yml:
```
version: "3.8"

services:
  tomcat:
    image: tomcat:9-jdk16-openjdk-slim
    ports:
      # Without the '0.0.0.0' we can't connect to from WSL/Ubuntu.
      - "0.0.0.0:${WEB_PORT}:80"
      - "0.0.0.0:${WEB_PORT_SSL}:443"
      - "0.0.0.0:8000:8000"
    volumes:
      - ./:/workspace/website
```

common-configuration.yml (must be in a separate directory)
```
version: "3.8"

services:
  tomcat:
    ports:
      - "0.0.0.0:8849:8849"
    volumes:
      - ${COMMON_FILES}/target/tomcat/lib-common:/usr/local/tomcat/lib-common
      - ${COMMON_FILES}:/workspace/project-master/core-master
```

bash code (The COMMON_FILES variable can be any valid path)
```
cd /Users/testing/Documents/workspace/test-project
export COMMON_FILES=/Users/testing/Documents/workspace/project-master/core-master
docker-compose -f './docker-compose.yml' -f "${COMMON_FILES}/common-configuration.yml" up
```
