### ISSUE TITLE
Error response from daemon: Duplicate mount point: /var/lib/postgresql/data/

### ISSUE THREAD

**Issue by butuzov** [docker/for-mac#5758]
Issue happening with postgress container with docker volume (`postgress`) and mounted path (`./postgresql`). these two combination can't be used together, and failing with error. Once the physical directory renamed from `postgresql` to something else (e.g. `pgsql`) error is gone.

## Checklist
  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
 

### Expected behaviour

docker compose's described containers starts

### Actual behaviour

fails with error

### Information
 
Please, help us understand the problem.  For instance:
  - Is it reproducible?
    > yes
  - Is the problem new?
    > yes
  - Did the problem appear with an update?
    > yes
  - A reproducible case if this is a bug, Dockerfiles FTW.
    > see next info.

  - macOS Version: mojave
  - Intel chip or Apple chip: intel
  - Docker Desktop Version: v20.10.7

### Steps to reproduce the behavior
```yaml
version: '3.2'
services:

  postgres:
    ports:
      - 6432:5432
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/
      - ./postgresql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_MULTIPLE_DATABASES: db1,db2,db3

  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    volumes:
    - mongo:/data/db
    ports:
    - 27017:27017

volumes:
  postgres: {}
  mongo: {}

```

```shell
 > task up
task: [up] docker-compose -f .sandbox/docker-compose.yaml -p Project up -d postgres
[+] Running 3/1
 ⠿ Network Project_default    Created                                                                                                                                                                                           3.9s
 ⠿ Volume "Project_postgres"  Created                                                                                                                                                                                           0.0s
 ⠿ Volume "Project_mongo"     Created                                                                                                                                                                                           0.0s
 ⠋ Container postgres                 Creating                                                                                                                                                                                          0.1s
Error response from daemon: Duplicate mount point: /var/lib/postgresql/data/
```

**Comment by jkhulme** [comment]
Having the same issue 
```
[+] Running 9/11
 ⠿ Volume "flow_database-testdata"  Created                                                                                                                                                            0.1s
 ⠿ Volume "flow_redis"              Created                                                                                                                                                            0.0s
 ⠿ Volume "flow_node_cache"         Created                                                                                                                                                            0.0s
 ⠿ Volume "flow_database-data"      Created                                                                                                                                                            0.0s
 ⠼ Container flow_db_1              Creating                                                                                                                                                           0.4s
 ⠼ Container flow_testdb_1          Creating                                                                                                                                                           0.4s
 ⠿ Container flow_build_1           Created                                                                                                                                                            0.4s
 ⠿ Container flow_fakempdb_1        Created                                                                                                                                                            0.4s
 ⠿ Container flow_typecheck_1       Created                                                                                                                                                            0.3s
 ⠿ Container flow_redis_1           Created                                                                                                                                                            0.3s
 ⠿ Container flow_fakeid_1          Created                                                                                                                                                            0.3s
Error response from daemon: Duplicate mount point: /var/lib/postgresql/data
```

Relevant part of docker-compose
```
version: '3'
services:
  # postgres for flow development instance
  db:
    image: "postgres" # use latest official postgres version
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts downvolumes:
    environment:
        POSTGRES_DB: flow_dev
        POSTGRES_PASSWORD: password
        POSTGRES_USER: flow
    ports:
      - "8181:5432"
  # postgres for jest tests
  testdb:
    image: "postgres" # use latest official postgres version
    volumes:
      - database-testdata:/var/lib/postgresql/data/ # persist data even if container shuts downvolumes:
    environment:
        POSTGRES_DB: flow_test
        POSTGRES_PASSWORD: password
        POSTGRES_USER: flow
    ports:
      - "8182:5432"
...
volumes:
  database-data:
  database-testdata:
```
