### ISSUE TITLE
Cannot write to volumes: "PermissionError: [Errno 1] Operation not permitted" 

### ISSUE THREAD

**Issue by iacobfred** [docker/for-mac#5765]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 905FB324-9616-49E1-AF10-CCCBEDA1D4EF/20210617003141

### Expected behavior
Volume directories should be writable by containers.

### Actual behavior
Containers cannot write to volume directories.

### Information
I'm using Docker to run a Django application. The application depends on volumes for static files, media files, and database backups. Here is the config for my `django` service in my `docker-compose.yml`:

```
  django:
    command: bash config/scripts/init/django.sh
    depends_on:
      - postgres
      - redis
      - elasticsearch
    env_file: .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:8000/healthcheck/ || exit 1",
        ]
      timeout: 7s
      interval: 30s
      retries: 2
      start_period: 30s
    image: "ghcr.io/modularhistory/django:$SHA"
    ports:
      - "8000:8000"
    user: www-data
    volumes:
      - /var/lib/lxd/storage-pools/coresvcs/containers/webserver/rootfs/etc/letsencrypt:/etc/letsencrypt
      - ./.backups:/modularhistory/.backups
      - ./.init:/modularhistory/.init
      - ./_static:/modularhistory/_static
      - ./_media:/modularhistory/_media
```

In my `docker-compose.override.yml`, the above configuration is modified a bit. The main differences are that (1) the whole project directory (which contains the `.backups`, `.init`, `_static`, and `_media` directories) is added as a volume and (2) root user is specified:

```
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
      args:
        ENVIRONMENT: dev
    image: django:latest
    user: root
    volumes:
      - .:/modularhistory
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
```

Here is an excerpt from my Dockerfile (`Dockerfile.django`), in which the directories corresponding with the volumes are created and write permissions are granted:

```
# Create required directories.
RUN mkdir -p -- \
  /modularhistory/_static \
  /modularhistory/_media \
  /modularhistory/.backups \
  /modularhistory/.init \
  /opt/atlas

# Add source code.
COPY . /modularhistory/
COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh

# Grant necessary permissions to non-root user.
RUN chown -R www-data:www-data /modularhistory && \
  chmod g+w -R /modularhistory/_media && \
  chmod g+w -R /modularhistory/_static && \
  chmod g+w -R /modularhistory/.backups && \
  chmod g+w -R /modularhistory/.init && \
  chmod +x /usr/local/bin/wait-for-it.sh

# Switch from root to non-root user.
USER www-data
```

Here is the `django.sh` script that is run when the container is started:

```
#!/bin/bash

sleep 3 && wait-for-it.sh postgres:5432 --
python manage.py collectstatic --no-input || {
    echo "Failed to collect static files."
    exit 1
}
python manage.py runserver 0.0.0.0:8000
```

The `collectstatic` command above involves writing a bunch of static files to the `_static` directory, which is defined as a volume in docker-compose.yml.

This setup has worked well for several months (i.e., the Docker container was able to write in its volumes and start up successfully), but a few days ago, all of the volumes became unwritable. The Django container is no longer able to write static files to the `_static` volume, write db backup files to the `.backups` volume, etc.

Example error when attempting to collect static files (writing to `_static` volume):
```
django_1                        | Traceback (most recent call last):
django_1                        |   File "/modularhistory/manage.py", line 22, in <module>
django_1                        |     main()
django_1                        |   File "/modularhistory/manage.py", line 18, in main
django_1                        |     execute_from_command_line(sys.argv)
django_1                        |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
django_1                        |     utility.execute()
django_1                        |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
django_1                        |     self.fetch_command(subcommand).run_from_argv(self.argv)
django_1                        |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
django_1                        |     self.execute(*args, **cmd_options)
django_1                        |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
django_1                        |     output = self.handle(*args, **options)
django_1                        |   File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 194, in handle
django_1                        |     collected = self.collect()
django_1                        |   File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 118, in collect
django_1                        |     handler(path, prefixed_path, storage)
django_1                        |   File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 355, in copy_file
django_1                        |     self.storage.save(prefixed_path, source_file)
django_1                        |   File "/usr/local/lib/python3.9/site-packages/django/core/files/storage.py", line 54, in save
django_1                        |     return self._save(name, content)
django_1                        |   File "/usr/local/lib/python3.9/site-packages/django/core/files/storage.py", line 274, in _save
django_1                        |     fd = os.open(full_path, self.OS_OPEN_FLAGS, 0o666)
django_1                        | PermissionError: [Errno 1] Operation not permitted: '/modularhistory/_static/_topic_cloud.png'
django_1                        | Failed to collect static files.
```

Example error when writing to `_media` volume:
```
Error calling '_check_storage': [Errno 1] Operation not permitted: '/modularhistory/_media/django-watchman-6913fdf6-724b-45a4-958b-a0543dc31a08.txt'
django_1                        | Traceback (most recent call last):
django_1                        |   File "/usr/local/lib/python3.9/site-packages/watchman/decorators.py", line 28, in wrapped
django_1                        |     response = func(*args, **kwargs)
django_1                        |   File "/usr/local/lib/python3.9/site-packages/watchman/checks.py", line 63, in _check_storage
django_1                        |     path = default_storage.save(filename, ContentFile(content))
django_1                        |   File "/usr/local/lib/python3.9/site-packages/django/core/files/storage.py", line 54, in save
django_1                        |     return self._save(name, content)
django_1                        |   File "/usr/local/lib/python3.9/site-packages/django/core/files/storage.py", line 274, in _save
django_1                        |     fd = os.open(full_path, self.OS_OPEN_FLAGS, 0o666)
django_1                        | PermissionError: [Errno 1] Operation not permitted: '/modularhistory/_media/django-watchman-6913fdf6-724b-45a4-958b-a0543dc31a08.txt'
django_1                        | Intercepted Sentry event: <LogRecord: watchman, 40, /usr/local/lib/python3.9/site-packages/watchman/decorators.py, 47, "Error calling '%s': %s">
```

One thing I noticed while investigating is that when I spin up containers using docker-compose, all the directories corresponding to volumes become "locked":

<img width="779" alt="Screen Shot 2021-06-16 at 20 03 05" src="https://user-images.githubusercontent.com/25336795/122314666-787ce280-cecd-11eb-92ee-d0ca329ca2dc.png">

<img width="434" alt="Screen Shot 2021-06-16 at 20 07 00" src="https://user-images.githubusercontent.com/25336795/122314784-ac580800-cecd-11eb-8f4f-5b3da67866cf.png">

If I uncheck "Locked," the directory becomes writable. But whenever containers are started (`docker-compose up django`), the directory automatically is locked again (so is not writable).

  - macOS Version: Big Sur 11.4
  - Intel chip or Apple chip: Intel Core i9
  - Docker Desktop Version: 3.4.0 (65384)

This was caused by the Docker software update to 3.4.0. 
If I revert to Docker Desktop version 3.3.3, everything works as expected.
