### ISSUE TITLE
Kubernetes RBAC is not working until applying this fix

### ISSUE THREAD

**Issue by marcofranssen** [docker/for-mac#5784]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

RBAC is enforced

### Actual behavior

RBAC isn't enforced

### Information

There is a mistake in the `docker-for-desktop-binding` role binding in k8s.

### Howto fix the issue

Change the `docker-for-desktop-binding` role binding from:
 
```yaml
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
  namespace: kube-system
```

to: 

```yaml
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:kube-system
```

I'm also happy to provide a Pull Request, just not sure if that part is open sourced and where to provide.
