### ISSUE TITLE
MongoDB very slow on Docker - Macbook Air M1 - Big Sur

### ISSUE THREAD

**Issue by lilouch** [docker/for-mac#5785]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:EA6916E9-4875-474D-80ED-93FADBB9C409/20210624115127

### Expected behavior
Read data from my MongoDB almost instantly. On a colleague's macbook air (Intel 2019) with the same docker container, everything works perfectly and quickly.
On my windows laptop, same. 
On another macbook air from 2015, which has a very low configuration, it works almost great.

### Actual behavior
It is very slow. For example, just for this line, it takes literally about 9s. Nothing fancy. 

```
 client = MongoClient(
        'mongo', 27017, username=current_user, password=current_password)
    db_list = client.list_databases() # this line 
```

From the MongoDB doc
_"The listDatabases command provides a list of all existing databases along with basic statistics about them."_

From another personal function that take some items, it takes 128s whereas on the others computers, it takes about 1-2s.

It is really a pain to develop.

The only difference from the others laptop is the fact that mine is Macbook Air M1.

I tried different versions and the last one of Docker Desktop and still the same.
I tried with the latest version of MongoDB and the stable 4.4 and the same.

### Information
  - macOS Version: macOS Big Sur 11.4
  - Intel chip or Apple chip: Apple M1
  - Docker Desktop Version: 3.5

Have other people experienced this?

Thank for your help !

**Comment by stephen-turner** [comment]
Are you using an Intel (amd64) container or an Arm container? Intel containers are emulated on Arm hardware, and are likely to be slow.

**Comment by lilouch** [comment]
How do I know that ?

**Comment by stephen-turner** [comment]
If you're using 3.5.0 then in the container list, there's a little badge for containers on the non-native architecture.

**Comment by lilouch** [comment]
<img width="1038" alt="2021-06-25_08-28-31" src="https://user-images.githubusercontent.com/8614763/123380193-7252ca00-d58f-11eb-9573-118942d443d0.png">

It seems that I don't have any badge...

**Comment by stephen-turner** [comment]
OK, that's not the problem then. So next question: are you using the new MacOS virtualization framework in the experimental settings? That has known filesystem performance problems.

**Comment by lilouch** [comment]
the box was unchecked. So I checked the box, delete my container and rebuild everything using docker-compose --build.

Still the same time...

<img width="859" alt="2021-06-25_09-41-52" src="https://user-images.githubusercontent.com/8614763/123389011-bb0f8080-d599-11eb-9176-7533c51faffa.png">

**Comment by stephen-turner** [comment]
In fact I would recommend _not_ using the new virtualization framework.

Where is the data for the database stored? Are you bind mounting it from the host (which I would not recommend for a database), or is it in a docker volume or inside the container's filesystem?

**Comment by lilouch** [comment]
Ok, I've unchecked the box.
Should I check as well "Use gRPC FUSE for file sharing" which is already checked per default ?

As I'm not sure to understand well your question, here my docker-compose.

```
version: "3"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME:''
      MONGO_INITDB_ROOT_PASSWORD:''
    networks:
      - app_net
    volumes:
      - shared_db:/data/db

  aiCore:
    build: ./docker/aiCore
    image: aiCore
    container_name: aiCore
    command: gunicorn --timeout 2000 --bind 0.0.0.0:5000 -w 12 coreApp:app
    depends_on:
      - redis
    expose:
      - 5000
    networks:
      - app_net
    volumes:
      - ./docker/aiCore/:/app
      - ./mgh/:/app/ai/mgh

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    networks:
      - app_net

  nginx_core:
    build: ./docker/nginx_core
    image: nginx_core
    container_name: nginx_core
    ports:
      - 1906:1906
    depends_on:
      - aiCore
    networks:
      - app_net

  appFront:
    build:
      context: ./docker/app_front
      target: debug
    image: app_front
    container_name: app_front
    command: gunicorn --timeout 2000 --bind 0.0.0.0:5008 -w 4 FrontApp:app --reload --log-level debug
    depends_on:
      - nginx_core
    ports:
      - "5008:5008" # app port
    networks:
      - app_net
    volumes:
      - ./docker/app_front/:/app
      - ./mgh/:/app/mgh

    stdin_open: true
    tty: true

  nginx_front:
    build: ./docker/nginx_front
    image: nginx_front
    container_name: nginx_front
    ports:
      - 80:80
      - 443:443
    depends_on:
      - appFront
    networks:
      - app_net

networks:
  app_net:

volumes:
  shared_db:
```

I have for mongodb
    **volumes:
      - shared_db:/data/db**

So it means that it is stored on the volume right ?

**Comment by stephen-turner** [comment]
Yes, that's on the volume, so it should be OK.

That also means that the file sharing setting won't make a difference to the database. It could make a difference to the aiCore or appFront containers if they have heavy traffic: you could try it, but it doesn't sound like that's likely to be the problem.

To be honest, I'm getting a bit stuck here. I think we've been through all the normal reasons for slow performance.

**Comment by lilouch** [comment]
I'm the only one who experimenting this ?

There is no way to diagnostic or to do something ?

Anyway, thank for your help.

**Comment by lilouch** [comment]
In order to reproduce the steps, I did something very simple. A simple Flask APP with nginx and MongoDB

**docker-compose.yml**

```
version: '3'

services:
    flask:
        build:
            context: app
            dockerfile: Dockerfile
        container_name: flask
        image: digitalocean.com/flask-python:3.6
        restart: unless-stopped
        environment:
            APP_ENV: "debug"
            APP_DEBUG: "True"
            APP_PORT: 5000
            MONGODB_DATABASE: flaskdb
            MONGODB_USERNAME: test
            MONGODB_PASSWORD: test
            MONGODB_HOSTNAME: mongodb
        volumes:
            - appdata:/var/www
        depends_on:
            - mongodb
        networks:
            - frontend
            - backend
        stdin_open: true
        tty: true
    
    mongodb:
        image: mongo:4.0.8
        container_name: mongodb
        restart: unless-stopped
        command: mongod --auth
        expose:
            - 27017
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongodbuser
            MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password
            MONGO_INITDB_DATABASE: flaskdb
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        volumes:
            - mongodbdata:/data/db
        networks:
            - backend
        


    webserver:
        build:
            context: nginx
            dockerfile: Dockerfile
        image: nginx
        container_name: webserver
        restart: unless-stopped
        environment:
            APP_ENV: "debug"
            APP_NAME: "webserver"
            APP_DEBUG: "true"
            SERVICE_NAME: "webserver"
        ports:
            - 80:80
            - 443:443
        volumes:
            - nginxdata:/var/log/nginx
        depends_on:
            - flask
        networks:
            - frontend
        
networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local
    nginxdata:
        driver: local
```

**app.py**

```
import os
from flask import Flask, request, jsonify
from flask_pymongo import PyMongo
import time

from pymongo import MongoClient

application = Flask(__name__)

application.config["MONGO_URI"] = 'mongodb://' + os.environ['MONGODB_USERNAME'] + ':' + \
    os.environ['MONGODB_PASSWORD'] + '@' + os.environ['MONGODB_HOSTNAME'] + \
    ':27017/' + os.environ['MONGODB_DATABASE']

mongo = PyMongo(application)
db = mongo.db


@application.route('/')
def index():
    username = os.environ['MONGODB_USERNAME']
    password = os.environ['MONGODB_PASSWORD']
    tic = time.perf_counter()
    client = MongoClient('mongo', 27017, username=username, password=password)
    toc = time.perf_counter()
    print(f"Get client login in {toc - tic:0.4f} seconds")

    tic = time.perf_counter()
    list(client.list_databases())
    toc = time.perf_counter()
    print(f"Get list client login in {toc - tic:0.4f} seconds")

    return jsonify(
        status=True,
        message='Welcome to the Dockerized Flask MongoDB app!'
    )

```

I have the same results.

**list(client.list_databases())** take about 10-15s to perform.

I really don't understand and it is very a pain to work with this kind of latence.

![image](https://user-images.githubusercontent.com/8614763/123424220-db9f0100-d5c0-11eb-9021-630b0c259801.png)
