### ISSUE TITLE
Ping by hostname in compose does not work from 3.4.0

### ISSUE THREAD

**Issue by boskiv** [docker/for-mac#5788]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

### Expected behavior
DNS works
### Actual behavior
DNS does not work
### Information

  - macOS Version: 11.4
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.5.0

### Steps to reproduce the behavior

```
version: '3'
services:
    postgres:
        image: postgres
    python:
        image: python
        depends_on:
          - postgres
```

```
docker compose run python bash
ping postgres
```

Output
```
root@17caf6cfde91:/# ping postgres
ping: postgres: Name or service not known
```

PS. This stop works from Docker Desktop for Mac after upgrading to 3.4.0
