### ISSUE TITLE
Sudden I/O errors with docker-compose

### ISSUE THREAD

**Issue by alcappello** [docker/for-mac#5929]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8844440C-6095-48BC-935D-126C12430762/20210824140953

### Expected behavior
Volumes shared between host machine and containers should always be accessible inside a running container.
### Actual behavior
From time to time (varying between hours and days) the files shared with containers in project stop to be available inside the containers. Conteinerized applications start to throw I/O errors, while the same files are still accessible from MacOS. A "reset to factory defaults" in Docker solves the problem, a OS reboot also does, while a `docker system prune -a` doesn't, nor does a `docker-compose restart`.
### Information
The project I'm working on has a docker-compose environment for development, and all of a sudden multiple containers start to have I/O errors like this one:
```typescript
Error: EIO: i/o error, open '/usr/app/src/components/common/FilterComponent.tsx'
```
NGINX crashes for the same reason, and so on:
```
nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (5: Input/output error)
```

Docker has enough disk space (112GB avail/32GB used), everything else on my Mac seems to work fine. The only way to make it work again is a Docker factory reset or a MacOS reboot, until it happens again (usually ~1-2 days).

This is the docker-compose.yml file:

```yaml
x-env-files: &env-files
  env_file:
    - docker.env
version: '3.3'
services:
  mongo-store:
    image: mongo:latest
    volumes:
      - /data/db
    ports:
      - 27017:27017
    networks:
      - backend
    command: ['mongod', '--bind_ip', '0.0.0.0']
  application-ui:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: application-ui:dev
    ports:
      - 5000:5000
    networks:
      - frontend
    stdin_open: true
    volumes:
      - ./src/:/usr/app/src/
    command: ['npm', 'run', 'start']

  application-service:
    build:
      context: ../application-service
      dockerfile: Dockerfile-local
    image: application-service:dev
    ports:
      - 9000:9000
    networks:
      - backend
      - frontend
    environment:
      - 'GITLAB_TOKEN=${GITLAB_TOKEN}'
    <<: *env-files
    volumes:
      - ../application-service/src/:/usr/app/src/
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
      - frontend
networks:
  backend:
  frontend:
```

I've never seen this happen before, it just started a couple of weeks ago. It doesn't happen all the time, everything works fine for hours, sometimes days, and then it crashes. None of my colleagues working on the same project has had the same problem. I can't see any pattern in how it happens or what could trigger the behavior.

  - macOS Version: 11.5.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.6.0
