### ISSUE TITLE
High CPU after upgrade to v4 (M1 Mac)

### ISSUE THREAD

**Issue by leimantas** [docker/for-mac#5945]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: ADDA7BE5-4290-4EE6-9DD2-2C3A791E77C1/20210903070947
  - Diagnostics ID: ADDA7BE5-4290-4EE6-9DD2-2C3A791E77C1/20210903072806

### Actual behavior
High CPU after docker-compose up. Even idle is over 100%
![image](https://user-images.githubusercontent.com/46538777/131966047-57466991-a6f2-4ea5-b560-7804b8de417f.png)
![image](https://user-images.githubusercontent.com/46538777/131966080-91e06ee6-001a-4ef9-b64e-501970da2086.png)
![image](https://user-images.githubusercontent.com/46538777/131966417-a6a408db-f25e-42a8-867d-4abe11ced2a5.png)

### Information

  - macOS Version: 11.5.2
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: 4.0.0

### Steps to reproduce the behavior

  1. Launch node v16 or python image with docker-compose.
  2. Do nothing and watch the CPU.

```
version: "3.4"
services:
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  odoo:
    image: wbms/odoo14-multiarch
    ports:
      - 8069:8069
    depends_on:
      - db
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ..:/mnt/extra-addons
      - ~/.ssh:/root/.ssh-localhost:ro
      - odoo_data:/var/lib/odoo_dev
      - dev_extensions:/home/odoo/.vscode-server
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  db_data:
  odoo_data:
  dev_extensions:
```
