### ISSUE TITLE
Kubernetes Cluster Reset does not remove Persistent Volumes in Docker VM

### ISSUE THREAD

**Issue by gregbook** [docker/for-mac#6010]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Dynamically Kubernetes Persistent Volumes should be deleted from `/var/lib/k8s-pvs/` when Kubernetes cluster reset is triggered

### Actual behavior

Folder/Files are still present under `/var/lib/k8s-pvs/<volume-claim-name>/<pvc-xxxx>/` even after a Kubernetes cluster reset

### Information
  - Is it reproducible? Yes
  - Is the problem new? Unsure
  - Did the problem appear with an update? Unsure
  - macOS Version: macOS 11.6 (20G165)
  - Intel chip or Apple chip: Intel Chip
  - Docker Desktop Version: 4.1.0 (69386)

### Steps to reproduce the behavior
Here is the state of the Docker Desktop VM before creating pv,pvcs

```
❯ docker run -it --rm --privileged --pid=host alpine:edge nsenter -t 1 -m -u -n -i ls -al /var/lib/k8s-pvs
total 8
drwxr-xr-x    2 root     root          4096 Oct 14 12:56 .
drwxr-xr-x   18 root     root          4096 Oct 14 12:56 ..
```

Only the default storage class is present

```
NAMESPACE   NAME                                             PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
            storageclass.storage.k8s.io/hostpath (default)   docker.io/hostpath   Delete          Immediate           false                  40m
```

This is the manifest I am using to create dynamically a Persistent Volume. 

- One Persistent Volume Claim that will use the default storage class of the Docker Desktop Kubernetes Cluster
- One pod that define a volume from the PVC, mount it in `/tmp` and then create a file in this directory

`kubectl apply -f docker-test-volume-claim.yaml`

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  restartPolicy: Never
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-volume-claim
  containers:
    - name: test-container
      image: "alpine"
      command: ["touch", "/tmp/file-from-pod.txt"]
      volumeMounts:
        - name: test-volume
          mountPath: /tmp
```

Here is the state of volumes `kubectl get pv,sc,pvc`

```
NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                       STORAGECLASS   REASON   AGE
persistentvolume/pvc-a8495f91-4a58-43bd-840a-80e502c17ed9   128Mi      RWO            Delete           Bound    default/test-volume-claim   hostpath                2m41s

NAMESPACE   NAME                                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
default     persistentvolumeclaim/test-volume-claim   Bound    pvc-a8495f91-4a58-43bd-840a-80e502c17ed9   128Mi      RWO            hostpath       2m41s

NAMESPACE   NAME                                             PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
            storageclass.storage.k8s.io/hostpath (default)   docker.io/hostpath   Delete          Immediate           false                  45m
```

And we can see from the Docker Desktop VM the file created from the pod

```
# ls -al /var/lib/k8s-pvs/test-volume-claim/pvc-a8495f91-4a58-43bd-840a-80e502c17ed9
total 8
drwxrwxrwx    2 root     root          4096 Oct 14 13:43 .
drwxr-xr-x    3 root     root          4096 Oct 14 13:43 ..
-rw-r--r--    1 root     root             0 Oct 14 13:43 file-from-pod.txt
```

From the host go in Docker Desktop Troubleshoot panel and click on `Reset Kubernetes Cluster` or directly call the gui-api socket with `curl --unix-socket ~/Library/Containers/com.docker.docker/Data/gui-api.sock -XPOST http://./kubernetes/reset`

After Kubernetes reset, pv and pvc have been deleted

```
NAMESPACE   NAME                                             PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
            storageclass.storage.k8s.io/hostpath (default)   docker.io/hostpath   Delete          Immediate           false                  8s
```

But the file from the previous persistent volume is still present in the VM mount

```
# ls -altr /var/lib/k8s-pvs/test-volume-claim/pvc-a8495f91-4a58-43bd-840a-80e502c17ed9/
total 8
drwxr-xr-x    3 root     root          4096 Oct 14 13:43 ..
-rw-r--r--    1 root     root             0 Oct 14 13:43 file-from-pod.txt
drwxrwxrwx    2 root     root          4096 Oct 14 13:43 .
```

> Note: The `pvc-xxx` folder in the VM disapears when running `kubectl delete -f docker-test-volume-claim.yaml` but `/var/lib/k8s-pvs/test-volume-claim/` remains - not sure it's the expected behavior
