### ISSUE TITLE
Docker Compose ports has unexpected behavior

### ISSUE THREAD

**Issue by gmmeyer** [docker/for-mac#6014]
If you are using two dockerfiles and in one you add definitions to the container you can no longer do this after the most recent version of docker. This is a simplified version of my dockerfile with redis in the place of building the package I was building, but it should work the same:

Dockerfile1.yaml:
```yaml
version: "3.8"
services:
  my_service:
    image: redis
    ports:
      - "3000:3000"

```

Dockerfile2yaml:
```yaml
version: "3.8"
services:
  my_service:
    image: redis
    ports:
      - "3000:80"
```

You will now get this error:
```
Error response from daemon: driver failed programming external connectivity on endpoint test-my_service-1 (47137f9cde37661b74e9dacb0daa11503e593276e3d303b3bb666d8d97aa79d1): Bind for 0.0.0.0:3000 failed: port is already allocated
```

This error is brand new and did not happen until the most recent version, it should be fixed!

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CA2B2026-1C6F-4CC4-9A90-4F0F9F484DCF/20211019215305

### Information

  - macOS Version: 11.6
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.1.1

### Steps to reproduce the behavior

  1. ...
  2. ...
