### ISSUE TITLE
Apple M1 Pro Chip error: "qemu: uncaught target signal 11 (Segmentation fault) - core dumped"

### ISSUE THREAD

**Issue by RoniFinTech** [docker/for-mac#6089]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
localhost:8080/console to load and not see the error when clicking on the container in Docker Desktop.

### Actual behavior
```qemu: uncaught target signal 11 (Segmentation fault) - core dumped```
and can't load `localhost:8080/console`
### Information

  - macOS Version: Monterey
  - Intel chip or Apple chip: M1 Pro
  - Docker Desktop Version: 4.3.0 (71786) 
  - Docker version 20.10.11, build dea9396

### Steps to reproduce the behavior
download docker from here:
https://docs.docker.com/desktop/mac/apple-silicon/

run `docker-compose up` on this docker-compose file

```
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.0.10
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
```
