### ISSUE TITLE
Unable to mount HostPath

### ISSUE THREAD

**Issue by ikaven1024** [docker/for-mac#6123]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
create pod and mount host path

### Actual behavior
under mount path, ls result is different between host and container

### Information

  - macOS Version: 11.4
  - Intel chip or Apple chip: Apple chip
  - Docker Desktop Version: Docker Desktop 4.3.2 (72729) 

### Steps to reproduce the behavior

  1. create a nginx deploy with host path
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
     ...
      containers:
      - image: nginx:alpine
        - mountPath: /tmp
          name: tmpdir
          readOnly: true
      volumes:
      - hostPath:
          path: /tmp/
          type: Directory
        name: tmpdir
    ...
```
  2.  when pod is running, 
```shell
➜  ~ kubectl exec -ti nginx-747b45886b-mwcjv -- ls /tmp
do-not-delete-cni-config  pty242612806              runc-process168838893
```
but on host, `ls /tmp` is different.
```
➜  ~ ls /tmp/
aciseposture.pid             com.sangfor.ca.verification  ev-NXOa6P                    safeq-didi
boost_interprocess           com.sangfor.lockcert         fseventsd-uuid               sangfor.ec.rundata
com.apple.launchd.lplIXzHab7 com.sangfor.lockecagent      powerlog                     stop_easyconnect.sh
com.google.Keystone          com.sogou.inputmethod        rancher-desktop
com.sangfor.ca.sha           ev-369Fdn                    rules
```

  3. but when i create a  container with docker
```shell
➜  ~ docker run --rm -v /tmp:/tmp/ nginx:alpine ls /tmp
```
this show right!

  4. /tmp dir is config in file sharing
![image](https://user-images.githubusercontent.com/17907604/148023787-07fe63c5-5e9b-41d3-80c9-6cf0af57fe78.png)
