### ISSUE TITLE
docker-compose run <item> starts every item in the file instead of the selected ones

### ISSUE THREAD

**Issue by qhenkart** [docker/for-mac#6266]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [no] I have uploaded Diagnostics
  - Diagnostics ID:
  - I have already reverted to an earlier working version

### Expected behavior

docker-compose run <item> should only start the selected items

### Actual behavior

docker-compose run <item> starts every item in the docker-compose file

### Information

  - macOS Version: Latest
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: Latest

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
I've already reverted, I cannot output this information
### Steps to reproduce the behavior

docker-compose.yml
```

mongo-client:
    image: mongo:5.0.2
    stdin_open: true
    tty: true
    command: mongosh mongodb://mongo:27017/db
    depends_on:
      - mongo
mongo:
    image: mongo:5.0.2
    command: mongod --port 27017 
    expose:
      - "27017"
    ports:
      - "27017:27017"

  redis:
    image: redis:3.2.4
    expose:
      - "6379"
    ports:
      - "6379:6379"


```

1. run docker-compose run mongo

every litem in the docker compose file will be started (it posts a "healthy check"). In this case we have 40+ different items in our docker-compose file and it spams the terminal with health checks. The intended services fail to start up
