### ISSUE TITLE
cannot mount nfs share on Mac PC into minikube pods due to docker for mac

### ISSUE THREAD

**Issue by hiroaki2020** [docker/for-mac#6280]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0A1161B7-830A-4B67-97A6-419E67E07A7D/20220415055810

Please note I believe **this is a docker for mac issue**. Scroll down to "Why I believe this is a docker for mac issue" section for details.
### Expected behavior
nfs share on Mac PC is mounted into minikube pods successfully.
### Actual behavior
nfs mount doesn't work. `kubectl describe po name-of-the-pod-with-mount-point` outputs following error msg.
```
...

Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  6m40s                default-scheduler  running PreBind plugin "VolumeBinding": Operation cannot be fulfilled on persistentvolumes "app-dir-pv": the object has been modified; please apply your changes to the latest version and try again
  Normal   Scheduled         6m39s                default-scheduler  Successfully assigned default/name-of-the-pod-with-mount-point to minikube
  Warning  FailedMount       32s (x2 over 3m36s)  kubelet            MountVolume.SetUp failed for volume "app-dir-pv" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs host.minikube.internal:/PATH/TO/NFS/SHARE/ON/MY/MAC/PC /var/lib/kubelet/pods/*******************/volumes/kubernetes.io~nfs/app-dir-pv
Output: mount.nfs: Connection timed out
  Warning  FailedMount  6s (x3 over 4m36s)  kubelet  Unable to attach or mount volumes: unmounted volumes=[app], unattached volumes=[app kube-api-access-*****]: timed out waiting for the condition
```
### Information

  - macOS Version: macOS Monterey version 12.1
  - Intel chip or Apple chip: Intel chip
  - Docker Desktop Version: 4.6.1
  - Is it reproducible? Yes
  - Is the problem new? it's new as far as I know
  - Did the problem appear with an update? No

nfs server: my macOS PC(Intel chip)
nfs client: persistent volume directories in 2 minikube node containers
I successfully mounted the local nfs share to another local directory, which means nfs server works properly.

I use docker driver for minikube by which minikube k8s node starts as a container.
I use multinode minikube cluster. It consists of 1 master and 1 worker node.
I also use 2 replicas of pod with mount point.

### Steps to reproduce the behavior

  **1. Create minikube multinode cluster with docker driver**
Run `minikube start --nodes 2 --driver=docker`
  **2. Set up nfs server**
Firstly, run `minikube ip` and `minikube ip -n minikube-m02` to get node IPs. Then write them into /etc/exports file.
In my case, nfs server is Mac PC, so create /etc/exports which is like
```
/PATH/TO/NFS/SHARE/ON/MY/MAC/PC -mapall=user:group 172.19.**.** 172.19.**.** (=IPs you just got by running `minikube ip`)
```
Then run `sudo nfsd update` to reflect the change.
  **3. Create k8s resources**
Put a following k8s config file named as k8s-nfs-test.yaml in a current directory and run `kubectl apply -f k8s-nfs-test.yaml`
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: app-dir-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-dir-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: app-dir-sc
  nfs:
# Please note I use my host PC(MacOS) as nfs server
    server: host.minikube.internal
    path: /PATH/TO/NFS/SHARE/ON/MY/MAC/PC
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
          - minikube-m02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-dir-pvc
spec:
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: app-dir-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      service: app
  replicas: 2
  template:
    metadata:
      labels:
        service: app
    spec:
      containers:
      - name: app
        image: ubuntu
        imagePullPolicy: Never
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "128Mi"
            cpu: "10m"
        ports:
        - containerPort: 9000
        volumeMounts:
          - mountPath: /tmp
            name: app
      volumes:
        - name: app
          persistentVolumeClaim:
            claimName: app-dir-pvc
```
  **4. Get a name of a pod.**
Run `kubectl get po` and copy a name of either pod.
  **5. Show the error msg.**
Run `kubectl describe po "pod name you just copied"` to get the error msg.

### Why I believe this is a docker for mac issue
I heard nfs mount works with minikube with virtualbox driver (but I haven't tried because of tight memory resource of my pc.) With docker driver, however, I haven't seen any success so far. In addition to a simple example above, I also tried to manually mount nfs share on my PC into minikube node container (that is, get into node container with `minikube ssh` and run `mount` cmd manually) but this doesn't work as well. Further, I tried to do the same thing on kind cluster as well (that is, try to mount nfs pv and mount nfs share manually on kind cluster) but didn't succeed. Like minikube with docker driver, kind's node also starts as a container. Furthermore, since mounting local nfs share to another local directory was successful, the problem is more likely to be on the client side.

What I can see from these facts and a tip from kind contributor[(source)](https://github.com/kubernetes-sigs/kind/issues/2708) is that nfs mount is successful with vm driven minikube (that is, minikube node is vm.) but not with docker driver. That is why I believe this is a docker for mac issue, not a minikube or kind one.

I did further research on docker and thought the cause was that docker desktop for mac uses unix domain socket (=docker.sock) to build connection between host pc network and docker network and nfs only supports tcp and udp so I actually ran socat container and set DOCKER_HOST env var to redirect traffic to docker.sock to tcp and vice versa so that traffic from nfs server on host pc goes to tcp. Unfortunately, this doesn’t solve the problem. So now I don't know what to do with this problem. Could you help me find this out?

Thanks in advance
