### ISSUE TITLE
Kubernetes is not exposing Node Ports to the host in Mac M1

### ISSUE THREAD

**Issue by quim3ra** [docker/for-mac#6339]
I have correctly setup my `/etc/hosts` in my mac m1:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1    localhost
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section

```
Working with docker desktop version 4.8.2 (79419) And having setup my k8s files as follows:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: cbelizon/posts
```
```
apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
   app: posts
  ports:
   - name: posts
     protocol: TCP
     port: 4000
     targetPort: 4000
```

When I run `k logs posts-depl-647cb69856-pzjtk`

```
posts@1.0.0 start
nodemon index.js

[nodemon] 2.0.16
[nodemon] to restart at any time, enter rs
[nodemon] watching path(s): .
[nodemon] watching extensions: js,mjs,json
[nodemon] starting node index.js
v55
Listening on 4000
```

When I run `k describe service posts-srv`

```
Name:                     posts-srv
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 app=posts
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.99.64.231
IPs:                      10.99.64.231
LoadBalancer Ingress:     localhost
Port:                     posts  4000/TCP
TargetPort:               4000/TCP
NodePort:                 posts  32697/TCP
Endpoints:                10.1.0.34:4000
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

`It is impossible to me to access http://localhost:32697/ 

The connection is refused, is there anything else that needs to be done to make docker desktop to make available the node ports to the host?
