### ISSUE TITLE
VirtioFS wants to create a /host_mnt folder into the root of the disc, but MacOS say is read only FS

### ISSUE THREAD

**Issue by cristianpatrichi** [docker/for-mac#6375]
I try to use VirtioFS, but it crashes on volume creation with error:

Error response from daemon: error while creating mount source path '/host_mnt/private/tmp/com.apple.launchd.wxmkUy2zBy/Listeners': mkdir /host_mnt/private/tmp/com.apple.launchd.wxmkUy2zBy/Listeners: operation not supported

Docker tries to create the /host_mnt/... folders into the root of the disc, which is now allowed by MacOS.

MacBook Pro M1 Pro, MacOS v12.3.1, Docker v4.7.0 (77141) .

**Comment by wizardist** [comment]
Do you by any chance use `$SSH_AUTH_SOCK` or similar for volume mapping in Docker or Docker Compose?

I don't think it has never worked on Mac, but with VirtioFS enabled it seems to now show an error and abort.

**Comment by loicrey** [comment]
Yes I use that.
 
It works, launching ssh-agent and ssh-add is successfully forwarding my SSH agent inside my containers but I need to do that everytime I recreate my volumes (and have to remove the directory I mentionned above

**Comment by tsrivishnu** [comment]
I'm facing the same issue. I have the following in docker-compose
```yaml
  app_with_ssh_forwarding:
    user: root
    environment:
      SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
    volumes:
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
```

When using VirtioFS, this fails with the error: 

```
Error response from daemon: error while creating mount source path '/host_mnt/private/tmp/com.apple.launchd.t87HDymVHN/Listeners': mkdir /host_mnt/private/tmp/com.apple.launchd.t87HDymVHN/Listeners: operation not supported
```
That is same path as the SSH agent socket `echo $SSH_AUTH_SOCK` gives `/private/tmp/com.apple.launchd.t87HDymVHN/Listeners`.

The same configuration works perfectly fine when I disable VirtioFS.
