### ISSUE TITLE
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

### ISSUE THREAD

**Issue by akhilespande** [docker/for-mac#6479]
**Error :** 
```
[INFO]  > Running creator
[INFO]     [creator]     Previous image with name "myorg/myapp:latest" not found
[INFO]     [creator]     ===> DETECTING
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped 
```

**My machine details are:**

macOsBigSur
Version - 11.2.2 
Chip - Apple M1
RAM - 16 GB

**Reproduce :**  Building a Docker Image with Maven

`./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=myorg/myapp
`

**Comment by ruslantau** [comment]
Hi! I got the similar error on my Macbook Air 2022 when I ran `docker-compose up`. 

**Logs:**
```
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
contacts-in-item-ruslantau  | <jemalloc>: (This is the expected behaviour if you are running under QEMU)
contacts-in-item-ruslantau  | qemu: uncaught target signal 11 (Segmentation fault) - core dumped

```

**My machine details are:**
macOS Monterey 12.5
Chip Apple M2
RAM 8Gb

**docker-compose.yaml**
```
version: '2.3'
services:
    dev:
        # runtime: nvidia
        build:
          context: ./
          dockerfile: ./Dockerfile
        platform: linux/amd64
        image: contacts-in-item:$USER
        container_name: contacts-in-item-$USER
        volumes:
            - ./:/app
            - ./data:/data
            - ./data:/test_data
        ipc: host
        shm_size: 8G
        command: /bin/bash -c "python lib/run.py --debug"
        network_mode: none
```

**Dockerfile**
```
FROM nvidia/cuda:10.2-devel-ubuntu18.04
RUN apt-get update && \
	apt-get install -y curl python3.8 python3.8-distutils && \
	ln -s /usr/bin/python3.8 /usr/bin/python && \
	rm -rf /var/lib/apt/lists/*
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py && \
    python -m pip install -U pip==20.3.3
ENV PROJECT_ROOT /app
ENV DATA_ROOT /data
ENV TEST_DATA_ROOT /test_data
RUN mkdir $PROJECT_ROOT $DATA_ROOT
COPY . $PROJECT_ROOT
WORKDIR $PROJECT_ROOT
RUN pip install -r requirements.txt
CMD python lib/run.py
```
