### ISSUE TITLE
Unexpect twice decoded for `$` in Dev Environments

### ISSUE THREAD

**Issue by mapleeit** [docker/for-mac#6489]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

This `docker-compose.yaml` should be able to be started correctly in Dev Environments

```yaml
version: '3.9'
services:
    mongo:
        image: mongo:5
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: xxx
            MONGO_INITDB_ROOT_PASSWORD: xxx
            MONGO_INITDB_DATABASE: xxx
        volumes:
            - ./.docker/mongo/random.key:/data/random.key
            - ./.docker/mongo/init-repl-set.sh:/docker-entrypoint-initdb.d/init-repl-set.sh
        entrypoint:
            - bash
            - -c
            - |
                cp /data/random.key /data/repl.key
                chmod 400 /data/repl.key
                chown 999:999 /data/repl.key
                exec docker-entrypoint.sh $$@
        command: 'mongod --bind_ip_all --replSet rs0 --keyFile /data/repl.key'
        networks:
          default:
            aliases:
              - mongo-replset-1.dev.jina.ai
              - mongo.dev.jina.ai
```

### Actual behavior

Throw error:

```
invalid interpolation format for services.mongo.entrypoint.[].
You may need to escape any $ with another $.
cp /data/random.key /data/repl.key
chmod 400 /data/repl.key
chown 999:999 /data/repl.key
exec docker-entrypoint.sh $@

exit status 15
```

### Information

  - macOS Version: 12.2.1
  - Intel chip or Apple chip: M1
  - Docker Desktop Version: 4.12.0

### My guess

I know in `docker-compose.yaml`, if one wants to use `${VAR}`, it needs to use `$${VAR}`. But here in Dev Environments, we need to use `$$$${VAR}` to achive that. So I believe it's somehow decoded twice, which apparently is a bug.
