### ISSUE TITLE
M1 macOS NFS mounted folders within container are not letting to create file even modifying and deleting possible

### ISSUE THREAD

**Issue by nihavend** [docker/for-mac#6523]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:379A3C1F-B27F-4C92-9894-BC3367B8AC20/20221017172547

### Expected behavior
can create new file in mount folder
### Actual behavior
can not create a new file in mount folder but can delete or modify
### Information

  - macOS Version: 12.6
  - Intel chip or Apple chip: Apple M1 Max
  - Docker Desktop Version:4.12.0

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`

```
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

```
### Steps to reproduce the behavior

  1. Run the below compose file with local path for volumes
  ```
version: '2'    
services:

  mount-server:
    container_name: mdl-mount-server
    image: itsthenetwork/nfs-server-alpine:12
    privileged: true
    ports:
      - 2049:2049
    environment:
      - SHARED_DIRECTORY=/local
    volumes:
      - /localpath/mnt:/local
 ```
   
  2. inside container mount the folder with `mount mount-server:/ /mnt`
  3. inside mnt folder you see files if any and modify it if exists but can not create new file
  ```
      root@0be22882020d:/mnt # echo "deneme" > a.txt
      bash: a.txt: Operation not permitted  
```
I guess this [issue](https://stackoverflow.com/questions/74078617/nfs-mount-within-containeralpine-to-hostm1-nfs-server-fails-with-error-per) is also related
