### ISSUE TITLE
User is not added to the group set by fsGroup parameter in Pod spec

### ISSUE THREAD

**Issue by kamialie** [docker/for-mac#6663]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2A8DA853-CCB4-4DAC-B858-B5FD5957A1C3/20230106081646

### Expected behavior

This is related to containerd beta feature, I have also filed a feedback through Google forms, but decided to open an issue as well to provide steps to reproduce the behavior.

User inside container is added to the group specified by `fsGroup` parameter in Pod spec.

### Actual behavior

User is not added to the group, and can't access filesystem available for that group.

### Information

  - macOS Version: 13.1 (22C65)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.15.0 (93002)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
<img width="1440" alt="Screenshot 2023-01-06 at 09 33 24" src="https://user-images.githubusercontent.com/43202110/210962736-1432dc31-e204-42f1-8489-7ee56de431f8.png">

### Steps to reproduce the behavior

1. Enable containerd beta feature
2. Start Kubernetes cluster
3. Apply the following deployment with `kubectl apply -f ubuntu.yaml`:
    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: ubuntu
      name: ubuntu
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: ubuntu
      template:
        metadata:
          labels:
            app: ubuntu
        spec:
          containers:
          - image: ubuntu
            name: ubuntu
            command:
              - bash
              - "-c"
              - "sleep infinity"
          securityContext:
            fsGroup: 1200
    ```
4. Enter container and check group(s) that current user belongs to:
    ```shell
    $ kubectl exec -ti ubuntu-... -- bash
    $ id
    ```

Following steps above produces the following output:
```shell
$ id
uid=0(root) gid=0(root) groups=0(root)
```

Disabling containerd feature resolved the issue:
```shell
$ id
uid=0(root) gid=0(root) groups=0(root),1200
````
