### ISSUE TITLE
Docker stops listening on UDP port

### ISSUE THREAD

**Issue by jabenninghoff** [docker/for-mac#674]
### Expected behavior

I'm running [graylog2](https://hub.docker.com/r/graylog2/server/) on Docker for Mac 1.12.1, using `docker-compose` listening on UDP port 1514. Graylog should ingest all log data sent to it via syslog from remote macs.

### Actual behavior

Graylog ingests syslog data for a varying period of time (generally less than an hour), then stops recording new messages. Restarting the graylog container using `docker restart` resumes logging.

### Information

The following error messages appear in `/var/log/system.log` at the time Graylog stops recording new messages:

```
Sep 19 11:31:05 myhost Docker[1365]: Socket.Datagram.recvfrom: dropping partial response
Sep 19 11:31:05 myhost Docker[1365]: udp:0.0.0.0:1514:udp:172.18.0.4:1514: shutting down recvfrom thread: (Failure "Socket.Datagram.recvfrom partial response")
```

Diagnostics:
```
Docker for Mac: version: 1.12.1 (2d5b4d9)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/1D6B63C2-00F4-4689-A324-4081FA1C59A9/20160919-144050.tar.gz
[OK]     docker-cli
[OK]     virtualization kern.hv_support
[OK]     menubar
[OK]     moby-syslog
[OK]     dns
[OK]     disk
[OK]     system
[OK]     app
[OK]     osxfs
[OK]     virtualization VT-X
[OK]     db
[OK]     slirp
[OK]     logs
[OK]     env
[OK]     vmnetd
[OK]     moby-console
[OK]     moby
[OK]     driver.amd64-linux
```

### Steps to reproduce the behavior

1. Launch Graylog with `docker-compose up -d` using the `docker-compose.yml` below
2. Add a new Syslog UDP Input from the Systems > Inputs page in Graylog. Select the running node, port 1514, otherwise default settings
3. Configure OS X systems to forward to Graylog per the docs: http://docs.graylog.org/en/2.1/pages/sending_data.html#sending-syslog-from-macos-x-hosts
4. Wait for error message

Here is my `docker-compose.yml` (passwords and secrets have been changed):

```
version: '2'
services:
  mongo:
    image: "mongo:3"
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
    environment:
      TZ: US/Central
  elasticsearch:
    image: "elasticsearch:2"
    restart: unless-stopped
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      TZ: US/Central
    ulimits:
      nofile: 65536
  graylog:
    image: graylog2/server:2.1.1-1
    restart: unless-stopped
    volumes:
      - ./data/journal:/usr/share/graylog/data/journal
    environment:
      TZ: US/Central
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_ROOT_TIMEZONE: US/Central
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api/
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201/udp:12201/udp"
      - "1514/udp:1514/udp"
```
