### ISSUE TITLE
Running webpack-dev-server crushes CPU

### ISSUE THREAD

**Issue by ascendantlogic** [docker/for-mac#73]
### Expected behavior

Normal-ish CPU usage. Running this outside of a container uses ~16% CPU
### Actual behavior

300% usage by hyperkit process, 100% usage by osxfs process

![image](https://cloud.githubusercontent.com/assets/60331/17331028/2f41f8fa-5897-11e6-9527-b6309e32b56e.png)
### Information

Diagnostic ID: E813C46C-9C75-4BAE-890E-A021E28A9591
Docker for Mac: 1.12.0-beta21 (Build 10868)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
### Steps to reproduce
1. Set up Alpine 3.4 container with node/npm/webpack/etc
2. run `webpack-dev-server` from a volume mount

Side note: I was using docker-compose for this, but I assume everything under the hood is still the same.

**Comment by dave-tucker** [comment]
Thanks for the report @ascendantlogic 
Could you provide a minimal `Dockerfile` and/or `docker-compose.yml` that will reproduce the problem? This will make it much easier for us to try and figure out what's going on.

**Comment by dsheets** [comment]
You likely have `webpack-dev-server` configured to poll the file system for changes. Instead, could you configure `webpack-dev-server` to listen for `inotify` events from the kernel? Docker for Mac bind mounts (`-v`) support `inotify` events.

**Comment by ascendantlogic** [comment]
docker-compose.yml

```
version: '2'
services:
  db:
    image: postgres:9.5
    networks:
      - v3
    environment:
      - POSTGRES_USER=derp
      - POSTGRES_PASSWORD=derp
    ports:
      - "5432:5432"
  migration:
    build: ./api-v3/
    image: api_v3
    entrypoint: ./wait-for-it.sh db:5432
    command: -- bundle exec rake db:create db:migrate
    volumes:
      - ./api-v3:/app
    depends_on:
      - db
    networks:
      - v3
  api:
    build: ./api-v3/
    image: api_v3
    command: bundle exec rails server
    volumes:
      - ./api-v3:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migration
    networks:
      - v3
  app:
    build: ./facility-app/
    image: app_v3
    command: npm run startdocker
    volumes:
      - ./facility-app:/app
    ports:
      - "8081:8081"
    depends_on:
      - api
    networks:
      - v3
networks:
  v3:
    driver: bridge
```
